### ISSUE TITLE
nodeFit ignores priority class

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#1014]
**What version of descheduler are you using?**

descheduler version: 0.24.1

**Does this issue reproduce with the latest release?** Yes

**Which descheduler CLI options are you using?**
```
--logging-format text --policy-config-file /policy-dir/policy.yaml --v 4
```

**Please provide a copy of your descheduler policy config file**
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
evictLocalStoragePods: true
strategies:
  RemovePodsViolatingTopologySpreadConstraint:
    enabled: true
    params:
      includeSoftConstraints: true
      labelSelector:
        matchExpressions:
        - {key: descheduler.k8s.io/opt-in, operator: In, values: ["true"]}
```

**What k8s version are you using (`kubectl version`)?** 1.25

**What did you do?**
Take the following scenario where we have a [2, 0] spread from Deployment 'A'.

*Node1 (2 vCPU, 4Gi)*
PodA1 (1 vCPU, 2Gi), high-priority class
PodA2 (1 vCPU, 2Gi), high-priority class

*Node2 (2 vCPU, 4Gi)*
PodX1 (2 vCPU, 4Gi), low-priority class

**What did you expect to see?**
_Node2_ to be considered as having resources to schedule one of PodA, given that _PodX1_ on _Node2_ has a lower priority class and will be preempted by Scheduler.

**What did you see instead?**
Nodefit logic determines that Node2 has no resources to give so does not evict one of the Pods on _Node1_
