### ISSUE TITLE
client-side throttling, not priority and fairness

### ISSUE THREAD

**Issue by dmitry-mightydevops** [kubernetes-sigs/descheduler#1027]
**What version of descheduler are you using?**

descheduler version: 0.25.2

**Does this issue reproduce with the latest release?**

yes

**Which descheduler CLI options are you using?**

```
cmdOptions:
    v: 3
```

**Please provide a copy of your descheduler policy config file**

```yaml
➜ kgcm descheduler -o yaml
apiVersion: v1
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    evictFailedBarePods: true
    evictLocalStoragePods: true
    ignorePvcPods: false
    maxNoOfPodsToEvictPerNamespace: 10
    maxNoOfPodsToEvictPerNode: 10
    strategies:
      LowNodeUtilization:
        enabled: true
        nodeFit: true
        params:
          namespaces:
            exclude:
            - mysql57
            - influxdb
            - mongodb
            - etcd
            - prometheus
            - monitoring
            - ops
            - metrics-server
          nodeResourceUtilizationThresholds:
            targetThresholds:
              cpu: 70
              memory: 70
              pods: 50
            thresholds:
              cpu: 40
              memory: 40
              pods: 20
      PodLifeTime:
        enabled: true
        params:
          namespaces:
            include:
            - mysql57
            - influxdb
            - mongodb
            - etcd
            - utils
          podLifeTime:
            maxPodLifeTimeSeconds: 86400
      RemoveDuplicates:
        enabled: false
        nodeFit: true
      RemovePodsHavingTooManyRestarts:
        enabled: true
        params:
          podsHavingTooManyRestarts:
            includingInitContainers: true
            podRestartThreshold: 20
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true
        nodeFit: true
      RemovePodsViolatingNodeAffinity:
        enabled: true
        nodeFit: true
        params:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
      RemovePodsViolatingNodeTaints:
        enabled: true
        nodeFit: true
      RemovePodsViolatingTopologySpreadConstraint:
        enabled: true
        nodeFit: true
        params:
          includeSoftConstraints: false
kind: ConfigMap
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
➜ k version               
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:32:14Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**
I started getting the following log in the descheduler pod

```
I1220 20:34:19.947974       1 request.go:533] Waited for 194.413528ms due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/api/v1/namespaces/oprs/pods
I1220 20:34:20.147238       1 request.go:533] Waited for 195.264831ms due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/api/v1/namespaces/ops/pods
I1220 20:34:20.347929       1 request.go:533] Waited for 189.438292ms due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/api/v1/namespaces/opsgenie/pods
```

How to get rid of them?

**Comment by damemi** [comment]
That error is coming from the kube client/api server, not specifically a descheduler issue. Maybe we can update our client config though to avoid that.

Just curious, what interval are you running the descheduler at? Wondering if that is causing the throttling.

**Comment by dmitry-mightydevops** [comment]
@damemi I always get it regardless of the period. I had it `*/15 * * * *`, and now `0 0 * * SUN` but still do see these messages.

It seems this can be fixed at the client level, I faced similar issue using kubernetes-event-exporter
https://github.com/resmoio/kubernetes-event-exporter/issues/27 

and the fix was by adding the folllowing to the config

```yaml
        config:
          logLevel: error
          logFormat: json
          throttlePeriod: 10  <----------------THIS
          maxEventAgeSeconds: 10 <----------------THIS
          kubeQPS: 60 <----------------THIS
          kubeBurst: 60 <----------------THIS
          receivers:
            - name: "dump"
              file:
                path: "/dev/stdout"
                layout:
                  message: "{{ printf "{{ .Message }}" }}"
                  reason: "{{ printf "{{ .Reason }}" }}"
                  type: "{{ printf "{{ .Type }}" }}"
                  count: "{{ printf "{{ .Count }}" }}"
                  kind: "{{ printf "{{ .InvolvedObject.Kind }}" }}"
                  name: "{{ printf "{{ .InvolvedObject.Name }}" }}"
                  namespace: "{{ printf "{{ .Namespace }}" }}"
                  component: "{{ printf "{{ .Source.Component }}" }}"
                  host: "{{ printf "{{ .Source.Host }}" }}"

```
