### ISSUE TITLE
No logs during cron execution

### ISSUE THREAD

**Issue by Whisper40** [kubernetes-sigs/descheduler#1031]
**What version of descheduler are you using?**

descheduler version: v0.21 (Kube 1.21)

**Does this issue reproduce with the latest release?**
Cannot test, because i use kube 1.21

**Which descheduler CLI options are you using?**
v: 8

**Please provide a copy of your descheduler policy config file**
```
    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: true
        RemovePodsViolatingNodeTaints:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
        LowNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 40
                memory: 40
                pods: 20
              targetThresholds:
                cpu: 80
                memory: 80
                pods: 50
        HighNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                memory: 20
        PodLifeTime:
          enabled: true
          params:
            # 14 days, then kicked
            podLifeTime:
              maxPodLifeTimeSeconds: 1209600
        RemovePodsHavingTooManyRestarts:
          enabled: true
          params:
            podsHavingTooManyRestarts:
              podRestartThreshold: 20
              includingInitContainers: true
```

**What k8s version are you using (`kubectl version`)?**

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:08:11Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:02:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

```
master-101:~# kubectl -n kube-system logs descheduler-27873184-w42dq
I1230 09:04:02.648713       1 secure_serving.go:197] Serving securely on [::]:10258
I1230 09:04:02.648825       1 tlsconfig.go:240] Starting DynamicServingCertificateController
```

**What did you expect to see?**
I expect to see more logs, what he did, what he ignored. Actually i can see pods that cannot be evicted.
I would like to see pods that have been evicted for specific reason
**What did you see instead?**
" Starting DynamicServingCertificateController"
