### ISSUE TITLE
PodAntiAffinity when doing LowNodeUtilization with nodefit set to true.

### ISSUE THREAD

**Issue by atropos112** [kubernetes-sigs/descheduler#1050]
**Is your feature request related to a problem? Please describe.**
I am noticing that in quiet a lot of cases the descheduler is descheduling pods that have podAntiAffinity. This descheduling is pointless because there is no "fit node" that can have this pod scheduled onto (other than the node from which pod is being descheduled) because of the podAntiAffinity constraint, as a result the pod is killed just to be re-scheduled on the same node.

**Describe the solution you'd like**
NodeFit looks if there is another node that could take run this pod, this includes checking nodeAffinity but not podAntiAffinity so something like this 
```
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "component"
                  operator: In
                  values:
                  - alert-manager
                - key: "app"
                  operator: In
                  values:
                  - prometheus
            topologyKey: "kubernetes.io/hostname" 
```
means nothing to descheduler when killing the pods using the LowNodeUtilization strategy. It would be good for node fit to account for this.

**Describe alternatives you've considered**
Run the descheduler once every few hours and accept that some pods will be killed pointlessly.

**What version of descheduler are you using?**

descheduler version:
0.26.0
