### ISSUE TITLE
Set up MostAllocated Strategy in GKE

### ISSUE THREAD

**Issue by marandalucas** [kubernetes-sigs/descheduler#1073]
Hi folks,

We are trying to Balance low utilization nodes, but we were not able to change the strategy to MostAllocated in GKE.

```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
- pluginConfig:
  - args:
      scoringStrategy:
        resources:
        - name: cpu
          weight: 1
        type: MostAllocated
    name: NodeResourcesFit
```

The previous manifests can not be applied in GKE (v1.24.9-gke.3200). In addition, We didn't find out how we can configure it.

Is Anyone working in GKE?

Thanks in advance
