### ISSUE TITLE
Prometheus: TLS certificate does not contain IP SANs

### ISSUE THREAD

**Issue by stephan2012** [kubernetes-sigs/descheduler#1102]
**What version of descheduler are you using?**

descheduler version: `v0.26.0`

**Does this issue reproduce with the latest release?** yes!

**Which descheduler CLI options are you using?**

```yaml
      - args:
        - --policy-config-file
        - /policy-dir/policy.yaml
        - --descheduling-interval
        - 5m
        - --v
        - "3"
        - --leader-elect=true
        - --leader-elect-lease-duration=15s
        - --leader-elect-renew-deadline=10s
        - --leader-elect-retry-period=2s
        - --leader-elect-resource-lock=leases
        - --leader-elect-resource-name=descheduler
        - --leader-elect-resource-namespace=kube-system
        command:
        - /bin/descheduler
```

**Please provide a copy of your descheduler policy config file**

N/A

**What k8s version are you using (`kubectl version`)?** v1.24.12

**What did you do?**

Let Prometheus scrape metrics from the descheduler.

**What did you expect to see?**

A TLS certificate that allows Prometheus to scrape metrics would be nice. 

**What did you see instead?**

The descheduler creates a TLS certificate that does not include an IP address, causing Prometheus to refuse to scrape even when instructed to skip TLS verification:

```text
Get "https://172.30.95.137:10258/metrics": x509: cannot validate certificate for 172.30.95.137 because it doesn't contain any IP SANs
```

Looks like adding the Pod IP address would be sufficient. However, I am aware that IP address auto-detection might be tricky if the Pod has multiple interfaces attached (e.g., with Multus). Solutions could be

* Resolve own Pod IP address through kube-dns
* Use the Kubernetes Downward API and a command line argument to pass the IP address
