### ISSUE TITLE
Failed to list nodes

### ISSUE THREAD

**Issue by Yangxiaohan0120** [kubernetes-sigs/descheduler#1117]
I have deployed descheduler on my server. I used the serviceaccount，configmap and cronjob to do it.
when I finished these steps，the pod descheduler has started but it can't get the node list. Then it just completed for every thirty minutes.

The logs of the cronjob has been placed under the line.

```
I0413 09:00:06.598043       1 reflector.go:202] Starting reflector *v1.Node (1h0m0s) from github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:84
I0413 09:00:06.598112       1 reflector.go:240] Listing and watching *v1.Node from github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:84
E0413 09:00:06.624574       1 reflector.go:205] github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:84: Failed to list *v1.Node: v1.NodeList: .......
I0413 09:00:06.698153       1 node.go:51] node lister returned empty list, now fetch directly
E0413 09:00:06.703838       1 server.go:46] v1.NodeList: Items: []v1.Node: v1.Node: ......
```

but I do have two nodes which need to be balanced on pods. What is the problem？

**Comment by damemi** [comment]
Hi @Yangxiaohan0120 , could you share your versions of descheduler and kubernetes, as well as the descheduler config you are using?

**Comment by Yangxiaohan0120** [comment]
kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-tke.28", GitCommit:"46c99f0a9c5636b9d5b277763b54ed0617169d14", GitTreeState:"clean", BuildDate:"2022-11-03T07:44:05Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

descheduler config :
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler
data:
  policy.yaml: |-  
    apiVersion: descheduler/v1alpha1
    kind: DeschedulerPolicy
    strategies:
      RemoveDuplicates:
         enabled: false
      LowNodeUtilization:
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               cpu: 20
               memory: 20
               pods: 20
             targetThresholds:
               cpu: 50
               memory: 50
               pods: 50
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true
      RemovePodsViolatingNodeAffinity:
        enabled: true
        params:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
```

cronjob config
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: descheduler
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    metadata:
      name: descheduler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: "true"
    spec:
      template:
        spec:
          serviceAccountName: descheduler
          containers:
          - name: descheduler
            image: komljen/descheduler:v0.5.0-4-ga7ceb671
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:
            - /bin/descheduler
            - --v=4
            - --max-pods-to-evict-per-node=10
            - --policy-config-file=/policy-dir/policy.yaml
          restartPolicy: "OnFailure"
          volumes:
          - name: policy-volume
            configMap:
              name: descheduler
```

**Comment by damemi** [comment]
Thanks for the quick reply. Unfortunately I don't think we can offer much help because your k8s+descheduler versions are very outdated. I strongly recommend updating to a more recent version of Kubernetes, as 1.20 is no longer supported by the community. It looks like you are running Descheduler v0.5.0, which is also long past our support window.

To try to answer your question, it looks like the Node lister is actually getting some nodes once it [fetches them directly](https://github.com/kubernetes-sigs/descheduler/blob/a6af54ab309d59adb43bedb86227cacdf1d71116/pkg/descheduler/node/node.go#L51) based on this log line, which I am assuming you truncated:
```
E0413 09:00:06.703838       1 server.go:46] v1.NodeList: Items: []v1.Node: v1.Node: ......
``` 

The message you're seeing is probably just indicating that the cache is empty (since this is a job and each iteration starts with an empty cache, that makes sense). If you're not seeing any other logs or pods evicted, it might be that there is just nothing to evict after that point.

**Comment by damemi** [comment]
If there is nothing to do, some strategies will log messages saying that (like this example in LowNodeUtilization: https://github.com/kubernetes-sigs/descheduler/blob/a6af54ab309d59adb43bedb86227cacdf1d71116/pkg/descheduler/strategies/lownodeutilization.go#L69). Other strategies might say nothing.

**Comment by Yangxiaohan0120** [comment]
Thank you for your detailed reply, it is very useful, I will try to deploy it in other ways

**Comment by Yangxiaohan0120** [comment]
My pod has completed all the task which has the status "Completed". However the pods only deploy on two nodes while I have three nodes. The pod log only have these five lines
```
I0413 09:00:06.598043       1 reflector.go:202] Starting reflector *v1.Node (1h0m0s) from github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:84
I0413 09:00:06.598112       1 reflector.go:240] Listing and watching *v1.Node from github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:84
E0413 09:00:06.624574       1 reflector.go:205] github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:84: Failed to list *v1.Node: v1.NodeList: .......
I0413 09:00:06.698153       1 node.go:51] node lister returned empty list, now fetch directly
E0413 09:00:06.703838       1 server.go:46] v1.NodeList: Items: []v1.Node: v1.Node: ......
```

And this is my configmap and my nodes details：
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 20
               "memory": 20
               "pods": 20
             targetThresholds:
               "cpu" : 50
               "memory": 50
               "pods": 50


```

```
NAME           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
10.70.32.179   184m         9%     2324Mi          40%       
10.70.34.210   79m          4%     388Mi           6%        
10.70.73.208   444m         11%    1342Mi          23%       

```
