### ISSUE TITLE
failed decoding policy config : strict decoding error: unknow field \" namesapces.include\"

### ISSUE THREAD

**Issue by AllenZMC** [kubernetes-sigs/descheduler#1121]
**What version of descheduler are you using?**

descheduler version: master branch

```
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: ProfileName
    pluginConfig:
    - name: "DefaultEvictor"
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 86400
        namespaces:
          include:
          - "namespace1"
          - "namespace2"
    plugins:
      evict:
        enabled:
          - "DefaultEvictor"
      deschedule:
        enabled:
          - "PodLifeTime"
```
