### ISSUE TITLE
RemovePodsViolatingInterPodAntiAffinity dont see my wrongly placed pods

### ISSUE THREAD

**Issue by Rumplown** [kubernetes-sigs/descheduler#1125]
**What version of descheduler are you using?**

descheduler version: v0.21

**Does this issue reproduce with the latest release?**
yes

**Which descheduler CLI options are you using?**
`--dry-run --v 5`

**Please provide a copy of your descheduler policy config file**
```yaml
 apiVersion: "descheduler/v1alpha1"
 kind: "DeschedulerPolicy"
 strategies:
   HighNodeUtilization:
     enabled: false
   LowNodeUtilization:
     enabled: false
     params:
       nodeResourceUtilizationThresholds:
         targetThresholds:
           cpu: 50
           memory: 50
           pods: 50
         thresholds:
           cpu: 20
           memory: 20
           pods: 20
   PodLifeTime:
     enabled: false
   RemoveDuplicates:
     enabled: false
   RemovePodsHavingTooManyRestarts:
     enabled: false
   RemovePodsViolatingInterPodAntiAffinity:
     enabled: true
   RemovePodsViolatingNodeAffinity:
     enabled: false
     params:
       nodeAffinityType:
       - requiredDuringSchedulingIgnoredDuringExecution
   RemovePodsViolatingNodeTaints:
     enabled: false
   RemovePodsViolatingTopologySpreadConstraint:
     enabled: false
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
Installed descheduler with helm chart version 0.21.0 and this values file:
```yaml
cmdOptions:
  dry-run:
  v: 5
deschedulerPolicy:
  strategies:
    RemoveDuplicates:
      enabled: false
    LowNodeUtilization:
      enabled: false
    HighNodeUtilization:
      enabled: false
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
    RemovePodsViolatingNodeAffinity:
      enabled: false
    RemovePodsViolatingNodeTaints:
      enabled: false
    RemovePodsViolatingTopologySpreadConstraint:
      enabled: false
    RemovePodsHavingTooManyRestarts:
      enabled: false
    PodLifeTime:
      enabled: false
```
Installed this deployment with podAntiAffinity on a 3 nodes cluster (the goal is to have one pod per node):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 85
  labels:
    app: test-proxy
  name: test-proxy
  namespace: test-affinity
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - test-proxy
              topologyKey: kubernetes.io/hostname
            weight: 100
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30  
```

Once deployed, the 3 replicas are spread accross my 3 nodes, all good. Then I simulate a wrong placement of my pods by doing so:
- edit the deployment to delete the anti affinity part
- Then the scheduler is placing my 3 pods on a single node
- re-edit my deployment to add my anti affinity rule

```
NAME↑                          READY   STATUS    NODE            
test-proxy-568fbf447b-hbrbj    1/1     Running   ppr-kub-01
test-proxy-568fbf447b-kms27    1/1     Running   ppr-kub-01
test-proxy-568fbf447b-vh8zs    1/1     Running   ppr-kub-01
```

**What did you expect to see?**
My 3 pods are now placed on the same node with an antiaffinity rule applied, I am in a situation where I want the descheduler to see this 3 badly placed pod and evict them so that the scheduler can replace them on the right node by respecting the antiaffinity rule.

**What did you see instead?**
The descheduler is checking my node with the anti affinity policy, but is doing nothing:
```
descheduler-28031636-zgdwk I0419 09:56:02.232719       1 named_certificates.go:53] loaded SNI cert [0/"self-signed loopback"]: "apiserver-loopback-client@1681898162" [serving] validServingFor=[apiserver-loop
descheduler-28031636-zgdwk I0419 09:56:02.232787       1 secure_serving.go:197] Serving securely on :10258                                                                                                     
descheduler-28031636-zgdwk I0419 09:56:02.232875       1 tlsconfig.go:240] Starting DynamicServingCertificateController                                                                                        
descheduler-28031636-zgdwk I0419 09:56:02.256389       1 node.go:46] "Node lister returned empty list, now fetch directly"                                                                                     
descheduler-28031636-zgdwk I0419 09:56:02.266485       1 pod_antiaffinity.go:81] "Processing node" node="ppr-kub-01"                                                                                     
descheduler-28031636-zgdwk I0419 09:56:02.321227       1 pod_antiaffinity.go:81] "Processing node" node="ppr-kub-02"                                                                                     
descheduler-28031636-zgdwk I0419 09:56:02.358066       1 pod_antiaffinity.go:81] "Processing node" node="ppr-kub-03"                                                                                     
descheduler-28031636-zgdwk I0419 09:56:02.410075       1 descheduler.go:151] "Number of evicted pods" totalEvicted=0
```

**Comment by Rumplown** [comment]
Hello @damemi, thx for your fast reply.
I just checked and yes the antiaffinity rule is set on the pod as seen below.
I saw in [this issue](https://github.com/kubernetes-sigs/descheduler/issues/494#issuecomment-771006304) that the pod antiAffinity strategy is only checking for `RequiredDuringSchedulingIgnoredDuringExecution` rule. 
Do you think it could be linked to my problem since I am on `Preferred` ?

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-proxy
  namespace: test-affinity
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - test-proxy
          topologyKey: kubernetes.io/hostname
        weight: 100
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ppr-kub-01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```
(I truncated non important part of the yml file)
