### ISSUE TITLE
The charts are not updating from values.yaml

### ISSUE THREAD

**Issue by kannamr** [kubernetes-sigs/descheduler#1126]
**What version of descheduler are you using?**

descheduler version: 0.26.1

**Does this issue reproduce with the latest release?**
 Yes

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
1.25.8
</pre></details>

**What did you do?**
- The securityContext values are not updating the cronJob chart. Instead taking the defaults
- Same with the `deschedulerPolicy`. Removed `RemovePodsViolatingTopologySpreadConstraint` from values.yaml, still it is created as part of policy.yaml

**What did you expect to see?**
Values updating the chart

**What did you see instead?**
default values

**Comment by damemi** [comment]
Hi @kannamr, can you please share your `values.yaml` file?

Fyi the security context isn't able to be customized in the [v0.26.1 helm chart](https://github.com/kubernetes-sigs/descheduler/blob/release-1.26/charts/descheduler/values.yaml). This is currently only on the master branch, which is considered in-development.

**Comment by kannamr** [comment]
@damemi please check the values.yaml. Thanks
```
# Default values for descheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# CronJob or Deployment
kind: CronJob

image:
  repository: registry.k8s.io/descheduler/descheduler
  # Versions are equal with current kubernetes version https://github.com/kubernetes-sigs/descheduler#compatibility-matrix
  tag: "v0.26.1"

#TODO - security context from this values is not updating the cronjob, need to use the patch 
securityContext:
  allowPrivilegeEscalation: true
  privileged: true
  runAsNonRoot: false

cronJobApiVersion: "batch/v1"  # Use "batch/v1beta1" for k8s version < 1.21.0. TODO(@7i) remove with 1.23 release
#Changed from default of every 2 min
schedule: "*/5 * * * *"

cmdOptions:
#Setting v=4 will log all reason why any pod is not evictable - can turn down to 3 after we feel comfortable
  v: 4

deschedulerPolicy:
  maxNoOfPodsToEvictPerNode: 10
  evictLocalStoragePods: true
  strategies:
    RemoveDuplicates:
      enabled: true
      params:
        removeDuplicates:
         excludeOwnerKinds:
         - "ReplicaSet"
    RemovePodsViolatingNodeTaints:
      enabled: true
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
#Evict pods that have restarted over 20 times.
    RemovePodsHavingTooManyRestarts:
      enabled: true
      params:
        podsHavingTooManyRestarts:
          podRestartThreshold: 20
          includingInitContainers: true
#Evict pods from nodes with >40% memory and >20% cpu usage and reschedule on nodes <30% memory and <10% cpu usage.
    LowNodeUtilization:
      enabled: true
      params:
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 10
            memory: 30
          targetThresholds:
            cpu: 20
            memory: 40

priorityClassName: system-cluster-critical

nodeSelector: {}
#  foo: bar

tolerations: []
# - key: 'management'
#   operator: 'Equal'
#   value: 'tool'
#   effect: 'NoSchedule'

rbac:
  # Specifies whether RBAC resources should be created
  create: true

#Disable until we can move to v0.21.0 where the docker container doesn't have to run as root
podSecurityPolicy:
  # Specifies whether PodSecurityPolicy should be created.
  create: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
```

**Comment by damemi** [comment]
Ok, the values look good but it's not clear to me which version of the Helm chart you're using. This comment:
```
#TODO - security context from this values is not updating the cronjob, need to use the patch 
securityContext:
  allowPrivilegeEscalation: true
  privileged: true
  runAsNonRoot: false
```

Sounds like you are using a custom patch? Or are you using the chart right from the master branch on github?
