### ISSUE TITLE
Override maxPodLifeTimeSeconds with a pod annotation

### ISSUE THREAD

**Issue by grosser** [kubernetes-sigs/descheduler#1128]
**Is your feature request related to a problem? Please describe.**
I want some pod to be killed sooner than the global maxPodLifeTimeSeconds.

**Describe the solution you'd like**
Setting a custom lifetime via a pod annotation.

**Describe alternatives you've considered**
Writing a new plugin.

**What version of descheduler are you using?**

descheduler version:  v0.26.1 

**Additional context**

**Comment by damemi** [comment]
This should be doable once v1alpha2 is released. If a label selector is sufficient you will be able to define a separate profile that has a different time for pods that match that label

**Comment by grosser** [comment]
Different profiles seems like a decent solution (could do 1d 12h 4h etc buckets).
Would prefer actual annotation parsing so I don't have to configure different profiles.

**Comment by a7i** [comment]
My preference would be to treat `DeschedulerPolicy` as the sole API as opposed to using annotation as an API.

With that being said, we _could_ add an override annotation to the API as a middle ground?
```
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 86400
        podLifeTimeSecondsAnnotationOverride: "descheduler.k8s.io/podlifetime"
```

**Comment by grosser** [comment]
yeah that sounds neat

**Comment by damemi** [comment]
> My preference would be to treat DeschedulerPolicy as the sole API as opposed to using annotation as an API.

+1, the api should be the source of truth. Ultimately, adding an annotation to each pod vs adding a profile with a label selector is the same amount of work, isn't it? With the benefit of having your config in 1 spot rather than scattered by annotations.

> we could add an override annotation to the API as a middle ground, where the user defines what the annotation is?

How is this different from using a label selector?

**Comment by grosser** [comment]
I think either approach works.
Annotations are nice because then the users don't need to know how exactly descheduler is configured and a descheduler change does not need to be synced with the users.
(for example "hey killing old pods now means 24h and not 48h")
The alternative would be to provide N different labels for "kill-in-30", "kill-in-60" etc.

**Comment by a7i** [comment]
>How is this different from using a label selector?

Label selector is for filtering, whereas the annotation is to define the age.

For example, the DeschedulerPolicy could have a global `maxPodLifeTimeSeconds: 86400 ` (or 1 day) but overriding it via an annotation would be:
```
metadata:
  annotations:
    descheduler.k8s.io/podlifetime: 3600 # 1 hour
```

**Comment by damemi** [comment]
From a usability standpoint though, if you are defining a custom annotation in the descheduler policy such as

```
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 86400
        podLifeTimeSecondsAnnotationOverride: "descheduler.k8s.io/podlifetime"
```

the definition of the age is in the descheduler config. You still need to apply that annotation to each pod

I'm asking, how is that different from a usability standpoint to just defining a new profile in the descheduler policy with a label selector such as

```
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 86400
        labelselector: app=foo
```

You still need to apply the label to each pod (instead of applying the annotation to each pod), unless the label already exists in which case it's fewer steps
