### ISSUE TITLE
Where should Policies go?

### ISSUE THREAD

**Issue by alifiroozi80** [kubernetes-sigs/descheduler#1131]
Hello guys,
I'm new to the Descheduler.

Based on the docs, I wrote this policy:

```yaml
apiVersion: descheduler/v1alpha2
kind: DeschedulerPolicy
profiles:
  - name: ProfileName
    pluginConfig:
    - name: "DefaultEvictor"
      args:
        evictFailedBarePods: true
        nodeFit: true
    - name: "RemoveFailedPods"
      args:
        reasons:
        - "NodeAffinity"
        includingInitContainers: true
        excludeOwnerKinds:
        - "Job"
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 3600
        states:
        - "Pending"
        - "PodInitializing"
        # namespaces:
        #   exclude:
        #   - "vault"
    - name: "RemovePodsHavingTooManyRestarts"
      args:
        podRestartThreshold: 20
        includingInitContainers: true
    - name: "RemovePodsViolatingTopologySpreadConstraint"
      args:
        includeSoftConstraints: false
    - name: "LowNodeUtilization"
      args:
        thresholds:
          "memory": 20
        targetThresholds:
          "memory": 80
    - name: "HighNodeUtilization"
      args:
        thresholds:
          "memory": 20
        evictableNamespaces:
          namespaces:
            exclude:
            - "kube-system"
            - "vault"
    plugins:
      evict:
        enabled:
          - "DefaultEvictor"
      balance:
        enabled:
          - "RemovePodsViolatingTopologySpreadConstraint"
          - "LowNodeUtilization"
          - "HighNodeUtilization"
      deschedule:
        enabled:
          - "RemoveFailedPods"
          - "PodLifeTime"
          - "RemovePodsHavingTooManyRestarts"
```

---

I installed the `descheduler` with Helm.

---

How can I apply this Policy to the `descheduler`?

It didn't create any `CRD`, and also I didn't see anything about this on the docs.

---

Should I add it here at the  [values](https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/values.yaml#L76)?

---

Maybe I should define it at the `values.yaml` like this?

```yaml
kind: Deployment

image:
  repository: mydomain-regisry/descheduler
  tag: "v0.26.1"

imagePullSecrets:
  - name: k8s-nexus

deschedulingInterval: 5m

replicas: 2
leaderElection: 
  enabled: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: "leases"
  resourceName: "descheduler"
  resourceNamescape: "kube-system"

deschedulerPolicyAPIVersion: "descheduler/v1alpha2"

deschedulerPolicy:
  profiles:
  - name: ProfileName
    pluginConfig:
    - name: "DefaultEvictor"
      args:
        evictFailedBarePods: true
        nodeFit: true
    - name: "RemoveFailedPods"
      args:
        reasons:
        - "NodeAffinity"
        includingInitContainers: true
        excludeOwnerKinds:
        - "Job"
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 3600
        states:
        - "Pending"
        - "PodInitializing"
        # namespaces:
        #   exclude:
        #   - "vault"
    - name: "RemovePodsHavingTooManyRestarts"
      args:
        podRestartThreshold: 20
        includingInitContainers: true
    - name: "RemovePodsViolatingTopologySpreadConstraint"
      args:
        includeSoftConstraints: false
    - name: "LowNodeUtilization"
      args:
        thresholds:
          "memory": 20
        targetThresholds:
          "memory": 80
    - name: "HighNodeUtilization"
      args:
        thresholds:
          "memory": 20
        evictableNamespaces:
          namespaces:
            exclude:
            - "kube-system"
            - "vault"
    plugins:
      evict:
        enabled:
          - "DefaultEvictor"
      balance:
        enabled:
          - "RemovePodsViolatingTopologySpreadConstraint"
          - "LowNodeUtilization"
          - "HighNodeUtilization"
      deschedule:
        enabled:
          - "RemoveFailedPods"
          - "PodLifeTime"
          - "RemovePodsHavingTooManyRestarts"
```
