### ISSUE TITLE
Pods are not getting evicted on "RemovePodsViolatingTopologySpreadConstraint"

### ISSUE THREAD

**Issue by JohnMops** [kubernetes-sigs/descheduler#1138]
**What version of descheduler are you using?**

descheduler version: 1.26

**Does this issue reproduce with the latest release?**
yes

**Which descheduler CLI options are you using?**
no CLI

**Please provide a copy of your descheduler policy config file**
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  RemovePodsViolatingTopologySpreadConstraint:
    enabled: true
    params:
      includeSoftConstraints: false
      namespaces:
        include:
        - assets
      nodeFit: false
```

**What k8s version are you using (`kubectl version`)?**
v1.24.10

**What did you do?**

1. Deployment has the following: 

```
topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: nginx
```

2. Also has nodeSelector and tolerations
3. GKE node autoprovisioner is used to scale new nodes according to node selector and tolerations
4. When the AZs are not balanced, descheduler throws: 

"ignoring pod for eviction as it does not fit on any other node" pod="assets/nginx-55b564d9d-77k8d"
even though nodeFit is set to "false"

**What did you expect to see?**
I expect the pod viloating the topology spread to be evicted , rescheduled and for node auto provisioner to pick it up and do its job

**What did you see instead?**
Pods remain untouched with the "ignoring pod for eviction as it does not fit on any other node" pod="assets/nginx-55b564d9d-77k8d" message in the descheduler pod logs.

**Comment by damemi** [comment]
Hi @JohnMops, this message comes from the strategy directly when it checks if the Pod would end up scheduled back onto the same node due to a hard node selector or affinity (see this comment in the code for some more details: https://github.com/kubernetes-sigs/descheduler/blob/eeafdb253a340f1d0fc4f272c304924a2b089e5b/pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go#L331-L335). It's independent of the nodeFit check since it's directly related to the strategy

Could you share the full Pod yaml? You mentioned it has a nodeSelector and tolerations so that might be the issue.

**Comment by JohnMops** [comment]
@damemi 

Thx for the reply. 

If this is the case then descheduler is not really right for us. 
I would expect for it to evict the pod anyway > pod goes back to scheduling pool > scheduler sees that the maxSkew on that specific zone is violated > new node spins up in a new AZ to balance the topology spread. 

We have a hardcoded nodeselector so that the node autoprovisioner will create a new node pool on the fly for each service we have. Kinda like an ASG in aws or a Karpenter provisioner. 

There is no way to use the descheduler to evict the pods that violate the constaint regardless of the node it currently using ?

**Comment by damemi** [comment]
@JohnMops thanks for explaining your use case, I think that actually could be a reasonable change for us to make. @a7i @knelasevero what do you think? Given the autoscaling use cases for descheduler I'm surprised we haven't hit this before

**Comment by JohnMops** [comment]
@damemi heya, any ETA on this by any chance?

**Comment by a7i** [comment]
Addressed in v0.28.0

**Comment by GraceAtwood** [comment]
@a7i That policy config doesn't seem to match the config format that's given in the helm chart on the `v0.28.0` release branch.  Does that need to get updated or am I reading this wrong?

**Comment by a7i** [comment]
the default policy is using v1alpha1 while above uses v1alpha2. I have a PR open to change it, hopefully that helps: https://github.com/kubernetes-sigs/descheduler/pull/1139

In summary, you should be able to do:

```
deschedulerPolicyAPIVersion: "descheduler/v1alpha2"
deschedulerPolicy:
  # maxNoOfPodsToEvictPerNamespace: 20  # summed through all strategies
  # maxNoOfPodsToEvictPerNode: 10       # summed through all strategies
  profiles:
    - name: fit # nodefit enabled plugins
      pluginConfig:
        - name: DefaultEvictor
          args:
            nodeFit: true # for ScheduleAnyway, you want to do a nodeFit check
        - name: RemovePodsViolatingTopologySpreadConstraint
          args:
            constraints:
            - ScheduleAnyway
      plugins:
        balance:
          enabled:
            - RemovePodsViolatingTopologySpreadConstraint

    - name: nofit # plugins without nodefit (e.g. force scale-up with cluster-autoscaler)
      pluginConfig:
        - name: "DefaultEvictor"
          args:
            nodeFit: false
        - name: RemovePodsViolatingTopologySpreadConstraint
          args:
            constraints:
            - DoNotSchedule
            topologyBalanceNodeFit: false
      plugins:
        balance:
          enabled:
            - RemovePodsViolatingTopologySpreadConstraint

   # workaround to disable v1alpha1 until https://github.com/kubernetes-sigs/descheduler/pull/1139 is merged
  strategies:
```
