### ISSUE TITLE
NodeFit Specification

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#1149]
**Is your feature request related to a problem? Please describe.**

Currently nodeFit is a boolean flag and the user has no control over which nodeFit checks should run or not.

**Describe the solution you'd like**

Full control over what nodeFit check is enabled or not

```
nodeFit:
  requests: false
  tolerateTaints: true
  affinity: true
  nodeSelector: true
  schedulable: true
```
  

**Describe alternatives you've considered**

Overwriting the Default Evictor

**What version of descheduler are you using?**

descheduler version: v0.27.0x

**Additional context**

**Comment by damemi** [comment]
Originally nodefit was planned to just eventually merge into the default state, we just made it an option because it was a change in how descheduler currently worked.

But seeing the options enumerated like this is really interesting. What if we just merged nodeFit into the default evictor or PreEvictionFilter? I think it has grown beyond what we originally envisioned and honestly I think it makes sense to expose each of these toggles

**Comment by a7i** [comment]
Adding @ingvagabund's proposal in this Issue:

At the same time someone might ask for disabling only specific checks. So instead of defining a bool argument I would like to suggest an enum.

```
topologyBalanceNodeFit:
- MatchSelector
- TaintsAndTolerations
- InsufficientResources
- SchedulableNodes
```

```
type NodeFitConditions string

var (
	MatchSelectorNodeFitConditions NodeFitConditions = "MatchSelector"
	TaintsAndTolerationsNodeFitConditions NodeFitConditions = "TaintsAndTolerations"
	InsufficientResourcesNodeFitConditions NodeFitConditions = "InsufficientResources"
	SchedulableNodesNodeFitConditions NodeFitConditions = "SchedulableNodes"
)

type RemovePodsViolatingTopologySpreadConstraintArgs struct {
	...
	TopologyBalanceNodeFit *[]NodeFitConditions `json:"topologyBalanceNodeFit,omitempty"`
}
```

Also on DefaultEvictor

**Comment by ingvagabund** [comment]
If there's a way I would like to avoid using pointers in the API definitions. Atm, `TopologyBalanceNodeFit == nil` means to use any reasonable defaults (that can change over time) vs. `*TopologyBalanceNodeFit == []NodeFitConditions` means do not use any node fit conditions, i.e. nodeFit feature disabled.

**Comment by a7i** [comment]
Is there a way to make this "future proof" in case we decide to pull in Scheduler's  Filter extension point?

**Comment by ingvagabund** [comment]
The goal is to definitely make it extendable. Unfortunately, I am out of time for the moment to help extend the design.

**Comment by ingvagabund** [comment]
To avoid using a pointer to a type:

```go
type NodeFitConditions string

var (
	NoCondition NodeFitConditions = ""
	MatchSelectorNodeFitConditions NodeFitConditions = "MatchSelector"
	TaintsAndTolerationsNodeFitConditions NodeFitConditions = "TaintsAndTolerations"
	InsufficientResourcesNodeFitConditions NodeFitConditions = "InsufficientResources"
	SchedulableNodesNodeFitConditions NodeFitConditions = "SchedulableNodes"
)

type RemovePodsViolatingTopologySpreadConstraintArgs struct {
	...
	TopologyBalanceNodeFit *[]NodeFitConditions `json:"topologyBalanceNodeFit,omitempty"`
}
```

```yaml
RemovePodsViolatingTopologySpreadConstraintArgs:
- TopologyBalanceNodeFit: [] // empty field -> fall back to defaults which is a subject to change
- TopologyBalanceNodeFit: [""] // empty string -> disable the node fit checks
- TopologyBalanceNodeFit: ["Cond1", ..., "CondN"] // arbitrary list of enabled conditions
```

Alternatively, `""` can be replaced with `"NoCheck"` or similar string which if specified will be the only valid item in the list.
