### ISSUE TITLE
Need support for adding multiple strategies of same type.

### ISSUE THREAD

**Issue by saranyareddy24** [kubernetes-sigs/descheduler#1154]
We have different set of pods in 2 different namespaces. We are using Pods with too many restarts strategy. Pod A should be evicted when there are more than 20 restarts, where as Pod B should we evicted even there is one restart.
```

 #STRATEGY_1
      "RemovePodsHavingTooManyRestarts":
        enabled:  true
        params:
          podsHavingTooManyRestarts:
            includingInitContainers:  false
            podRestartThreshold: 20
          namespaces:
            include:
            - NamespaceA
          nodefit : true
          thresholdPriorityClassName:  
      #STRATEGY_2
      "RemovePodsHavingRestarts":
        enabled: true
        params:
          podsHavingTooManyRestarts:
            includingInitContainers:  false
            podRestartThreshold: 1
          namespaces:
            - NamespaceB
          nodefit : false
          thresholdPriorityClassName:  
```
Is the above configuration supported? Are is there any alternative that can be done for these kind of scenarios.

**Comment by damemi** [comment]
You should be able to do this with descheduler profiles, though there is a bug in v0.27.0 that will be patched (https://github.com/kubernetes-sigs/descheduler/pull/1143)

**Comment by a7i** [comment]
This is available in v0.27.1

```
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
    - name: one
      pluginConfig:
        - name: DefaultEvictor
          args:
            nodeFit: true
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 20
            includingInitContainers: false
      plugins:
        deschedule:
          enabled:
          - RemovePodsHavingTooManyRestarts
    - name: two
      pluginConfig:
        - name: DefaultEvictor
          args:
            nodeFit: false
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 1
            includingInitContainers: false
      plugins:
        deschedule:
          enabled:
          - RemovePodsHavingTooManyRestarts
```
