### ISSUE TITLE
DefaultEvictor to support Delete verb

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#1170]
**Is your feature request related to a problem? Please describe.**

Consider a strategy such as pods with too many restarts, it is very likely that the PDB is already violated so eviction will not be able to evict as it would violate the budget.

```
app-server-6996cdf64f-7shnv                              0/2     Init:CrashLoopBackOff   150 (2m54s ago)   12h
app-server-7dd65cc5ff-5rkw6                              0/2     Init:CrashLoopBackOff   154 (3m32s ago)   12h
app-server-7dfdf8c678-2dd2x                              2/2     Running                            0                              12h
```

PDB:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
spec:
  maxUnavailable: 20%
  selector:
    matchLabels:
      app.kubernetes.io/name: app-server
```

**Describe the solution you'd like**

Ability to instruct DefaultEvictor to use delete instead of evict.

**Describe alternatives you've considered**

Custom plugin

**What version of descheduler are you using?**

descheduler version: v0.27.1

**Additional context**

```
    - name: "DefaultEvictor"
      args:
        verb: delete # default is evict
```
