### ISSUE TITLE
RemoveFailedPods does not evict with namespace filter

### ISSUE THREAD

**Issue by shadrus** [kubernetes-sigs/descheduler#1211]
**What version of descheduler are you using?**

descheduler version: 1.23
installed with Helm

**Which descheduler CLI options are you using?**
--policy-config-file /policy-dir/policy.yaml --descheduling-interval 5m --v 3

**Please provide a copy of your descheduler policy config file**
```yaml 
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  LowNodeUtilization:
    enabled: false
    params:
      nodeResourceUtilizationThresholds:
        targetThresholds:
          cpu: 50
          memory: 50
          pods: 50
        thresholds:
          cpu: 20
          memory: 20
          pods: 20
  PodLifeTime:
    enabled: false
    params:
      labelSelector:
        matchExpressions:
        - key: app
          operator: NotIn
          values:
          - runner-gitlab-runner
      namespaces:
        include:
        - gitlab-runner
      podLifeTime:
        maxPodLifeTimeSeconds: 3600
  RemoveDuplicates:
    enabled: false
  RemoveFailedPods:
    enabled: true
    params:
      failedPods:
        minPodLifetimeSeconds: 600
      namespaces:
        include:
        - prometheus-stack
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: false
  RemovePodsViolatingNodeAffinity:
    enabled: false
    params:
      nodeAffinityType:
      - requiredDuringSchedulingIgnoredDuringExecution
  RemovePodsViolatingNodeTaints:
    enabled: false
  RemovePodsViolatingTopologySpreadConstraint:
    enables: false
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

**What did you expect to see?**
I want to evict Failed pod in namespace prometheus-stack (other tried too, but without success). If I remove 
```yaml 
namespaces:
  include:
    - prometheus-stack
 ```
 descheduller starts to remove Failed pods in different namespaces.
I have failed pods in the namespace, for example

```yaml 
apiVersion: v1
kind: Pod
metadata:
  name: kube-prometheus-stack-grafana-95d649d9f-8sj5w
  generateName: kube-prometheus-stack-grafana-95d649d9f-
  namespace: prometheus-stack
  uid: c9e7d4e6-470c-40df-b289-3f057a5a8c76
  resourceVersion: '252120933'
  creationTimestamp: '2023-07-14T10:58:18Z'
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
    pod-template-hash: 95d649d9f
  annotations:
    checksum/config: b969da9b3953143b71818e6927e9156f7ebe285eab26b48585a0b809cf0d6337
    checksum/dashboards-json-config: 46d8c2427825506c44f20ec351a2c9e885fa640eb623af5739ad0952678343a6
    checksum/sc-dashboard-provider-config: a4a66942750fe8b712a2436de70143290681b641626761dc012f8d11908dc204
    checksum/secret: 4208d57b3ee9e1d3cd8eadb1a3f376a1cc6f2a24ff05f7e8f710c5610a507e4d
    container.seccomp.security.alpha.kubernetes.io/grafana: runtime/default
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: kube-prometheus-stack-grafana-95d649d9f
      uid: fd096858-3077-41c6-99b4-41746e2551fd
      controller: true
      blockOwnerDeletion: true  
status:
  phase: Failed
```

**What did you see instead?**
I0801 09:50:23.361815       1 node.go:46] "Node lister returned empty list, now fetch directly"
I0801 09:50:23.500358       1 descheduler.go:263] Building a pod evictor
I0801 09:50:23.500448       1 failedpods.go:70] "Processing node" node="cl178ik1oqk8is4rdu7t-icyb"
I0801 09:50:23.500475       1 failedpods.go:70] "Processing node" node="cl178ik1oqk8is4rdu7t-ozam"
I0801 09:50:23.500496       1 failedpods.go:70] "Processing node" node="cl1gpsicpu5tcjjtsk2o-ojir"
I0801 09:50:23.500510       1 failedpods.go:70] "Processing node" node="cl1gpsicpu5tcjjtsk2o-yrec"
I0801 09:50:23.500524       1 failedpods.go:70] "Processing node" node="cl1jtkelbmhrnngq0ol5-aloz"
I0801 09:50:23.500662       1 failedpods.go:70] "Processing node" node="cl1jtkelbmhrnngq0ol5-obir"
I0801 09:50:23.500679       1 failedpods.go:70] "Processing node" node="cl1jtkelbmhrnngq0ol5-olyp"
I0801 09:50:23.500770       1 failedpods.go:70] "Processing node" node="cl1jtkelbmhrnngq0ol5-ukal"
I0801 09:50:23.500814       1 failedpods.go:70] "Processing node" node="cl1jtkelbmhrnngq0ol5-ukon"
I0801 09:50:23.500934       1 failedpods.go:70] "Processing node" node="cl1tn0qp40a8mruafofh-asuz"
I0801 09:50:23.500961       1 failedpods.go:70] "Processing node" node="cl1tn0qp40a8mruafofh-azeb"
I0801 09:50:23.500978       1 failedpods.go:70] "Processing node" node="cl1tn0qp40a8mruafofh-esor"
I0801 09:50:23.500993       1 failedpods.go:70] "Processing node" node="cl1tn0qp40a8mruafofh-itut"
I0801 09:50:23.501006       1 failedpods.go:70] "Processing node" node="cl1tn0qp40a8mruafofh-ovas"
I0801 09:50:23.501023       1 failedpods.go:70] "Processing node" node="cl1tn0qp40a8mruafofh-uqud"
I0801 09:50:23.501038       1 failedpods.go:70] "Processing node" node="cl1tn0qp40a8mruafofh-usun"
I0801 09:50:23.501056       1 failedpods.go:70] "Processing node" node="cl1tn0qp40a8mruafofh-yzyp"
I0801 09:50:23.501079       1 descheduler.go:288] "Number of evicted pods" totalEvicted=0
