### ISSUE TITLE
nodeFit doesn't handle preferredDuringSchedulingIgnoredDuringExecution (RemovePodsViolatingNodeAffinity)

### ISSUE THREAD

**Issue by antoinedeschenes** [kubernetes-sigs/descheduler#1236]
There should be a way for nodeFit filtering to check for `preferredDuringSchedulingIgnoredDuringExecution` nodeAffinity terms
https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/utils/predicates.go#L48

**What version of descheduler are you using?**

descheduler version: 0.28.0

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
```
      --policy-config-file=/policy-dir/policy.yaml
      --descheduling-interval=1h
      --dry-run=true
      --v=-1
      --vmodule=evictions=1,profile=1
```

**Please provide a copy of your descheduler policy config file**
```yaml
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
    - name: MigrateSpotNodeAffinity
      pluginConfig:
      - args:
          evictLocalStoragePods: true
          nodeFit: true
        name: DefaultEvictor
      - args:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
          - preferredDuringSchedulingIgnoredDuringExecution
        name: RemovePodsViolatingNodeAffinity
      plugins:
        deschedule:
          enabled:
          - RemovePodsViolatingNodeAffinity
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.12", GitCommit:"ba490f01df1945d0567348b271c79a2aece7f623", GitTreeState:"clean", BuildDate:"2023-07-19T12:23:43Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.10-gke.2700", GitCommit:"df2448d7739c44e41ee999b9065ce506cab86344", GitTreeState:"clean", BuildDate:"2023-06-22T09:25:37Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

- Setup descheduler deployment using `RemovePodsViolatingNodeAffinity` rule with nodeAffinityType `preferredDuringSchedulingIgnoredDuringExecution`
- Setup a deployment with a `preferredDuringSchedulingIgnoredDuringExecution` nodeAffinity rule matching no cluster nodes
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: does-not-exist-on-a-node
                operator: Exists
            weight: 100
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

```

**What did you expect to see?**
No pods being evicted as `nodeFit` is enabled
 
**What did you see instead?**
Pods not matching their `preferredDuringSchedulingIgnoredDuringExecution` nodeAffinity rules are evicted, while no nodes actually fit the `preferred` requirements.
