### ISSUE TITLE
The getTargetNodes in RemoveDuplicates does not respect node resources and can mistakenly evict pods

### ISSUE THREAD

**Issue by bingzheliu** [kubernetes-sigs/descheduler#1237]
### descheduler version
0.27.1
### k8s version
v1.28.0
### Problem
The RemoveDuplicate plugin is supposed to get the feasible nodes that can place the duplicatePods before calculating which pods to delete. In particular, [this line](https://github.com/kubernetes-sigs/descheduler/blob/e8427d0eb44843aab7722a9bf18e9db119fd4202/pkg/framework/plugins/removeduplicates/removeduplicates.go#L192) of code. 

However, it currently only checks on the tolerance/taint and nodeSelector (code [here)](https://github.com/kubernetes-sigs/descheduler/blob/e8427d0eb44843aab7722a9bf18e9db119fd4202/pkg/framework/plugins/removeduplicates/removeduplicates.go#L251). The node can be infeasible to the pod due to other reasons, i.e., the node does not have enough resources for more pods. 

This issue can cause more pods to be mistakenly evicted if nodes can't hold the pods due to limited resources. And unending cycle of scheduling and eviction can occur.

### What is expected
The getTargetNodes should consider the node resource fits and other scheduling restrictions of the pods (like NodePorts).

**Comment by a7i** [comment]
@bingzheliu `nodeFit` by default is `false` so you may want to enable that.

If you are using `descheduler/v1alpha2`, the docs can be found [here](https://github.com/kubernetes-sigs/descheduler/tree/master#evictor-plugin-configuration-default-evictor) to configure the `DefaultEvictor`.
```
profiles:
  - name: ProfileName
    pluginConfig:
    - name: "DefaultEvictor"
      args:
        nodeFit: true
```


If you are using `descheduler/v1alpha`, the docs can be found [here](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/deprecated/v1alpha1.md#removeduplicates)
```
  RemoveDuplicates:
     enabled: true
     params:
       removeDuplicates:
         nodeFit: true
```
