### ISSUE TITLE
Confusing Helm usage

### ISSUE THREAD

**Issue by danielepolencic** [kubernetes-sigs/descheduler#1252]
I'm using the Helm Chart: 0.28.0

The project doesn't make it easy to understand how to submit policy to the scheduler.
Initially, I thought the policies were CRDs, but after stumbling over a few issues in this repo, I realized they are just YAML files stored in a ConfigMap. Yet, the quickstart guide or the examples don't mention this.

So the next question was, how do I update those policies after I deploy the Descheduler?
The ConfigMap, of course.
So I had a look at the `Values.yaml` and figured out that I could manually set all the values in the `deschedulerPolicy`. Great. But I have policies as files, and I'd prefer not to use several `--set` to configure those.

So, I tried the following:

```bash
helm upgrade descheduler descheduler/descheduler -n kube-system \
  --set deschedulerPolicy="$(cat 03-demo/02-restart.yaml)"
```

Unfortunately, the current template doesn't account for that. Every time the template is rendered, I can see the following:

```yaml
apiVersion: v1
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    |- # <--this
      # apiVersion: "descheduler/v1alpha2"
      # kind: "DeschedulerPolicy"
      profiles:
        - name: ProfileName
          pluginConfig:
            - name: "PodLifeTime"
              args:
                maxPodLifeTimeSeconds: 10 # in seconds
          plugins:
            deschedule:
              enabled:
                - "PodLifeTime"
kind: ConfigMap
```

 A quick googling suggested that the `|-` is injected by the `toYaml` helper in Helm.
So I guess the only ways to use this Helm chart is to:

- Manually set the value one by one.
- Overwrite the ConfigMap manually (and forget about Helm)
- Use some sort of Helm + Kustomize combination.

Let me know if I missed the obvious, I'm still fairly new with the new project.

**Comment by a7i** [comment]
Hi @danielepolencic thanks for the feedback, we can work on enhancing the docs to make this clear.

`deschedulerPolicy` is a map and not a string so you can overwrite the existing values or pass in a values file:

```
helm upgrade descheduler descheduler/descheduler -n kube-system \
  -f 03-demo/02-restart.yaml
```

where `03-demo/02-restart.yaml` is:

```
deschedulerPolicyAPIVersion: "descheduler/v1alpha1"

deschedulerPolicy:
  profiles:
    - name: ProfileName
      pluginConfig:
        - name: "PodLifeTime"
          args:
            maxPodLifeTimeSeconds: 10 # in seconds
      plugins:
        deschedule:
          enabled:
            - "PodLifeTime"
```
