### ISSUE TITLE
configmap cannot be hot updated

### ISSUE THREAD

**Issue by openstack-test** [kubernetes-sigs/descheduler#1258]
**What version of descheduler are you using?**

descheduler version:  0.28.0

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
```
git clone  https://github.com/kubernetes-sigs/descheduler.git
cd descheduler/
kubectl create -f kubernetes/base/rbac.yaml
kubectl create -f kubernetes/base/configmap.yaml
kubectl create -f kubernetes/deployment/deployment.yaml
```
**Please provide a copy of your descheduler policy config file**
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "RemovePodsViolatingNodeTaints"
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu" : 30
              "memory": 30
            targetThresholds:
              "cpu" : 70
              "memory": 70
        plugins:
          balance:
            enabled:
              - "LowNodeUtilization"
          deschedule:
            enabled:
              - "RemovePodsViolatingNodeTaints"
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.16-eks-2d98532", GitCommit:"af930c12e26ef9d1e8fac7e3532ff4bcc1b2b509", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:47Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**
Update and apply configmap as described above

**What did you expect to see?**
configmap can be hot updated, and the descheduler pod takes effect with the new policy configuration

**What did you see instead?**
It doesn't actually take effect and you need to restart the descheduler pod manually
