### ISSUE TITLE
Pods strategies doesn't work

### ISSUE THREAD

**Issue by y0zg** [kubernetes-sigs/descheduler#1341]
descheduler version: v0.27.1
helm chart version: 0.27.1

**Does this issue reproduce with the latest release?**
Haven't tested

**Which descheduler CLI options are you using?**
```
    Command:
      /bin/descheduler
    Args:
      --policy-config-file
      /policy-dir/policy.yaml
      --v
      3
```

**Please provide a copy of your descheduler policy config file**

helm values file
```
cronJobApiVersion: "batch/v1"  # Use "batch/v1beta1" for k8s version < 1.21.0. TODO(@7i) remove with 1.23 release
schedule: "0 9 * * 1-4"
suspend: false

deschedulerPolicy:
  profiles:
  - name: ProfileName
    pluginConfig:
    - name: "DefaultEvictor"
      args:
        evictFailedBarePods: true
        nodeFit: true
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 3600
        states:
        - "ContainerStatusUnknown"
        - "Completed"
        - "Error"
        - "Evicted"
    - name: "RemoveFailedPods"
      args:
        # evictableNamespaces:
        #   exclude:
        #   - "kube-system"
        #   - "jenkins"
        reasons:
        # - "OutOfcpu"
        - "CreateContainerConfigError"
        - "Error"
        - "Completed"
        - "Evicted"
        - "ContainerStatusUnknown"
        # excludeOwnerKinds:
        # - "Job"
        minPodLifetimeSeconds: 3600
    plugins:
      deschedule:
        enabled:
          - "RemoveFailedPods"
          - "PodLifeTime"
  # nodeSelector: "key1=value1,key2=value2"
  # maxNoOfPodsToEvictPerNode: 10
  # maxNoOfPodsToEvictPerNamespace: 10
  ignorePvcPods: true
  # evictLocalStoragePods: true
  strategies:
    RemoveFailedPods:
      enabled: true
      params:
        failedPods:
          reasons:
          - "Failed"
          # - "Succeeded"
    LowNodeUtilization:
      enabled: false
    HighNodeUtilization:
      enabled: true
      params:
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 20
            memory: 20
        namespaces:
          exclude:
          - "kube-system"
          - "jenkins"
          - "logs"




serviceMonitor:
  enabled: false
  # The namespace where Prometheus expects to find service monitors.
  # namespace: ""
  interval: ""
  # honorLabels: true
  insecureSkipVerify: true
  serverName: null
  metricRelabelings: []
    # - action: keep
    #   regex: 'descheduler_(build_info|pods_evicted)'
    #   sourceLabels: [__name__]
  relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace
```

**What k8s version are you using (`kubectl version`)?**

k8s version: v1.27.8-eks-8cb36c9

I don't see that descheduler removes pods with status `Error`, `ContainerStatusUnknown`, `Completed`

**Comment by damemi** [comment]
Hi @y0zg, are you seeing descheduler remove pods with other status codes besides `Error`, `ContainerStatusUnknown`, and `Completed`? And are the pods with these statuses at least 3600 seconds old as your `minPodLifetimeSeconds`

@knelasevero @a7i @ingvagabund I don't remember exactly how we check pod eviction reasons/statuses. Did we have any updated docs on what exactly is covered?

**Comment by y0zg** [comment]
The problem that I don't see that descheduler removes pods at all. I tried to set lifetime to 60sec with frequent cronjob run.

One more interesting fact , in log I see this warning while running 0.27 version on 1.27 k8s version
```
W0118 16:51:01.043860       1 descheduler.go:127] Warning: Descheduler minor version 27 is not supported on your version of Kubernetes 1.27+. See compatibility docs for more info: https://github.com/kubernetes-sigs/descheduler#compatibility-matrix
```

I tried to use descheduler 0.28 version and with it above compatibility isn't present

**Comment by a7i** [comment]
The warning message about compatibility was addressed [here](https://github.com/kubernetes-sigs/descheduler/pull/1249/commits/dca2e58b8e705ad60b3c060f541e9d0a43238fe0) which landed in v0.28.1 and v0.29.0 but not v0.27.x

As far as your second question, `RemoveFailedPods` only looks at pod phase reason, and not container status. For example `CreateContainerConfigError` is not a Pod Phase, but rather a Container Status.

Additionally, reason `Completed` will not work with `RemoveFailedPods` because this strategy only looks at pods in `Failed` phase. Pod phase for `Completed` is always `Succeeded`.

All of that to say that you may want to use `PodLifeTime` instead since it checks both pod status reasons and container status reasons ([ref](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/framework/plugins/podlifetime/pod_lifetime.go#L89)).

Question for maintainers - we should either merge the two strategies and formally retire `RemoveFailedPods` or be consistent in the reasons that we check (check pod status and container status in both strategies).

**Comment by ingvagabund** [comment]
> Question for maintainers - we should either merge the two strategies and formally retire RemoveFailedPods

Similar request for merging strategies is in https://github.com/kubernetes-sigs/descheduler/issues/1169. Worth extending it with `RemoveFailedPods` for further analysis and discussion.

**Comment by y0zg** [comment]
Since I shared the config (for sure it might contain incorrect settings as I was testing various options), can you check what should be corrected in order to delete "failed" pods, i.e. pods with status: `Error`

Much appreciate!

**Comment by blmhemu** [comment]
Descheduler does not delete failed pods.

```
    deschedulerPolicy:
      profiles:
        - name: default
          pluginConfig:
            - name: RemoveFailedPods
          plugins:
            deschedule:
              enabled:
                - RemoveFailedPods
```

Pod status below:

```
--- snip ---

status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-03-07T06:44:09Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-03-07T06:44:09Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-03-07T06:44:09Z"
    reason: PodFailed
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-03-07T06:44:09Z"
    reason: PodFailed
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-03-07T06:44:09Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: quay.io/cilium/operator-generic:v1.16.6@sha256:13d32071d5a52c069fb7c35959a56009c6914439adc73e99e098917646d154fc
    imageID: ""
    lastState: {}
    name: cilium-operator
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        exitCode: 137
        finishedAt: null
        message: The container could not be located when the pod was terminated
        reason: ContainerStatusUnknown
        startedAt: null
    volumeMounts:
    - mountPath: /tmp/cilium/config-map
      name: cilium-config-path
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-psglh
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.4.102
  hostIPs:
  - ip: 192.168.4.102
  message: 'Pod was rejected: Pod was rejected as the node is shutting down.'
  phase: Failed
  podIP: 192.168.4.102
  podIPs:
  - ip: 192.168.4.102
  qosClass: BestEffort
  reason: NodeShutdown
  startTime: "2025-03-06T22:02:39Z"

```
