### ISSUE TITLE
Strategy RemovePodsViolatingNodeAffinity does not remove pod when affinity disappears

### ISSUE THREAD

**Issue by bprieur** [kubernetes-sigs/descheduler#1345]
**What version of descheduler are you using?**

descheduler version: v0.29.0

**Does this issue reproduce with the latest release?**

Yes.

**Which descheduler CLI options are you using?**

Defaults from chart helm release.

**Please provide a copy of your descheduler policy config file**

From chart helm release, enable only `RemovePodsViolatingNodeAffinity`.

<details>
<summary>Values applies with helm installation.</summary>

```yaml
deschedulerPolicy:
  strategies:
    RemoveDuplicates:
      enabled: false
    RemovePodsHavingTooManyRestarts:
      enabled: false
    RemovePodsViolatingNodeTaints:
      enabled: false
    RemovePodsViolatingNodeAffinity:
      enabled: true
      params:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
        - preferredDuringSchedulingIgnoredDuringExecution
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: false
    RemovePodsViolatingTopologySpreadConstraint:
      enabled: false
    LowNodeUtilization:
      enabled: false
```

</details>

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5+k3s1
</pre></details>

**What did you do?**

<details>
<summary>Create a Deployment.</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
```

</details>

<details open>
<summary>Labeled one node in the cluster</summary>

`kubectl label nodes <node> disktype=ssd`

</details>

<details open>
<summary>Unlabeled the node</summary>

`kubectl label nodes <node> disktype-`

</details>

**What did you expect to see?**

Node are in pending status because any node in the cluster fit the affinity.

**What did you see instead?**

Pods are in running status. 

With verbosity 4, descheduler log is `node.go:166] "Pod does not fit on node" pod:="default/nginx-deployment-56f548b646-jmcqv" node:="pi-101" error:="pod node selector does not match the node label"` for each node.

The strategy `RemovePodsHavingTooManyRestarts` deletes pods when the parameter `podRestartThreshold` is reached.

Maybe this kind of scenario isn't covered by the "RemovePodsViolatingNodeAffinity" strategy, or maybe it's deliberate?
