### ISSUE TITLE
unknown phase feature

### ISSUE THREAD

**Issue by BiancaTofan** [kubernetes-sigs/descheduler#1417]
Hello , 

I am using the latest version for descheduler chart and I am trying to define a descheduler policy in order to evict pods which are in an unknown state, but it seems that nothing happens even if there are already 2 pods with this status which are running for more than 86400 seconds. Is it there a problem or my policy isn't defined correctly? 

```
apiVersion: v1
data:
  values.yaml: |
    ---
    cmdOptions:
      v: 7
    deschedulerPolicy:
      profiles:
        - name: ProfileName
          pluginConfig:
            - args:
                evictDaemonSetPods: true
                evictLocalStoragePods: true
                evictFailedBarePods: true
              name: "DefaultEvictor"
            - args:
                nodeAffinityType:
                - "requiredDuringSchedulingIgnoredDuringExecution"
              name: "RemovePodsViolatingNodeAffinity"
            - args:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: kured
                maxPodLifeTimeSeconds: 86400
                namespaces:
                  include:
                  - "kubernetes-reboot-daemon"
                states:
                - "Unknown"
                - "Pending"
              name: "PodLifeTime"
          plugins:
            deschedule:
              enabled:
                - "PodLifeTime"
                - "RemovePodsViolatingNodeAffinity"
      strategies: null
    deschedulerPolicyAPIVersion: "descheduler/v1alpha2"
    deschedulingInterval: 5m
    image:
      pullPolicy: Always
    kind: Deployment
    resources:
      limits:
        ephemeral-storage: 100Mi
        memory: 127Mi
      requests:
        cpu: 50m
        ephemeral-storage: 100Mi
        memory: 127Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001

```
Thank you in advance!
