### ISSUE TITLE
otel: conflicting Schema URL

### ISSUE THREAD

**Issue by morremeyer** [kubernetes-sigs/descheduler#1428]
**What version of descheduler are you using?**

descheduler version: v0.31.0
helm chart version: 0.30.0

**Does this issue reproduce with the latest release?**

Yes

**Which descheduler CLI options are you using?**

```
--policy-config-file=/policy-dir/policy.yaml
--logging-format=json
--otel-collector-endpoint=monitoring-alloy.monitoring.svc.cluster.local:4317
--otel-sample-rate=1
--v=3

**Please provide a copy of your descheduler policy config file**

```yaml
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
- name: RemovePodsHavingTooManyRestarts
  pluginConfig:
  - args:
      includingInitContainers: true
      podRestartThreshold: 50
    name: RemovePodsHavingTooManyRestarts
    plugins:
      deschedule:
        enabled:
        - RemovePodsHavingTooManyRestarts
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
</pre></details>

**What did you do?**

Deploy descheduler with the helm chart in version 0.30.0 with the following `values.yaml`:

```yaml
image:
  repository: registry.k8s.io/descheduler/descheduler
  tag: v0.30.1

fullnameOverride: descheduler

cmdOptions:
  logging-format: json

  otel-sample-rate: 1.0
  otel-collector-endpoint: monitoring-alloy.monitoring.svc.cluster.local:4317

deschedulerPolicy:
  ## Setting the config here does not do anything, setting it in cmdOptions above
  # tracing:
  #   collectorEndpoint: monitoring-alloy.monitoring.svc.cluster.local:4317
  #   sampleRate: 1.0

  profiles:
    - name: RemovePodsHavingTooManyRestarts
      pluginConfig:
        - name: "RemovePodsHavingTooManyRestarts"
          args:
            podRestartThreshold: 50
            includingInitContainers: true
          plugins:
            deschedule:
              enabled:
                - "RemovePodsHavingTooManyRestarts"
```

**What did you expect to see?**

Descheduler running with the policy specified

**What did you see instead?**

Descheduler exits with an error

> conflicting Schema URL: https://opentelemetry.io/schemas/1.12.0 and https://opentelemetry.io/schemas/1.24.0

<details>
<summary>Full log</summary>

```
{"ts":1717675604781.581,"caller":"server/secure_serving.go:57","msg":"Forcing use of http/1.1 only","v":0}
{"ts":1717675604782.072,"caller":"dynamiccertificates/named_certificates.go:53","msg":"Loaded SNI cert","v":2,"index":0,"certName":"self-signed loopback","certDetail":"\"apiserver-loopback-client@1717675604\" [serving] validServingFor=[apiserver-loopback-client] issuer=\"apiserver-loopback-client-ca@1717675604\" (2024-06-06 11:06:44 +0000 UTC to 2025-06-06 11:06:44 +0000 UTC (now=2024-06-06 12:06:44.782019599 +0000 UTC))"}
{"ts":1717675604782.1294,"caller":"server/secure_serving.go:213","msg":"Serving securely on [::]:10258","v":0}
{"ts":1717675604782.1575,"caller":"tracing/tracing.go:109","msg":"Enabling trace GRPC client in insecure mode","v":0}
{"ts":1717675604782.2544,"caller":"dynamiccertificates/tlsconfig.go:240","msg":"Starting DynamicServingCertificateController","v":0}
{"ts":1717675604782.679,"caller":"tracing/tracing.go:130","msg":"failed to create traceable resource","err":"2 errors occurred detecting resource:\n\t* conflicting Schema URL: https://opentelemetry.io/schemas/1.12.0 and https://opentelemetry.io/schemas/1.24.0\n\t* user: Current requires cgo or $USER set in environment"}
{"ts":1717675604782.7117,"caller":"app/server.go:96","msg":"descheduler server","err":"2 errors occurred detecting resource:\n\t* conflicting Schema URL: https://opentelemetry.io/schemas/1.12.0 and https://opentelemetry.io/schemas/1.24.0\n\t* user: Current requires cgo or $USER set in environment"}
{"ts":1717675604782.729,"caller":"cli/run.go:74","msg":"command failed","err":"2 errors occurred detecting resource:\n\t* conflicting Schema URL: https://opentelemetry.io/schemas/1.12.0 and https://opentelemetry.io/schemas/1.24.0\n\t* user: Current requires cgo or $USER set in environment"}
```

</details>
