### ISSUE TITLE
Unable to create a profile" err="unable to build DefaultEvictor plugin

### ISSUE THREAD

**Issue by timetofaceit** [kubernetes-sigs/descheduler#1440]
Hi!

I'm facing an error in Descheduler pod logs:

```
"unable to create a profile" err="unable to build DefaultEvictor plugin: unable to initialize \"DefaultEvictor\" plugin: indexer conflict: map[metadata.ownerReferences:{}]" profile="Descheduler"
```

I'm installing Descheduler via Helm Chart v0.30.1 with Deployment mode.

My policy config looks like this:
```
deschedulerPolicy:
  profiles:
    - name: "Descheduler"
      pluginConfig:
        - name: "DefaultEvictor"
          args:
            evictLocalStoragePods: false
            evictSystemCriticalPods: false
            ignorePvcPods: false
            evictFailedBarePods: false
            nodeFit: true
            minReplicas: 2
        - name: "RemoveDuplicates"
        - name: "LowNodeUtilization"
          args:
            thresholds:
              cpu : 30
              memory: 30
              pods: 20
            targetThresholds:
              cpu : 80
              memory: 80
              pods: 50
        - name: "HighNodeUtilization"
          args:
            thresholds:
              cpu : 80
              memory: 80
              pods: 50
        - name: "RemovePodsViolatingInterPodAntiAffinity"
        - name: "RemovePodsViolatingNodeTaints"
        - name: "RemovePodsViolatingNodeAffinity"
          args:
            nodeAffinityType:
              - "requiredDuringSchedulingIgnoredDuringExecution"
        - name: "RemovePodsViolatingTopologySpreadConstraint"
          args:
            topologyBalanceNodeFit: true
            constraints:
              - "DoNotSchedule"
              - "ScheduleAnyway"
      plugins:
        balance:
          enabled:
            - "RemoveDuplicates"
            - "LowNodeUtilization"
            - "HighNodeUtilization"
            - "RemovePodsViolatingTopologySpreadConstraint"
        deschedule:
          enabled:
            - "RemovePodsViolatingInterPodAntiAffinity"
            - "RemovePodsViolatingNodeAffinity"
            - "RemovePodsViolatingNodeTaints"
```

I also see that when pod starts, everything works fine until CronJob finishes... Then I'm starting to get these errors...

Maybe I'm configuring something wrong? 🤔
