### ISSUE TITLE
Replace namespace include/exclude filter with label selector

### ISSUE THREAD

**Issue by nabokihms** [kubernetes-sigs/descheduler#1499]
**Is your feature request related to a problem? Please describe.**
I have productive and test namespaces labeled accordingly (env: prod, env: test). I'd like to deschedule pods based on these labels. As of today, every time engineers create new namespace, it is required to go and change the rescheduled config as well.

This problem affects the ability to provide self-service for my teams.

**Describe the solution you'd like**
I'd like to see `namespaces.labelSelector` option which can filter namespaces based on labels. This is more flexible in all terms.

Including and excluding namespaces by names (as it works now) can also be implemented using this option (so we no longer need include/exclude at all), e.g., 
```
namespaces:
  include:
  - ns-a
  - ns-b
  - ns-c
```
equals to

```
labelSelector:
  matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: [ns-a, ns-b, ns-c]
```

**Describe alternatives you've considered**

--

**What version of descheduler are you using?**

descheduler version: latest

**Additional context**

**Comment by damemi** [comment]
+1 this is honestly how we probably should have done it. @ingvagabund @knelasevero do you know any reason why we did the include/exclude pattern instead of just label selectors?

**Comment by ingvagabund** [comment]
We can not guarantee mutual exclusion of included and excluded namespaces with the whole expressiveness of `labelSelector`. If there's an non-empty intersection of the namespaces should we ignore the shared namespaces? Should we be more restrictive and ignore the shared included namespaces?

**Comment by nabokihms** [comment]
@ingvagabund thanks for your answer, but it is puzzling. Are you saying that the feature will not be accepted because it is not a simple feature? 

What is with the use case then? What can you suggest go solve the issue?

**Comment by damemi** [comment]
@ingvagabund if we get rid of the `include` and `exclude` fields and make it one label selector (ie, where people can set `IN` or `NOT IN` themselves) then I don't think there's any issue with conflicting includes/excludes. It just becomes label selector semantics

**Comment by ingvagabund** [comment]
What you are saying makes sense. Still trying to recall why we decided to use combination of included/excluded namespaces. I can think of performance reasons. If we allow combination of `IN` and `NOT IN` it might be time expensive to compute the final set of matched namespaces. With a list of only included or (exclusive or) only excluded namespaces it's fast to get a list of matched namespaces. If we allow combination of both the computation might get expensive. E.g. 
```
labelSelector:
  matchExpressions:
    - key: labelKey1
      operator: In
      values: [labelValue1]
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: [ns-10000, ns-9999, ns-9998]
```
When the first expression matches most of the 10000 namespaces it might take a while to enumerate the list. Given each strategy/plugin will iterate through the list (some might do it repeatedly within a single run) this might have a significant impact on the overall performance (many ifs). We have not made any performance measurements in big clusters (or clusters with many many namespaces) so it's all theoretical here.
