### ISSUE TITLE
No removable pods on node，why?

### ISSUE THREAD

**Issue by hwyrq** [kubernetes-sigs/descheduler#1516]
I0912 09:17:02.750207       1 nodeutilization.go:204] "Node is underutilized" node="home0123" usage={"cpu":"600m","memory":"306Mi","pods":"4"} usagePercentage={"cpu":0.75,"memory":0.33,"pods":3.64}                             
│ I0912 09:17:02.750371       1 nodeutilization.go:207] "Node is overutilized" node="cloud0406" usage={"cpu":"950m","memory":"290Mi","pods":"15"} usagePercentage={"cpu":47.5,"memory":17.32,"pods":13.64}                          
│ I0912 09:17:02.750414       1 nodeutilization.go:204] "Node is underutilized" node="home0122" usage={"cpu":"200m","memory":"250Mi","pods":"10"} usagePercentage={"cpu":3.33,"memory":1.62,"pods":9.09}                            
│ I0912 09:17:02.750448       1 lownodeutilization.go:135] "Criteria for a node under utilization" CPU=100 Mem=5 Pods=100                                                                                                           
│ I0912 09:17:02.750483       1 lownodeutilization.go:136] "Number of underutilized nodes" totalNumber=2                                                                                                                            
│ I0912 09:17:02.750506       1 lownodeutilization.go:149] "Criteria for a node above target utilization" CPU=100 Mem=10 Pods=100                                                                                                   
│ I0912 09:17:02.750539       1 lownodeutilization.go:150] "Number of overutilized nodes" totalNumber=1                                                                                                                             
│ I0912 09:17:02.750567       1 nodeutilization.go:261] "Total capacity to be moved" CPU=85200 Mem=10678022143 Pods=206                                                                                                             
│ I0912 09:17:02.750655       1 nodeutilization.go:264] "Evicting pods from node" node="cloud0406" usage={"cpu":"950m","memory":"290Mi","pods":"15"}                                                                                
│ I0912 09:17:02.750978       1 nodeutilization.go:267] "Pods on node" node="cloud0406" allPods=15 nonRemovablePods=15 removablePods=0                                                                                              
│ I0912 09:17:02.751021       1 nodeutilization.go:270] "No removable pods on node, try next node" node="cloud0406"                                                                                                                 
│ I0912 09:17:02.751082       1 profile.go:349] "Total number of pods evicted" extension point="Balance" evictedPods=0

**Comment by hwyrq** [comment]
I learned the go , looked at the source code, and Add a annotations here
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wccloud-web-rust
  name: wccloud-web-rust
spec:
  replicas: 10
  selector:
    matchLabels:
      app: wccloud-web-rust
  template:
    metadata:
      annotations:
        "descheduler.alpha.kubernetes.io/evict": "1"
      labels:
        app: wccloud-web-rust
    spec:
      containers:
        - name: wccloud-web-rust
```
Now there is a new problem，After the pod was expelled, it was deployed again on the original node
