### ISSUE TITLE
Respond to nodeConditions changes

### ISSUE THREAD

**Issue by nogazax** [kubernetes-sigs/descheduler#1518]
**Is your feature request related to a problem? Please describe.**
When using nodeProblemDetector (NPD), there is a gap where NPD marks nodes using nodeCondition, and Descheduler (DSC) is watching taints.

**Describe the solution you'd like**
I want to fill this gap with a controller, which is alerted on nodeCondition changes.
Controller reads condition, if it matches a some criteria (implementation + restrictions TBD) it taints the node\deschedules the pods (customable taint\simply cordon TBD).

After tainting, DSC starts removing the pods from these nodes, and clusterAutoScaler will remove the node when underutilized.

**Describe alternatives you've considered**
non controller application - IMO, in this use case it's better subscribing to events rather than polling api server for them.
using forked version of [Draino project ](https://github.com/planetlabs/draino) - as an unmaintained project, with multiple security vulnerabilities, not the favorite option
add this functionality to NPD - [stale PR for a long time](https://github.com/kubernetes/node-problem-detector/pull/565)

**What version of descheduler are you using?**

descheduler version:
V0.30.0

**Additional context**
I wrote a small POC.
NPD marks condition -> my controller recognized it and added taint to node -> DSC acts on pods without toleration

**Comment by a7i** [comment]
Would you be able to use the existing [RemovePodsViolatingNodeTaints](https://github.com/kubernetes-sigs/descheduler#removepodsviolatingnodetaints)?

**Comment by nogazax** [comment]
I think so, but not sure if this is the right place to add it:
1. if yes, should it be renamed to RemovePodsViolatingNodeTaints*AndConditions*?
2. another option is to create another plugin RemovePodsViolatingNodeCondition. reducing complexity, adds functionality, but kinda duplicates the business logic
3. last option is to add a small component which taints nodes based on conditions, and letting current controller do it's job.

WDYT?

**Comment by googs1025** [comment]
Maybe `RemovePodsViolatingCustomNodeConditions` is more appropriate. 🤔  The built-in NodeConditions will be caught and evicted by the nodeLifeCycleController.

**Comment by googs1025** [comment]
@a7i @ingvagabund any comment? 😄

**Comment by googs1025** [comment]
I plan to add a plugin `customnodeconditions` that can be used with npd (node ​​problem detector).
@ingvagabund @a7i

```yaml
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: ProfileName
    pluginConfig:
      - name: "CustomNodeConditions"
        args:
          nodeConditions:
            - "CustomCondition1=true"
            - "CustomCondition2=false"
    plugins:
      deschedule:
        enabled:
          - "CustomNodeConditions"
```

**Comment by googs1025** [comment]
> I plan to add a plugin `customnodeconditions` that can be used with npd (node ​​problem detector). [@ingvagabund](https://github.com/ingvagabund) [@a7i](https://github.com/a7i)
> 
> apiVersion: "descheduler/v1alpha2"
> kind: "DeschedulerPolicy"
> profiles:
>   - name: ProfileName
>     pluginConfig:
>       - name: "CustomNodeConditions"
>         args:
>           nodeConditions:
>             - "CustomCondition1=true"
>             - "CustomCondition2=false"
>     plugins:
>       deschedule:
>         enabled:
>           - "CustomNodeConditions"
>           - 
@ingvagabund @ricardomaraschini wdyt? This plugin can well support node problem detect (NPD) 😄

**Comment by ricardomaraschini** [comment]
This seems to be a nice feature to have in the descheduler, I am curious to hear what others think. Taking your proposed configuration into account:

```yaml
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: ProfileName
    pluginConfig:
      - name: "CustomNodeConditions"
        args:
          nodeConditions:
            - "CustomCondition1=true"
            - "CustomCondition2=false"
    plugins:
      deschedule:
        enabled:
          - "CustomNodeConditions"
 ```

What pods are going to be evicted ? Pods running on nodes who contain **any** of these conditions or **all** of these conditions ?

A node condition type is of `corev1.NodeConditionType` and the status is of `corev1.ConditionStatus`. Condition status can be one of the following:

```go
const (
       ConditionTrue    ConditionStatus = "True"
       ConditionFalse   ConditionStatus = "False"
       ConditionUnknown ConditionStatus = "Unknown"
)
```

I would prefer to use these types, what do you think ? I can also see someone wanting to make evictions based on `Condition != True` (which would be equal to condition equal either to "False" or "Unknown"). 

More, this plugin will eventually require something else to taint the nodes based on the conditions otherwise the descheduled workload may just boomerang back. I wonder if we have the latter we don't the the first, I mean, with a tainter we don't need a new plugin.
