### ISSUE TITLE
Using ignorePodsWithoutPDB results in pod error

### ISSUE THREAD

**Issue by kreeuwijk** [kubernetes-sigs/descheduler#1552]
<!-- Please answer these questions before submitting your bug report. Thanks! -->

**What version of descheduler are you using?**

descheduler version: 0.31.0


**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
```
- args:                                                                                                                                                                                                                                
   - --policy-config-file=/policy-dir/policy.yaml                                                                                                                                                                                       
   - --v=3
```
**Please provide a copy of your descheduler policy config file**
```
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
    - name: default
      pluginConfig:
      - args:
          evictLocalStoragePods: true
          ignorePodsWithoutPDB: true
          ignorePvcPods: true
        name: DefaultEvictor
      - name: RemoveDuplicates
      - args:
          includingInitContainers: true
          podRestartThreshold: 100
        name: RemovePodsHavingTooManyRestarts
      - args:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
        name: RemovePodsViolatingNodeAffinity
      - name: RemovePodsViolatingNodeTaints
      - name: RemovePodsViolatingInterPodAntiAffinity
      - name: RemovePodsViolatingTopologySpreadConstraint
      - args:
          targetThresholds:
            cpu: 50
            memory: 50
            pods: 50
          thresholds:
            cpu: 20
            memory: 20
            pods: 20
        name: LowNodeUtilization
      plugins:
        balance:
          enabled:
          - RemoveDuplicates
          - RemovePodsViolatingTopologySpreadConstraint
          - LowNodeUtilization
        deschedule:
          enabled:
          - RemovePodsHavingTooManyRestarts
          - RemovePodsViolatingNodeTaints
          - RemovePodsViolatingNodeAffinity
          - RemovePodsViolatingInterPodAntiAffinity
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Server Version: v1.30.5
</pre></details>


**What did you do?**

I added `ignorePvcPods: true` to the DefaultEvictor args.

**What did you expect to see?**
Pod to start normally and not error.

**What did you see instead?**
```
I1114 16:20:41.048491       1 secure_serving.go:57] Forcing use of http/1.1 only                                                                                                                                                     I1114 16:20:41.059664       1 named_certificates.go:53] "Loaded SNI cert" index=0 certName="self-signed loopback" certDetail="\"apiserver-loopback-client@1731601241\" [serving] validServingFor=[apiserver-loopback-client] issuer=\"apiserver-loopback-client-ca@1731601240\" (2024-11-14 15:20:39 +0000 UTC to 2025-11-14 15:20:39 +0000 UTC (now=2024-11-14 16:20:41.059620547 +0000 UTC))"                                                                           I1114 16:20:41.059706       1 secure_serving.go:213] Serving securely on :10258                                                                                                                                                      I1114 16:20:41.059726       1 tracing.go:87] Did not find a trace collector endpoint defined. Switching to NoopTraceProvider                                                                                                         I1114 16:20:41.059791       1 tlsconfig.go:243] "Starting DynamicServingCertificateController"                                                                                                                                       E1114 16:20:41.061107       1 server.go:96] "descheduler server" err="failed decoding descheduler's policy config \"/policy-dir/policy.yaml\": strict decoding error: unknown field \"ignorePodsWithoutPDB\""                        E1114 16:20:41.061128       1 run.go:72] "command failed" err="failed decoding descheduler's policy config \"/policy-dir/policy.yaml\": strict decoding error: unknown field \"ignorePodsWithoutPDB\""
```

**Comment by kreeuwijk** [comment]
@john7doe FYI, some issue with trying to activate this new `ignorePodsWithoutPDB` feature

**Comment by kreeuwijk** [comment]
It seems that this works:
```
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    ignorePodsWithoutPDB: true
    profiles:
    - name: default
      pluginConfig:
      - args:
          evictLocalStoragePods: true
          ignorePvcPods: true
        name: DefaultEvictor
```

while this does not:
```
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
    - name: default
      pluginConfig:
      - args:
          evictLocalStoragePods: true
          ignorePvcPods: true
          ignorePodsWithoutPDB: true
        name: DefaultEvictor
```
