### ISSUE TITLE
Feature request: Descheduler policies at the namespace level

### ISSUE THREAD

**Issue by tspearconquest** [kubernetes-sigs/descheduler#1583]
**Is your feature request related to a problem? Please describe.**

I've configured Descheduler in a test cluster and I find it a little worrying having it running because while the policy is very descriptive, at the same time it is not very discriminate.

**Describe the solution you'd like**

What I'd like to do is setup different policies, potentially even with different evictors, for different use-cases within the same cluster. The best way I could think of handling this is as a CRD that I can apply in each namespace where I want descheduler to apply the policy. The next option I could think of was to continue using configmaps but read them from the Kubernetes API instead of reading from a volume in the pod.

In any case, I am running only a single instance of Descheduler; this is NOT a request to allow me to run multiple Descheduler instances in the same cluster. I just want to run one instance of Descheduler and have it apply policies per namespace like a built-in controller would do.

**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version: latest

**Additional context**

I'm a platform admin and while I can make use of labels and namespace selectors to target pods, the monolithic policy is not as flexible as I need it to be. Our clusters will be running a very diverse set of apps. Each app team has their own namespace in the cluster and we want to be able to give the app teams the final say in whether an eviction policy is applied to their workloads or not. They would not be able to edit the configmap currently used by Descheduler and we would not be able to accommodate the flexibility they need without making the config file overly complex. Having a descheduler policy defined in a single monolithic configmap prevents our app teams from making adjustments to the policy to accommodate their workloads and prevents our team from enforcing the organization's minimum standard in a way that is flexible and fair to all of our app teams.

**Comment by googs1025** [comment]
https://github.com/kubernetes-sigs/descheduler/blob/29ff28cbb57a59d55bed6f8f04e999620d6f813c/pkg/api/types.go#L53-L59

We have fields in each plugin that can filter namespaces, does this solve the problem?

**Comment by tspearconquest** [comment]
Hello, thank you for mentioning this. I feel that in my use case it isn't
going to allow me to achieve the goal that I detailed in the "additional
context" field of the issue.

**Comment by ingvagabund** [comment]
> Each app team has their own namespace in the cluster and we want to be able to give the app teams the final say in whether an eviction policy is applied to their workloads or not.

This is the crucial point. Would the namespaced policy include all the existing plugins or just plugins that are built to run over individual namespaces independently? E.g. RemoveDuplicate, PodLifeTime.

Some custom plugins that deal with enforcing security policies may not be configured on the namespace level. Yet, I can see benefit of allowing application teams to run some plugins. Would you please provide some examples? I.e. list of plugins (or custom/hypothetical ones if there any?) to run.

**Comment by tspearconquest** [comment]
> Would the namespaced policy include all the existing plugins or just plugins that are built to run over individual namespaces independently?

Plugins built to run over individual namespaces independently.

> Some custom plugins that deal with enforcing security policies may not be configured on the namespace level.

We're not currently using any plugins that enforce security policies; our `policy.yaml` currently looks as below.

```yaml
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
evictDaemonSetPods: true
evictFailedBarePods: true
evictLocalStoragePods: true
ignorePvcPods: false
maxNoOfPodsToEvictPerNamespace: 1
maxNoOfPodsToEvictPerNode: 3
profiles:
- name: default
  pluginConfig:
  - name: DefaultEvictor
  - name: RemoveDuplicates
  - args:
      includingInitContainers: true
      podRestartThreshold: 1024
      states:
      - CrashLoopBackOff
    name: RemovePodsHavingTooManyRestarts
  - args:
      excludeOwnerKinds:
      - DaemonSet
      - Job
      - ReplicaSet
      - StatefulSet
      includingInitContainers: true
    name: RemoveFailedPods
  - args:
      includedTaints:
      - node.kubernetes.io/disk-pressure
      - node.kubernetes.io/memory-pressure
      - node.kubernetes.io/network-unavailable
      - node.kubernetes.io/pid-pressure
    name: RemovePodsViolatingNodeTaints
  plugins:
    balance:
      enabled:
      - RemoveDuplicates
    deschedule:
      enabled:
      - RemoveFailedPods
      - RemovePodsHavingTooManyRestarts
      - RemovePodsViolatingNodeTaints
```

For the use-case I described, we currently can add a `namespaces.include` field to the `pluginConfig` for any of these plugins, but it doesn't achieve the desired goal of allowing the team to make that change; they have to ask us to make the change for them since they don't have access to the kube-system namespace.

**Comment by tspearconquest** [comment]
We've updated to Descheduler 0.34.0 and our config file now looks like this:

```yaml
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    maxNoOfPodsToEvictPerNamespace: 1
    maxNoOfPodsToEvictPerNode: 3
    maxNoOfPodsToEvictTotal: 6
    nodeSelector: kubernetes.azure.com/mode=user
    profiles:
    - name: default
      pluginConfig:
      - args:
          minPodAge: 60m
          noEvictionPolicy: Mandatory
          nodeFit: true
          podProtections:
            defaultDisabled:
            - DaemonSetPods
            - FailedBarePods
            - PodsWithLocalStorage
            extraEnabled:
            - PodsWithPVC
        name: DefaultEvictor
      - name: RemoveDuplicates
      - args:
          includingInitContainers: true
        name: RemoveFailedPods
      - args:
          includingInitContainers: true
          podRestartThreshold: 1024
          states:
          - CrashLoopBackOff
        name: RemovePodsHavingTooManyRestarts
      - args:
          includedTaints:
          - node.kubernetes.io/disk-pressure
          - node.kubernetes.io/memory-pressure
          - node.kubernetes.io/network-unavailable
          - node.kubernetes.io/pid-pressure
        name: RemovePodsViolatingNodeTaints
      plugins:
        balance:
          enabled:
          - RemoveDuplicates
        deschedule:
          enabled:
          - RemoveFailedPods
          - RemovePodsHavingTooManyRestarts
          - RemovePodsViolatingNodeTaints
```
