### ISSUE TITLE
charts: missing perms in ClusterRole if metricsCollector.enabled is true

### ISSUE THREAD

**Issue by linuxmaniac** [kubernetes-sigs/descheduler#1597]
**What version of descheduler are you using?**

descheduler version: v0.32.0

**Does this issue reproduce with the latest release?**

It's the latest one

**Which descheduler CLI options are you using?**

**Please provide a copy of your descheduler policy config file**
```
deschedulerPolicy:
      nodeSelector: node-role.kubernetes.io/worker=true
      metricsCollector:
        enabled: true
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.31.4
Kustomize Version: v5.4.2
Server Version: v1.31.2
</pre></details>

**What did you do?**

enabled metricsCollector

**What did you expect to see?**

**What did you see instead?**

```
E0103 12:37:27.584970       1 metricscollector.go:128] "Error fetching metrics" err="nodes.metrics.k8s.io \"k3s-node3\" is forbidden: User \"system:serviceaccount:kube-system:descheduler\" cannot get resource \"nodes\" in API group \"metrics.k8s.io\" at the cluster scope" node="k3s-node3"
```
