### ISSUE TITLE
Observed significant discrepancy in memory utilization reporting between descheduler logs and kubectl top nodes.

### ISSUE THREAD

**Issue by ramili4** [kubernetes-sigs/descheduler#1656]
The problem is that descheduler does not evict anything and thinks all nodes are underutilized. In reality, however, some nodes are close to a coma state due to resource usage. So I began investigating and so far I have a couple of questions about descheduler's methods of calculating resource usage. 

config (LowNodeUtilization)

```
LowNodeUtilization:
    enabled: true
    params:
      evictionGracePeriodSeconds: 10
      nodeFit: true
      nodeResourceUtilizationThresholds:
        thresholds:
          memory: 75
          pods: 20
        targetThresholds:
          memory: 90
          pods: 20
```

### Environment
- Kubernetes: 1.24.6 ( I know it's ancient)
- Descheduler: 0.24
- Infrastructure: On-premises Kubernetes cluster

### Specific Observation
- Descheduler log reports: 46.36% memory utilization
- Kubectl top nodes reports: 83% memory utilization

Descheduler's logs are: 
`Node is appropriately utilized" node="node1" usage=map[cpu:3775m memory:6312Mi pods:14] usagePercentage=map[cpu:49.671052631578945 memory:46.36885327285009 pods:12.727272727272727] `

kubectl top nodes output
`[node1](https://node1/) 294m 3% 11354Mi 83%`

Could you clarify the methodology behind memory utilization calculations?
