### ISSUE TITLE
config failure:  strict decoding error: unknown field \"metricsUtilization.source\""

### ISSUE THREAD

**Issue by stewartshea** [kubernetes-sigs/descheduler#1658]
**What version of descheduler are you using?**

descheduler version: v0.32.2

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**

**Please provide a copy of your descheduler policy config file**
We are using helm, this is the rendered configMap: 
```
policy.yaml:
----
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
metricsProviders:
- source: KubernetesMetrics
profiles:
- name: default
  pluginConfig:
  - args:
      evictLocalStoragePods: true
      ignorePvcPods: true
    name: DefaultEvictor
  - name: RemoveDuplicates
  - args:
      includingInitContainers: true
      podRestartThreshold: 100
    name: RemovePodsHavingTooManyRestarts
  - args:
      nodeAffinityType:
      - requiredDuringSchedulingIgnoredDuringExecution
    name: RemovePodsViolatingNodeAffinity
  - name: RemovePodsViolatingNodeTaints
  - name: RemovePodsViolatingInterPodAntiAffinity
  - name: RemovePodsViolatingTopologySpreadConstraint
  - args:
      metricsUtilization:
        source: KubernetesMetrics
      targetThresholds:
        cpu: 60
        memory: 60
        pods: 60
      thresholds:
        cpu: 40
        memory: 40
        pods: 40
    name: LowNodeUtilization
  - args:
      excludeOwnerKinds:
      - Job
      includingInitContainers: true
      minPodLifetimeSeconds: 3600
      reasons:
      - OutOfcpu
      - CreateContainerConfigError
    name: RemoveFailedPods
  plugins:
    balance:
      enabled:
      - RemoveDuplicates
      - RemovePodsViolatingTopologySpreadConstraint
      - LowNodeUtilization
    deschedule:
      enabled:
      - RemoveFailedPods
      - RemovePodsHavingTooManyRestarts
      - RemovePodsViolatingNodeTaints
      - RemovePodsViolatingNodeAffinity
      - RemovePodsViolatingInterPodAntiAffinity

```
**What k8s version are you using (`kubectl version`)?**
v.1.31.6-gke.1020000

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

We are using a Flux helm controller to install the descheduler, we simply tried to add the configuration to use the metricsUtilization (as outlined in the main docs), such that decisions would be made from actual utilization. Attempting to follow the docs continues to display the same configuration decoding error. Most other examples are for prometheus - but the KubernetesMetrics source should have worked. Removing this line under the LowNodeUtilization pluginConfig makes the error disappear. 

<details><summary><code>startup error</code> Output</summary><br><pre>

│ I0327 19:02:31.479261       1 feature_gate.go:387] feature gates: {map[]}                                                                                                                                        │
│ I0327 19:02:32.251593       1 secure_serving.go:57] Forcing use of http/1.1 only                                                                                                                                 │
│ I0327 19:02:32.251873       1 named_certificates.go:53] "Loaded SNI cert" index=0 certName="self-signed loopback" certDetail="\"apiserver-loopback-client@1743102152\" [serving] validServingFor=[apiserver-loop │
│ I0327 19:02:32.251932       1 secure_serving.go:213] Serving securely on :10258                                                                                                                                  │
│ I0327 19:02:32.251948       1 tracing.go:87] Did not find a trace collector endpoint defined. Switching to NoopTraceProvider                                                                                     │
│ I0327 19:02:32.251983       1 tlsconfig.go:243] "Starting DynamicServingCertificateController"                                                                                                                   │
│ I0327 19:02:32.252271       1 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false                                                                                               │
│ I0327 19:02:32.252292       1 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false                                                                                              │
│ I0327 19:02:32.252298       1 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false                                                                                        │
│ I0327 19:02:32.252302       1 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false                                                                                                │
│ E0327 19:02:32.254013       1 server.go:73] "failed to run descheduler server" err="failed decoding descheduler's policy config \"/policy-dir/policy.yaml\": strict decoding error: unknown field \"metricsUtili │
│ E0327 19:02:32.254063       1 run.go:72] "command failed" err="failed decoding descheduler's policy config \"/policy-dir/policy.yaml\": strict decoding error: unknown field \"metricsUtilization.source\""      │
│ Stream closed EOF for kube-system/descheduler-78f7c89544-tg7gl (descheduler)                                                                                                                                     │
│                                                                                   
</pre></details>

**What did you expect to see?**
We expected the K8s Metrics server to influence the descheduling / balance decisions

**What did you see instead?**

**Comment by googs1025** [comment]
I do get this error when using v0.32.2. I remember that we seem to support the metricsUtilization.source field in the master version. I can use it normally when using the master branch. But I can't remember exactly which pr it was merged with, maybe @ingvagabund knows. 😄

**Comment by ingvagabund** [comment]
I am not able to reproduce this:
```
$ git checkout release-1.32
$ make
$ ./descheduler --policy-config-file policy.yaml
```
The same for `master` and `release-1.31` branches.

**Comment by ingvagabund** [comment]
@stewartshea the new `source` field was merged recently through https://github.com/kubernetes-sigs/descheduler/pull/1614. We have not produced any release with the new field.

**Comment by ingvagabund** [comment]
> We are using a Flux helm controller to install the descheduler, we simply tried to add the configuration to use the metricsUtilization (as outlined in the main docs), such that decisions would be made from actual utilization.

@stewartshea I suggest to use the previous configuration from https://github.com/kubernetes-sigs/descheduler/tree/release-1.32?tab=readme-ov-file#lownodeutilization:
```
  - args:
      metricsUtilization:
        metricsServer: true
      targetThresholds:
        cpu: 60
        memory: 60
        pods: 60
      thresholds:
        cpu: 40
        memory: 40
        pods: 40
    name: LowNodeUtilization
```
With `metricsServer: true` instead. It's a new option in 1.32 that is deprecated in master/1.33.
