### ISSUE TITLE
Can't use descheduler.alpha.kubernetes.io/evict=false to disable evicton

### ISSUE THREAD

**Issue by kreeuwijk** [kubernetes-sigs/descheduler#1659]
**Is your feature request related to a problem? Please describe.**
We use VirtualMachine preferences in Kubevirt to default the use of the descheduler for any VMs using the those presets, by setting the `descheduler.alpha.kubernetes.io/evict: 'true'` annotation. But this makes it difficult to turn off the descheduler for specific VMs, as the descheduler actually accepts any value for the annotation. Overriding the annotation from the preset through the VM YAML is only possible if you specify an alternate value.

**Describe the solution you'd like**
I would like to be able to set the annotation
```
descheduler.alpha.kubernetes.io/evict: 'false'
```
and have the descheduler treat that pod as if no annotation was set on it.

**Describe alternatives you've considered**
The only other options that worked were:
* Remove the annotation from the VM preferences altogether and go back to specifying it in the VM YAML. This isn't very user friendly
* Create "No DRS" copies of the VM preferences that don't have the annotation but are the same otherwise. This also isn't very user friendly

**What version of descheduler are you using?**

descheduler version: 0.32.2

**Additional context**
N/A

**Comment by kreeuwijk** [comment]
>> We use VirtualMachine preferences in Kubevirt to default the use of the descheduler

>Would you please elaborate more on this? There are other ways to tell the descheduler to focus on particular pods. E.g. specifying a label selector or a list of included/excluded namespace. Have you explored this option?

Here's an example of a VM preference:
```
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference
metadata:
  name: generic-linux
spec:
  annotations:
    descheduler.alpha.kubernetes.io/evict: "true"
  clock:
    preferredClockOffset:
      utc: {}
      #timezone: America/New_York
  cpu:
    preferredCPUTopology: spread   
    spreadOptions:
      across: SocketsCores
      ratio: 4
  devices:
    preferredDiskBus: virtio
    preferredDiskCache: writethrough
    preferredInterfaceModel: virtio
    preferredRng: {}
  machine:
    preferredMachineType: q35
  preferredTerminationGracePeriodSeconds: 180
```

When you then create a VM, you can link to this VM preference by setting:
```
spec:
  preference:
    name: generic-linux
```
in the `VirtualMachine` object. This is a nice way to reduce the content in the VM spec and make things generally easier on the user. For example. the user doesn't need to set the descheduler annotation on the VM manually, instead it comes via the VM preference.

There is however one issue, that is when the VM preference is used, but the user wants to override the descheduler option and prevent the descheduler from managing this VM. There is no way to remove an annotation coming from a VM preference, but you can override the value of an annotation.
