### ISSUE TITLE
RemoveDuplicates does not take effect

### ISSUE THREAD

**Issue by Cairry** [kubernetes-sigs/descheduler#1669]
**What version of descheduler are you using?**

descheduler version:
v0.20.0

**Does this issue reproduce with the latest release?**

**Which descheduler CLI options are you using?**

**Please provide a copy of your descheduler policy config file**
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
        enabled: true
        params:
          namespaces:
            include:
            - "ztest"
          excludeOwnerKinds:
          - "ReplicaSet"
          - "Deployment"
      "RemovePodsViolatingInterPodAntiAffinity":
        enabled: true
        params:
          namespaces:
            include:
            - "ztest"
      "LowNodeUtilization":
        enabled: true
        params:
          namespaces:
            include:
            - "ztest"
          nodeResourceUtilizationThresholds:
            thresholds:
              "cpu" : 20
              "memory": 20
              "pods": 20
            targetThresholds:
              "cpu" : 50
              "memory": 50
              "pods": 50

```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.20.4
```

</pre></details>

**What did you do?**
```
log-server-5bb7989b7b-875hk                   2/2     Running   0          45m    10.15.7.250    cn-beijing.172.17.5.220   <none>           <none>
log-server-5bb7989b7b-9s7k4                   2/2     Running   0          17m    10.15.7.253    cn-beijing.172.17.5.220   <none>           <none>
log-server-5bb7989b7b-ns8jn                   2/2     Running   0          17m    10.15.7.254    cn-beijing.172.17.5.220   <none>           <none>
log-server-5bb7989b7b-tp55j                   2/2     Running   0          17m    10.15.7.252    cn-beijing.172.17.5.220   <none>           <none>
log-server-5bb7989b7b-zwsgm                   2/2     Running   0          127d   10.15.7.234    cn-beijing.172.17.5.220   <none>           <none>
```
```
cn-beijing.172.17.5.220   Ready    <none>   485d   v1.20.4 
cn-beijing.172.17.5.221   Ready    <none>   485d   v1.20.4
cn-beijing.172.17.5.222   Ready    <none>   485d   v1.20.4 
cn-beijing.172.17.5.235   Ready    <none>   342d   v1.20.4 
```

**What did you expect to see?**

**What did you see instead?**

**Comment by googs1025** [comment]
Can you show the descheduler log info? Also, please increase the log level for better tuning.  :)

**Comment by Cairry** [comment]
I don't see the corresponding relationship of log level, so I don't know how much I should adjust it to.

**Comment by googs1025** [comment]
what this log-server yaml look like? 
does log-server use LocalStorage? we will filter some pod by config like 
```go
 - name: ProfileName
    pluginConfig:
    - name: "DefaultEvictor"
      args:
        evictSystemCriticalPods: true
        evictFailedBarePods: true
        evictLocalStoragePods: true
        nodeFit: true
        minReplicas: 2
```
use can see more info here : https://github.com/kubernetes-sigs/descheduler?tab=readme-ov-file#evictor-plugin-configuration-default-evictor

**Comment by Cairry** [comment]
> what this log-server yaml look like?这个 log-server YAML 是什么样的？ does log-server use LocalStorage? we will filter some pod by config likelog-server 是否使用 LocalStorage？我们将通过配置过滤一些 Pod，例如
> 
>  - name: ProfileName
>     pluginConfig:
>     - name: "DefaultEvictor"
>       args:
>         evictSystemCriticalPods: true
>         evictFailedBarePods: true
>         evictLocalStoragePods: true
>         nodeFit: true
>         minReplicas: 2
> use can see more info here : https://github.com/kubernetes-sigs/descheduler?tab=readme-ov-file#evictor-plugin-configuration-default-evictor用户可以在此处查看更多信息：https://github.com/kubernetes-sigs/descheduler?tab=readme-ov-file#evictor-plugin-configuration-default-evictor

Thanks, log-server does have hostpath, enabling evictLocalStoragePods: true worked for me.

I want to learn more about the working principle. For example, if log-server runs 5 pods on the same node, how does its eviction/rescheduling ratio work when RemoveDuplicates is enabled? Can it be customized?

In addition, is it possible to reschedule all pods? This will cause business interruption.

**Comment by googs1025** [comment]
`ignorePodsWithoutPDB`  can control whether the workload is bound to PDB. If set to true, it means that workloads that are not bound to PDB will not be evicted. PDB is a CR to ensure service stability. This may solve your problem.

```yaml
    pluginConfig:
      - args:
          evictLocalStoragePods: true
          ignorePvcPods: true
          ignorePodsWithoutPDB: true
        name: DefaultEvictor
      - name: RemoveDuplicates
        args:
          namespaces:
            include:
              - "default"
     ....

```
