### ISSUE TITLE
cnpg and descheduler

### ISSUE THREAD

**Issue by vtmocanu** [kubernetes-sigs/descheduler#1689]
Anyone managed to get descheduler to work with the CNPG operator?
The pods are managed by the operator so rescheduled ignores them, as they are not part of a deployment.
This is the configuration I have tried:

```
        pluginConfig:
          - name: DefaultEvictor
            args:
              ignorePvcPods: false
              evictLocalStoragePods: true
              labelSelector:
                matchExpressions:
                  - {
                      key: cnpg.io/instanceRole,
                      operator: NotIn,
                      values: [primary],
                    }
          - name: RemoveDuplicates
          - name: RemovePodsHavingTooManyRestarts
            args:
              podRestartThreshold: 100
              includingInitContainers: true
          - name: RemovePodsViolatingNodeAffinity
            args:
              nodeAffinityType:
                - requiredDuringSchedulingIgnoredDuringExecution
          - name: RemovePodsViolatingNodeTaints
          - name: RemovePodsViolatingInterPodAntiAffinity
          - name: RemovePodsViolatingTopologySpreadConstraint
            args:
              constraints:
                - DoNotSchedule
                - ScheduleAnyway
          - name: LowNodeUtilization
            args:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 50
                memory: 50
                pods: 50
        plugins:
          balance:
            enabled:
              - RemoveDuplicates
              - RemovePodsViolatingTopologySpreadConstraint
              - LowNodeUtilization
          deschedule:
            enabled:
              - RemovePodsHavingTooManyRestarts
              - RemovePodsViolatingNodeTaints
              - RemovePodsViolatingNodeAffinity
              - RemovePodsViolatingInterPodAntiAffinity

```

The issue I am trying to solve:
- drain a node
- some replicas move to other node
- initial node recovers, but replicas remain on another node and I end up with multiple replicas on the same node.

**Comment by googs1025** [comment]
If labelSelector is used, only pods matching this label will be evicted. 
code: https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/framework/plugins/defaultevictor/defaultevictor.go#L147-L159 

If we want to add pod eviction for specific workload management, perhaps we need new feature about a more flexible conifg to implement this. 🤔

**Comment by ingvagabund** [comment]
> The pods are managed by the operator so rescheduled ignores them, as they are not part of a deployment.

Can you please share the pod manifests and a reproducer?

**Comment by vtmocanu** [comment]
this is the CNPG PSQL Cluster CR:
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-4"
    argocd.argoproj.io/tracking-id: k8s-blue-cc-kutt:postgresql.cnpg.io/Cluster:kutt/cnpg-kutt
  labels:
    app.kubernetes.io/instance: kutt
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cnpg
    app.kubernetes.io/part-of: cloudnative-pg
    helm.sh/chart: cnpg-0.3.1
    wxs.io/backup: ignore
  name: cnpg-kutt
  namespace: kutt
spec:
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname
  backup:
    barmanObjectStore:
      data:
        compression: gzip
        jobs: 2
      destinationPath: s3://psql-bkp-blue/
      endpointURL: https://m3.example.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: cnpg-creds-s3-backup
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: cnpg-creds-s3-backup
      wal:
        compression: gzip
        maxParallel: 1
    retentionPolicy: 30d
    target: prefer-standby
  bootstrap:
    recovery:
      database: app
      owner: app
      source: objectStoreRecoveryCluster
  enablePDB: true
  enableSuperuserAccess: true
  externalClusters:
    - barmanObjectStore:
        destinationPath: s3://psql-bkp-green/
        endpointURL: https://m3.example.com
        s3Credentials:
          accessKeyId:
            key: ACCESS_KEY_ID
            name: cnpg-creds-s3-backup
          secretAccessKey:
            key: ACCESS_SECRET_KEY
            name: cnpg-creds-s3-backup
        serverName: cnpg-kutt
      name: objectStoreRecoveryCluster
  failoverDelay: 0
  imageName: harbor.example.com/repl-cloudnative-pg/postgresql:17.6
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: k8sro-robot-secret
  instances: 3
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  priorityClassName: high-priority-service
  probes:
    liveness:
      isolationCheck:
        connectionTimeout: 1000
        enabled: true
        requestTimeout: 1000
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      cpu: "4"
      ephemeral-storage: 2Gi
      memory: 2Gi
    requests:
      cpu: 10m
      ephemeral-storage: 1Gi
      memory: 100Mi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 3Gi
  superuserSecret:
    name: cnpg-kutt-su
  switchoverDelay: 3600
```

and the Cluster creates pods like this:
this is the primary:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cnpg.io/nodeSerial: "15"
    cnpg.io/operatorVersion: 1.27.0
    cnpg.io/podEnvHash: 6d9685cdb9
    cnpg.io/podSpec: '{"volumes":[{"name":"pgdata","persistentVolumeClaim":{"claimName":"cnpg-kutt-15"}},{"name":"scratch-data","emptyDir":{}},{"name":"shm","emptyDir":{"medium":"Memory"}}],"initContainers":[{"name":"bootstrap-controller","image":"ghcr.io/cloudnative-pg/cloudnative-pg:1.27.0","command":["/manager","bootstrap","/controller/manager","--log-level=info"],"resources":{"limits":{"cpu":"4","ephemeral-storage":"2Gi","memory":"2Gi"},"requests":{"cpu":"10m","ephemeral-storage":"1Gi","memory":"100Mi"}},"volumeMounts":[{"name":"pgdata","mountPath":"/var/lib/postgresql/data"},{"name":"scratch-data","mountPath":"/run"},{"name":"scratch-data","mountPath":"/controller"},{"name":"shm","mountPath":"/dev/shm"}],"imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"drop":["ALL"]},"privileged":false,"runAsNonRoot":true,"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"seccompProfile":{"type":"RuntimeDefault"}}}],"containers":[{"name":"postgres","image":"harbor.example.com/repl-cloudnative-pg/postgresql:17.6","command":["/controller/manager","instance","run","--status-port-tls","--log-level=info"],"ports":[{"name":"postgresql","containerPort":5432,"protocol":"TCP"},{"name":"metrics","containerPort":9187,"protocol":"TCP"},{"name":"status","containerPort":8000,"protocol":"TCP"}],"env":[{"name":"PGDATA","value":"/var/lib/postgresql/data/pgdata"},{"name":"POD_NAME","value":"cnpg-kutt-15"},{"name":"NAMESPACE","value":"kutt"},{"name":"CLUSTER_NAME","value":"cnpg-kutt"},{"name":"PSQL_HISTORY","value":"/controller/tmp/.psql_history"},{"name":"PGPORT","value":"5432"},{"name":"PGHOST","value":"/controller/run"},{"name":"TMPDIR","value":"/controller/tmp"}],"resources":{"limits":{"cpu":"4","ephemeral-storage":"2Gi","memory":"2Gi"},"requests":{"cpu":"10m","ephemeral-storage":"1Gi","memory":"100Mi"}},"volumeMounts":[{"name":"pgdata","mountPath":"/var/lib/postgresql/data"},{"name":"scratch-data","mountPath":"/run"},{"name":"scratch-data","mountPath":"/controller"},{"name":"shm","mountPath":"/dev/shm"}],"livenessProbe":{"httpGet":{"path":"/healthz","port":8000,"scheme":"HTTPS"},"timeoutSeconds":5,"periodSeconds":10},"readinessProbe":{"httpGet":{"path":"/readyz","port":8000,"scheme":"HTTPS"},"timeoutSeconds":5,"periodSeconds":10},"startupProbe":{"httpGet":{"path":"/startupz","port":8000,"scheme":"HTTPS"},"timeoutSeconds":5,"periodSeconds":10,"failureThreshold":360},"imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"drop":["ALL"]},"privileged":false,"runAsNonRoot":true,"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"seccompProfile":{"type":"RuntimeDefault"}}}],"terminationGracePeriodSeconds":1800,"serviceAccountName":"cnpg-kutt","securityContext":{"runAsUser":26,"runAsGroup":26,"runAsNonRoot":true,"fsGroup":26,"seccompProfile":{"type":"RuntimeDefault"}},"hostname":"cnpg-kutt-15","affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":100,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"cnpg.io/cluster","operator":"In","values":["cnpg-kutt"]},{"key":"cnpg.io/podRole","operator":"In","values":["instance"]}]},"topologyKey":"kubernetes.io/hostname"}}]}},"priorityClassName":"high-priority-service"}'
    k8tz.io/injected: "true"
    k8tz.io/timezone: Europe/Bucharest
  labels:
    cnpg.io/cluster: cnpg-kutt
    cnpg.io/instanceName: cnpg-kutt-15
    cnpg.io/instanceRole: primary
    cnpg.io/podRole: instance
    role: primary
    wxs.io/backup: ignore
  name: cnpg-kutt-15
  namespace: kutt
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: cnpg.io/cluster
                  operator: In
                  values:
                    - cnpg-kutt
                - key: cnpg.io/podRole
                  operator: In
                  values:
                    - instance
            topologyKey: kubernetes.io/hostname
          weight: 100
  containers:
    - command:
        - /controller/manager
        - instance
        - run
        - --status-port-tls
        - --log-level=info
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POD_NAME
          value: cnpg-kutt-15
        - name: NAMESPACE
          value: kutt
        - name: CLUSTER_NAME
          value: cnpg-kutt
        - name: PSQL_HISTORY
          value: /controller/tmp/.psql_history
        - name: PGPORT
          value: "5432"
        - name: PGHOST
          value: /controller/run
        - name: TMPDIR
          value: /controller/tmp
        - name: TZ
          value: Europe/Bucharest
      image: harbor.example.com/repl-cloudnative-pg/postgresql:17.6
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
          scheme: HTTPS
        timeoutSeconds: 5
      name: postgres
      ports:
        - containerPort: 5432
          name: postgresql
        - containerPort: 9187
          name: metrics
        - containerPort: 8000
          name: status
      readinessProbe:
        httpGet:
          path: /readyz
          port: 8000
          scheme: HTTPS
        timeoutSeconds: 5
      resources:
        limits:
          cpu: "4"
          ephemeral-storage: 2Gi
          memory: 2Gi
        requests:
          cpu: 10m
          ephemeral-storage: 1Gi
          memory: 100Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      startupProbe:
        failureThreshold: 360
        httpGet:
          path: /startupz
          port: 8000
          scheme: HTTPS
        timeoutSeconds: 5
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
        - mountPath: /run
          name: scratch-data
        - mountPath: /controller
          name: scratch-data
        - mountPath: /dev/shm
          name: shm
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-zhcg7
          readOnly: true
        - mountPath: /etc/localtime
          name: k8tz
          readOnly: true
          subPath: Europe/Bucharest
        - mountPath: /usr/share/zoneinfo
          name: k8tz
          readOnly: true
  hostname: cnpg-kutt-15
  imagePullSecrets:
    - name: k8sro-robot-secret
  initContainers:
    - command:
        - /manager
        - bootstrap
        - /controller/manager
        - --log-level=info
      image: ghcr.io/cloudnative-pg/cloudnative-pg:1.27.0
      name: bootstrap-controller
      resources:
        limits:
          cpu: "4"
          ephemeral-storage: 2Gi
          memory: 2Gi
        requests:
          cpu: 10m
          ephemeral-storage: 1Gi
          memory: 100Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
        - mountPath: /run
          name: scratch-data
        - mountPath: /controller
          name: scratch-data
        - mountPath: /dev/shm
          name: shm
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-zhcg7
          readOnly: true
    - args:
        - bootstrap
      image: harbor.example.com/repl-k8tz/k8tz:0.18.0
      name: k8tz
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 30Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /mnt/zoneinfo
          name: k8tz
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-zhcg7
          readOnly: true
  preemptionPolicy: PreemptLowerPriority
  priority: 100000000
  priorityClassName: high-priority-service
  securityContext:
    fsGroup: 26
    runAsGroup: 26
    runAsNonRoot: true
    runAsUser: 26
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: cnpg-kutt
  terminationGracePeriodSeconds: 1800
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 60
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 60
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: cnpg-kutt-15
    - name: scratch-data
    - emptyDir:
        medium: Memory
      name: shm
    - name: kube-api-access-zhcg7
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    fieldPath: metadata.namespace
                  path: namespace
    - name: k8tz
```

and this is a replica:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cnpg.io/nodeSerial: "17"
    cnpg.io/operatorVersion: 1.27.0
    cnpg.io/podEnvHash: 584646ccd7
    cnpg.io/podSpec: '{"volumes":[{"name":"pgdata","persistentVolumeClaim":{"claimName":"cnpg-kutt-17"}},{"name":"scratch-data","emptyDir":{}},{"name":"shm","emptyDir":{"medium":"Memory"}}],"initContainers":[{"name":"bootstrap-controller","image":"ghcr.io/cloudnative-pg/cloudnative-pg:1.27.0","command":["/manager","bootstrap","/controller/manager","--log-level=info"],"resources":{"limits":{"cpu":"4","ephemeral-storage":"2Gi","memory":"2Gi"},"requests":{"cpu":"10m","ephemeral-storage":"1Gi","memory":"100Mi"}},"volumeMounts":[{"name":"pgdata","mountPath":"/var/lib/postgresql/data"},{"name":"scratch-data","mountPath":"/run"},{"name":"scratch-data","mountPath":"/controller"},{"name":"shm","mountPath":"/dev/shm"}],"imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"drop":["ALL"]},"privileged":false,"runAsNonRoot":true,"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"seccompProfile":{"type":"RuntimeDefault"}}}],"containers":[{"name":"postgres","image":"harbor.example.com/repl-cloudnative-pg/postgresql:17.6","command":["/controller/manager","instance","run","--status-port-tls","--log-level=info"],"ports":[{"name":"postgresql","containerPort":5432,"protocol":"TCP"},{"name":"metrics","containerPort":9187,"protocol":"TCP"},{"name":"status","containerPort":8000,"protocol":"TCP"}],"env":[{"name":"PGDATA","value":"/var/lib/postgresql/data/pgdata"},{"name":"POD_NAME","value":"cnpg-kutt-17"},{"name":"NAMESPACE","value":"kutt"},{"name":"CLUSTER_NAME","value":"cnpg-kutt"},{"name":"PSQL_HISTORY","value":"/controller/tmp/.psql_history"},{"name":"PGPORT","value":"5432"},{"name":"PGHOST","value":"/controller/run"},{"name":"TMPDIR","value":"/controller/tmp"}],"resources":{"limits":{"cpu":"4","ephemeral-storage":"2Gi","memory":"2Gi"},"requests":{"cpu":"10m","ephemeral-storage":"1Gi","memory":"100Mi"}},"volumeMounts":[{"name":"pgdata","mountPath":"/var/lib/postgresql/data"},{"name":"scratch-data","mountPath":"/run"},{"name":"scratch-data","mountPath":"/controller"},{"name":"shm","mountPath":"/dev/shm"}],"livenessProbe":{"httpGet":{"path":"/healthz","port":8000,"scheme":"HTTPS"},"timeoutSeconds":5,"periodSeconds":10},"readinessProbe":{"httpGet":{"path":"/readyz","port":8000,"scheme":"HTTPS"},"timeoutSeconds":5,"periodSeconds":10},"startupProbe":{"httpGet":{"path":"/startupz","port":8000,"scheme":"HTTPS"},"timeoutSeconds":5,"periodSeconds":10,"failureThreshold":360},"imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"drop":["ALL"]},"privileged":false,"runAsNonRoot":true,"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"seccompProfile":{"type":"RuntimeDefault"}}}],"terminationGracePeriodSeconds":1800,"serviceAccountName":"cnpg-kutt","securityContext":{"runAsUser":26,"runAsGroup":26,"runAsNonRoot":true,"fsGroup":26,"seccompProfile":{"type":"RuntimeDefault"}},"hostname":"cnpg-kutt-17","affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":100,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"cnpg.io/cluster","operator":"In","values":["cnpg-kutt"]},{"key":"cnpg.io/podRole","operator":"In","values":["instance"]}]},"topologyKey":"kubernetes.io/hostname"}}]}},"priorityClassName":"high-priority-service"}'
    k8tz.io/injected: "true"
    k8tz.io/timezone: Europe/Bucharest
  labels:
    cnpg.io/cluster: cnpg-kutt
    cnpg.io/instanceName: cnpg-kutt-17
    cnpg.io/instanceRole: replica
    cnpg.io/podRole: instance
    role: replica
    wxs.io/backup: ignore
  name: cnpg-kutt-17
  namespace: kutt
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: cnpg.io/cluster
                  operator: In
                  values:
                    - cnpg-kutt
                - key: cnpg.io/podRole
                  operator: In
                  values:
                    - instance
            topologyKey: kubernetes.io/hostname
          weight: 100
  containers:
    - command:
        - /controller/manager
        - instance
        - run
        - --status-port-tls
        - --log-level=info
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POD_NAME
          value: cnpg-kutt-17
        - name: NAMESPACE
          value: kutt
        - name: CLUSTER_NAME
          value: cnpg-kutt
        - name: PSQL_HISTORY
          value: /controller/tmp/.psql_history
        - name: PGPORT
          value: "5432"
        - name: PGHOST
          value: /controller/run
        - name: TMPDIR
          value: /controller/tmp
        - name: TZ
          value: Europe/Bucharest
      image: harbor.example.com/repl-cloudnative-pg/postgresql:17.6
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
          scheme: HTTPS
        timeoutSeconds: 5
      name: postgres
      ports:
        - containerPort: 5432
          name: postgresql
        - containerPort: 9187
          name: metrics
        - containerPort: 8000
          name: status
      readinessProbe:
        httpGet:
          path: /readyz
          port: 8000
          scheme: HTTPS
        timeoutSeconds: 5
      resources:
        limits:
          cpu: "4"
          ephemeral-storage: 2Gi
          memory: 2Gi
        requests:
          cpu: 10m
          ephemeral-storage: 1Gi
          memory: 100Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      startupProbe:
        failureThreshold: 360
        httpGet:
          path: /startupz
          port: 8000
          scheme: HTTPS
        timeoutSeconds: 5
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
        - mountPath: /run
          name: scratch-data
        - mountPath: /controller
          name: scratch-data
        - mountPath: /dev/shm
          name: shm
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-2d6w6
          readOnly: true
        - mountPath: /etc/localtime
          name: k8tz
          readOnly: true
          subPath: Europe/Bucharest
        - mountPath: /usr/share/zoneinfo
          name: k8tz
          readOnly: true
  hostname: cnpg-kutt-17
  imagePullSecrets:
    - name: k8sro-robot-secret
  initContainers:
    - command:
        - /manager
        - bootstrap
        - /controller/manager
        - --log-level=info
      image: ghcr.io/cloudnative-pg/cloudnative-pg:1.27.0
      name: bootstrap-controller
      resources:
        limits:
          cpu: "4"
          ephemeral-storage: 2Gi
          memory: 2Gi
        requests:
          cpu: 10m
          ephemeral-storage: 1Gi
          memory: 100Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
        - mountPath: /run
          name: scratch-data
        - mountPath: /controller
          name: scratch-data
        - mountPath: /dev/shm
          name: shm
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-2d6w6
          readOnly: true
    - args:
        - bootstrap
      image: harbor.example.com/repl-k8tz/k8tz:0.18.0
      name: k8tz
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 30Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /mnt/zoneinfo
          name: k8tz
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-2d6w6
          readOnly: true
  preemptionPolicy: PreemptLowerPriority
  priority: 100000000
  priorityClassName: high-priority-service
  securityContext:
    fsGroup: 26
    runAsGroup: 26
    runAsNonRoot: true
    runAsUser: 26
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: cnpg-kutt
  terminationGracePeriodSeconds: 1800
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 60
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 60
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: cnpg-kutt-17
    - name: scratch-data
    - emptyDir:
        medium: Memory
      name: shm
    - name: kube-api-access-2d6w6
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    fieldPath: metadata.namespace
                  path: namespace
    - name: k8tz
```

ideally descheduler would move only replicas, not primary based on `cnpg.io/instanceRole` label.
Thank for looking into this and let me know if I can help further.
