### ISSUE TITLE
Enhance Descheduler Metrics to Include Specific Arg(Rule) Violation Details

### ISSUE THREAD

**Issue by Colvin-Y** [kubernetes-sigs/descheduler#1692]
**Is your feature request related to a problem? Please describe.**

Currently, the descheduler_pods_evicted metric only indicates which plugin caused a pod eviction (e.g., RemovePodsViolatingNodeAffinity). However, when a plugin is configured with multiple arguments or sub-rules (e.g., different nodeAffinityType values), the metric does not specify which exact rule/argument was violated. This lack of granularity makes it difficult to debug and monitor evictions effectively.

**Describe the solution you'd like**

- Introduce a new `strategyName` field in the pluginConfig struct to allow users to assign an alias or identifier to a specific rule configuration.
- Propagate the`strategyName` value as a label (strategy_name) in the descheduler_pods_evicted metric.

Example Configuration
```
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: ProfileName
    pluginConfig:
    - name: "RemovePodsViolatingNodeTaints"
      strategyName: "include-decommissioned" # Custom identifier for this strategy
      args:
        includedTaints:
        - decommissioned=end-of-life 
    - name: "RemovePodsViolatingNodeTaints"
      strategyName: "include-reserved" # Custom identifier for this strategy
      args:
        includedTaints:
        - reserved 
    plugins:
      deschedule:
        enabled:
          - "RemovePodsViolatingNodeTaints"
```
Resulting Metric
```
descheduler_pods_evicted{
  plugin="RemovePodsViolatingNodeTaints",
  strategy_name="include-decommissioned",  # New label
  ...
}
```

**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version: release-1.27

**Additional context**

Use Case:
- Users need precise visibility into which specific rule caused evictions, especially when a single plugin is configured with multiple parameters (e.g., resource thresholds, affinity types). However, it is challenging for each plugin to explicitly identify which specific argument (rule) has been violated. Therefore, it can be split at the plugin level, allowing multiple config items to be configured for the same plugin, with different items distinguished by the strategyName.
- Backward Compatibility:
The `strategyName` field should be optional to avoid breaking existing configurations.
