### ISSUE TITLE
Prometheus URL scheme must use HTTPS

### ISSUE THREAD

**Issue by calvinbui** [kubernetes-sigs/descheduler#1703]
**What version of descheduler are you using?**

descheduler version: 0.33.0

**Does this issue reproduce with the latest release?**

Yes

**Which descheduler CLI options are you using?**

```
    - --policy-config-file=/policy-dir/policy.yaml
    - --descheduling-interval=5m
    - --v=4
```

**Please provide a copy of your descheduler policy config file**

```
apiVersion: v1
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    metricsProviders:
    - source: KubernetesMetrics
    - source: Prometheus
      prometheus:
        url: http://thanos-query.prometheus-operator.svc.cluster.local:9090
    profiles:
    - name: default
      pluginConfig:
      - args:
          evictDaemonSetPods: true
          evictFailedBarePods: false
          evictLocalStoragePods: true
          evictSystemCriticalPods: false
          ignorePvcPods: false
        name: DefaultEvictor
      - args:
          includingInitContainers: true
          podRestartThreshold: 10
        name: RemovePodsHavingTooManyRestarts
      - name: RemovePodsViolatingNodeTaints
      - args:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
        name: RemovePodsViolatingNodeAffinity
      - name: RemovePodsViolatingInterPodAntiAffinity
      - name: RemovePodsViolatingTopologySpreadConstraint
      plugins:
        balance:
          enabled:
          - RemovePodsViolatingTopologySpreadConstraint
        deschedule:
          enabled:
          - RemovePodsHavingTooManyRestarts
          - RemovePodsViolatingNodeTaints
          - RemovePodsViolatingNodeAffinity
          - RemovePodsViolatingInterPodAntiAffinity
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: descheduler
    meta.helm.sh/release-namespace: descheduler
  labels:
    app.kubernetes.io/instance: descheduler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: descheduler
    app.kubernetes.io/version: 0.33.0
    helm.sh/chart: descheduler-0.33.0
  name: descheduler
  namespace: descheduler
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.3-eks-bcf3d70
</pre></details>

**What did you do?**

Configured the Prometheus metricsProvider to `http://thanos-query.prometheus-operator.svc.cluster.local:9090`.

**What did you expect to see?**

Prometheus working. This aligns with the documentation which also uses HTTP 

https://github.com/kubernetes-sigs/descheduler/blob/2d7528411a7c0c8c1a99c87d4aef4e2f032e7f0d/README.md?plain=1#L183-L190

**What did you see instead?**

CrashLoopBackOff:

```
E0604 02:03:44.266592       1 server.go:73] "failed to run descheduler server" err="prometheus URL's scheme is not https, got \"http\" instead"
E0604 02:03:44.266627       1 run.go:72] "command failed" err="prometheus URL's scheme is not https, got \"http\" instead"
stream closed EOF for descheduler/descheduler-9c6cf8dfb-bf644 (descheduler)
```
