### ISSUE TITLE
Pods with Annotation "scheduler.alpha.kubernetes.io/critical-pod" are constantly terminated

### ISSUE THREAD

**Issue by Voolkanus23** [kubernetes-sigs/descheduler#189]
Hi,
I'm trying to set up a Descheduler for my cluster, and based on the readme if a pod is annotated with the "scheduler.alpha.kubernetes.io/critical-pod" annotation, it shouldn't be terminated by the Descheduler app. However, seems like it's not working properly. I'm having a deployment that as part of it config this annotation has been set up. And describing the running pods I can see that the annotation exists as part of the pod. Yet, Descheduler is still terminating the pods(using the "RemoveDuplicates" policy). I tried to enable the PodPriority and PriorityClass gates on the API level, and it did nothing. Can you please help me to sort it out? 

Thanks in advance!

![Screenshot 2019-10-11 at 10 35 34](https://user-images.githubusercontent.com/47102630/66637484-697f6080-ec13-11e9-9e92-cf4a27db0c79.png)

**Comment by amnk** [comment]
That feature was part of kubelet, and was [removed in 1.16](https://github.com/kubernetes/kubernetes/pull/80342). Afaik, now `spec.priorityClassName` should be used to mark pods as critical.

**Comment by alperbas** [comment]
I have a similar problem with kubelet v1.15.3. low node utilisation policy evicts critical pods. Pod priority and prority class does not change the result. Has anyone encountered this before?

**Comment by ananace** [comment]
I'm seeing the issue on Kubernetes 1.15.0 as well, pods with both the `scheduler.alpha.kubernetes.io/critical-pod` annotation set, as well as with `priorityClassName: system-node-critical` are still being evicted.

**Comment by damemi** [comment]
We check if a pod is critical based on their `pod.Spec.Priority` https://github.com/kubernetes-sigs/descheduler/blob/8a62cf16999b19d42c94f9a94da9b1db07427377/pkg/utils/pod.go#L122

Which is set to `2 * int32(1000000000)` (copied from the [scheduler's defined SystemCriticalPriority](https://github.com/kubernetes/kubernetes/blob/a9f0db16614ae62563ead2018f1692407bd93d8f/pkg/apis/scheduling/types.go#L30-L32) https://github.com/kubernetes-sigs/descheduler/blob/8a62cf1699/pkg/utils/priority.go#L9

Is this value wrong for these priority classes?

**Comment by seanmalloy** [comment]
I was not able to reproduce this bug using [kind ](https://kind.sigs.k8s.io/) v0.8.1 with k8s v1.18.2. Here are the steps I followed to try and reproduce this issue.

```
cat << EOF > kind.yml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
- role: worker
EOF
kind create cluster --config kind.yml
cat << EOF > ns.yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: "demo"
spec:
EOF
kubectl apply -f ns.yml
cat << EOF > app.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      priorityClassName: system-cluster-critical
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
EOF
kubectl apply -f app.yml -n demo
sleep 60
cat << EOF > rbac.yml
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: descheduler-cluster-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: descheduler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: descheduler-cluster-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descheduler-cluster-role
subjects:
  - name: descheduler-sa
    kind: ServiceAccount
    namespace: kube-system
EOF
kubectl apply -f rbac.yml
cat << EOF > configmap.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "LowNodeUtilization":
        enabled: false
      "RemoveDuplicates":
        enabled: false
      "RemovePodsViolatingInterPodAntiAffinity":
        enabled: false
      "RemovePodsViolatingNodeAffinity":
        enabled: false
      "RemovePodsViolatingNodeTaints":
        enabled: false
      "RemovePodsHavingTooManyRestarts":
        enabled: false
      "PodLifeTime":
        enabled: true
        params:
          maxPodLifeTimeSeconds: 10
EOF
kubectl apply -f configmap.yml
cat << EOF > job.yml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: descheduler-job
  namespace: kube-system
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: descheduler-pod
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: descheduler
          image: us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.18.0
          volumeMounts:
          - mountPath: /policy-dir
            name: policy-volume
          command:
            - "/bin/descheduler"
          args:
            - "--policy-config-file"
            - "/policy-dir/policy.yaml"
            - "--v"
            - "3"
      restartPolicy: "Never"
      serviceAccountName: descheduler-sa
      volumes:
      - name: policy-volume
        configMap:
          name: descheduler-policy-configmap
EOF
kubectl apply -f job.yml
```

**Comment by seanmalloy** [comment]
I was able to reproduce this bug using kind v0.8.1 with k8s 1.15.11. To reproduce this bug use the annotation `scheduler.alpha.kubernetes.io/critical-pod` NOT `spec.priorityClassName`. The steps to reproduce are the same as https://github.com/kubernetes-sigs/descheduler/issues/189#issuecomment-641017558 except use the below commands to create the kid cluster and create the `Deployment`.
```
kind create cluster --config kind.yml --image kindest/node:v1.15.11
cat << EOF > app.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
EOF
kubectl apply -f app.yml
```
