### ISSUE TITLE
Add HighNodeUtilization strategy

### ISSUE THREAD

**Issue by vvbogdanov87** [kubernetes-sigs/descheduler#196]
I want to keep my cluster as compact as possible. In order to do that, I switched kubernetes-scheduler policy from LeastRequestedPriority to MostRequestedPriority. It would be greate to have corresponding HighNodeUtilization strategy for descheduler.

**Comment by NGTOne** [comment]
👍 for this.

**Comment by hanumanthan** [comment]
hi @seanmalloy   `HighNodeUtilization` - Is it the inverse of `LowNodeUtilization` ?
If a node's utilization <= threshold, evict pods from that node such that `MostRequestedPriority` will reschedule it accordingly ?

**Comment by seanmalloy** [comment]
> hi @seanmalloy   `HighNodeUtilization` - Is it the inverse of `LowNodeUtilization` ?
> If a node's utilization <= threshold, evict pods from that node such that `MostRequestedPriority` will reschedule it accordingly ?
> 

@hanumanthan yes that is correct.

**Comment by hanumanthan** [comment]
@seanmalloy I think https://github.com/kubernetes-sigs/descheduler#lownodeutilization should be called as `HighNodeUtilisation` as its evicting pods from nodes which are highly utilised and this feature is `LowNodeUtilisation` - evict pods from nodes that are under utilised 😄 

Interested to pick this up. The strategy would be like
```yaml
strategies:
  "HighNodeUtilization":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           "cpu" : 20
           "memory": 20
           "pods": 20
```
Calculate total utilised resources in a node and if its less than the threshold, consider pods in those nodes for eviction. 
Do we need a similar TargetThreshold ?

**Comment by seanmalloy** [comment]
@hanumanthan thanks for offering to work on this feature.

I believe we should not use the word "utilization" to describe this descheduler strategy. We should instead name it something like `HighNodeAllocation`. I proposed renaming the `LowNodeUtilization` strategy to `LowNodeAllocation` when creating the v1alpha2 API. See this https://github.com/kubernetes-sigs/descheduler/pull/314#issuecomment-638975891.

Maybe something like this:
```
strategies:
  "HighNodeAllocation":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           "cpu" : 20
           "memory": 20
           "pods": 20
```

@damemi and @ingvagabund what do you think? Can we have @hanumanthan start implementing this new strategy? Are there additional details we need to work out before starting to implement this?
