### ISSUE TITLE
Would be nice to have a CronJob example

### ISSUE THREAD

**Issue by dmitrievav** [kubernetes-sigs/descheduler#199]
Here is a CronJob example to rebalance pods on worker nodes every night

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: descheduler
  namespace: kube-system
spec:
  schedule: "0,30 3 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 600 # 1 min
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 3
      activeDeadlineSeconds: 3300 # 55min
      template:
        metadata:
          annotations:
            scheduler.alpha.kubernetes.io/critical-pod: ""
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          serviceAccountName: descheduler-sa
          volumes:
          - name: policy-volume
            configMap:
              name: descheduler-policy-configmap
          containers:
          - name: descheduler
            image: descheduler:0.9.0-55-gbbc902b8
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:
              - "/bin/descheduler"
            args:
              - "--policy-config-file"
              - "/policy-dir/policy.yaml"
              - "--v"
              - "3"
```
