### ISSUE TITLE
Strategy For Pod Life Time

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#205]
This is an enhancement proposal to add a new descheduler strategy for evicting old pods. I would like to be able to evict pods that were created more than `X` hours ago.

Here are my initial thoughts on the API for a new `PodLifeTime` strategy. In this example the descheduler would evict all pods that were created more than 24 hours ago.
```
kind: "DeschedulerPolicy"
apiVersion: "descheduler/v1alpha1"
strategies:
  "PodLifeTime":
     enabled: true
     params:
        maxPodLifeTimeHours: 24
```

**Comment by seanmalloy** [comment]
Any feedback on this proposal would be greatly appreciated.

CC: @sanbornick @vinny-sabatini

**Comment by seanmalloy** [comment]
Here is a slightly different proposal, specify the max pod life time in minutes instead of hours.

```
kind: "DeschedulerPolicy"
apiVersion: "descheduler/v1alpha1"
strategies:
  "PodLifeTime":
     enabled: true
     params:
        maxPodLifeTimeMinutes: 1440   # 24 hours
```

**Comment by mcandre** [comment]
Don't allow users to omit units: Accept a Go-compatible time duration string.

https://golang.org/pkg/time/#ParseDuration

**Comment by seanmalloy** [comment]
@ravisantoshgudimetla @aveshagarwal @damemi do you have any thoughts on this proposal? Does this sound reasonable?

**Comment by damemi** [comment]
Not sure if this applies here, but I think Kubernetes convention prefers having the units in the field name (https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#units), which also makes it easier for non-go clients to parse the API. 

If that's the case then I agree with the smaller units (ie `Minutes` instead of `Hours`, or maybe even `Seconds`)

**Comment by seanmalloy** [comment]
Based on the feedback from @damemi here is the updated proposal.

```
kind: "DeschedulerPolicy"
apiVersion: "descheduler/v1alpha1"
strategies:
  "PodLifeTime":
     enabled: true
     params:
        maxPodLifeTimeSeconds: 86400   # 24 hours
```
