### ISSUE TITLE
Elements of nodeResourceUtilizationThresholds should be optional

### ISSUE THREAD

**Issue by cguethle** [kubernetes-sigs/descheduler#212]
The "balance" of my workload is solely based on Memory requests. I have no idea what my cpu or pod usages look like. And for the sake of the descheduler, I don't really care. How can I have it identify under and over utilized nodes based purely on Memory?

**Comment by aleksmark** [comment]
Any update on this? I find this suggestion useful...

**Comment by seanmalloy** [comment]
@aleksmark no updates yet.

**Comment by seanmalloy** [comment]
/kind feature

Still no updates.

**Comment by lixiang233** [comment]
@cguethle @aleksmark @seanmalloy  elements of nodeResourceUtilizationThresholds are optional now, if we only want to consider memory allocation, just run descheduler with this policy:
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "LowNodeUtilization":
    enabled: true
    params:
      nodeResourceUtilizationThresholds:
        thresholds:
          "memory" : 20
        targetThresholds:
          "memory" : 70
```
nodes with memory usage over 70% will be considered as `overutilizated` and vice versa.

you can refer to this pr #285 for more information, in this pr we added default values to the strategy's params and changed the stop condition.
