### ISSUE TITLE
Use actual node resource utilization in the strategy "LowNodeUtilization"

### ISSUE THREAD

**Issue by zhiyxu** [kubernetes-sigs/descheduler#225]
Currently, pods' request resource requirements are considered for computing node resource utilization in the strategy "LowNodeUtilization", is it more rational to use actual node resource utilization as judgement?

It is common that resource limit of pod is larger than request, and after the scheduling of default scheduler (by resource request), It's probably that cluster is balanced. But the actual resources usage of pod could be much larger than request, which may lead some nodes under pressure.

So is it much more reasonable to combine with metrics server and use actual node resource utilization.

**Comment by seanmalloy** [comment]
@zhiyxu it looks like you are not the first person to request this feature. See the discussions in #123 , #118, and #7. Based on the discussions in those issues it looks like the descheduler `LowNodeUtilization` strategy is still using requests because this aligns with how the k8s scheduler works. Also, this feature is mentioned in the [roadmap](https://github.com/kubernetes-sigs/descheduler#roadmap).

@damemi @aveshagarwal @ravisantoshgudimetla has anything changed recently to enable the k8s scheduler to use real load metrics during scheduling? For example could the new scheduler framework some how enable this feature in the scheduler? Maybe a custom plugin using the scheduler framework could be created to take real load metrics in account?

**Comment by zhiyxu** [comment]
@seanmalloy @ravisantoshgudimetla @damemi @aveshagarwal Any update or plan about this feature?

**Comment by kangtiann** [comment]
+1, We need this feature too.

If we can make a PR for this ?

@seanmalloy @ravisantoshgudimetla @damemi @aveshagarwal

**Comment by seanmalloy** [comment]
@zhiyxu and @kangtiann here are my initial thoughts on what the API spec might look like. Please let me know what you think. I'm pretty confident the v1alpha2 `LowNodeUtilization` strategy will need to be adjusted.

I believe it would be a good idea to write a proposal for this and have SIG scheduling review this.

Create a  new v1alpha1 `LowNodeAllocation` strategy. This strategy will work identically to the request based v1alpha `LowNodeUtilization` strategy. The usage of the work allocation is inspired by the discussion in #7. 
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "LowNodeAllocation":
     enabled: true
     params:
       nodeResourceAllocatedThresholds:
         thresholds:
           "cpu" : 20
           "memory": 20
           "pods": 20
         targetThresholds:
           "cpu" : 50
           "memory": 50
           "pods": 50
```


Create a new v1alpha2 `LowNodeUtilization` strategy. This strategy will get data from the [metrics API](https://github.com/kubernetes/metrics) to evict pods from nodes based on actual node utilization metrics. The below proposed YAML API spec is a rough draft and will need to be refined.

The [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics) supports custom metrics. Does the descheduler also need to support custom metrics too?

Keep in mind that the k8s scheduler does not take actual node utilization into account when scheduling pods. Pods evicted by this strategy could end up being scheduled on the same node again. Maybe this strategy could be paired with a yet to be created [out of tree scheduler plugin](https://github.com/kubernetes-sigs/scheduler-plugins) that takes node utilization into account when scheduling pods. See the discussions in #123 and #118. 
```
apiVersion: "descheduler/v1alpha2".   # Bump to v1alpha2
kind: "DeschedulerPolicy"
strategies:
  "LowNodeUtilization":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           "cpu" : 20
           "memory": 20
         targetThresholds:
           "cpu" : 50
           "memory": 50
```
