### ISSUE TITLE
RemovePodsViolatingInterPodAntiAffinity ignores preferredDuringSchedulingIgnoredDuringExecution

### ISSUE THREAD

**Issue by asnkh** [kubernetes-sigs/descheduler#250]
The strategy silently assumes `requiredDuringSchedulingIgnoredDuringExecution` is used
https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/strategies/pod_antiaffinity.go#L99-L101
but `preferredDuringSchedulingIgnoredDuringExecution` may be used as well.  It is useful if descheduler can evict pods scheduled in a zone (when `topologyKey: failure-domain.beta.kubernetes.io/zone` is used) or a host (when `topologyKey: kubernetes.io/hostname` is used) where another pod of same type had been already running.  This may happen if there are no enough resources in the cluster at the time of scheduling.  Later, when more nodes are added by `cluster-autoscaler` or temporary-failed nodes come back, it is desirable to evict the pods violating inter-pod anti-affinity so that the pods evenly spread across zones/hosts.

Similarly to `RemovePodsViolatingNodeAffinity`, this behavior should be controlled by an additional parameter.  The resource syntax will be like below:
```yaml
apiVersion: descheduler/v1alpha1
kind: DeschedulerPolicy
strategies:
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: true
    params:
      nodeAffinityType:
      - preferredDuringSchedulingIgnoredDuringExecution
```
