### ISSUE TITLE
Logging is broken with the switch to klog/v2

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#353]
Testing a build with and without the changes in https://github.com/kubernetes-sigs/descheduler/pull/327, the switch to klog/v2 seems to have broken logging and nothing is printed, even at log level 5.

**What version of descheduler are you using?**
descheduler version: built from latest master

**Does this issue reproduce with the latest release?**
not 1.18, yes for 1.19

**Which descheduler CLI options are you using?**
```
        - --policy-config-file=/policy-dir/policy.yaml
        - --v=5
        - --descheduling-interval=3600s
```

**Please provide a copy of your descheduler policy config file**
```
  policy.yaml: |
    strategies:
      LowNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            numberOfNodes: 3
            targetThresholds:
              cpu: 10
              memory: 20
              pods: 30
            thresholds:
              cpu: 10
              memory: 20
              pods: 30
      RemoveDuplicates:
        enabled: true
```

**What k8s version are you using (`kubectl version`)?**
```
$ oc version
Client Version: v4.2.0-alpha.0-361-gcb858ac
Server Version: 4.6.0-0.nightly-2020-07-15-170241
Kubernetes Version: v1.18.3+7024740
```

/priority critical-urgent
