### ISSUE TITLE
How to restrict descheduler activity to the certain namespace and node groups?

### ISSUE THREAD

**Issue by disparo13** [kubernetes-sigs/descheduler#377]
I have a problem with restricting descheduler's activity to only certain namespaces and node groups. I mean - I need to descheduler process only pods in the certain namespace named "dev" and node group with the label "env=dev". First, I tried to replace default ClusterRoleBinding with two role bindings:

```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: descheduler-cluster-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: descheduler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: descheduler-cluster-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descheduler-cluster-role
subjects:
  - name: descheduler-sa
    kind: ServiceAccount
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: descheduler-cluster-role-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descheduler-cluster-role
subjects:
  - name: descheduler-sa
    kind: ServiceAccount
    namespace: kube-system


```

but that didn't work

`I0817 12:30:08.173707       1 node.go:45] node lister returned empty list, now fetch directly
I0817 12:30:08.177200       1 descheduler.go:85] Unable to get ready nodes: nodes is forbidden: User "system:serviceaccount:kube-system:descheduler-sa" cannot list resource "nodes" in API group "" at the cluster scope`

Is there any way to solve my problem?

**Comment by lixiang233** [comment]
You can set startup parameter `node-selector` in descheduler to let descheduler run only on nodes that matches the node labels. e.g.
```
command:
  - "/bin/descheduler"
args:
  - "--policy-config-file"
  - "/policy-dir/policy.yaml"
  - "--v"
  - "3"
  - "--node-selector"
  - "env=dev"
```
also you can refer to [Filter Pods](https://github.com/kubernetes-sigs/descheduler#filter-pods) and set `include namespace` in every strategy to let them excute over certain namespaces. e.g.
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "PodLifeTime":
     enabled: true
     params:
        maxPodLifeTimeSeconds: 86400
        namespaces:
          include:
          - "dev"
```
