### ISSUE TITLE
 KubeJobCompletion Prometheus alert for desheduler jobs

### ISSUE THREAD

**Issue by KR411-prog** [kubernetes-sigs/descheduler#432]
We are receiving  KubeJobCompletion Prometheus alert for desheduler jobs with the below alert message,
kube-system/descheduler-1603424400 is taking more than 12 hours to complete.

The descheduler values file config is as shown below,
```
fullnameOverride: descheduler
nameOverride: descheduler
deschedulerPolicy:
  nodeSelector: kops.k8s.io/instancegroup=nodes
  evict-local-storage-pods: false
  maxNoOfPodsToEvictPerNode: 4
  strategies:
    RemoveDuplicates:
      enabled: true
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
    RemovePodsViolatingNodeAffinity:
      enabled: true
    LowNodeUtilization:
      enabled: true
      params:
        numberOfNodes: 2
        nodeResourceUtilizationThresholds:
          # node is underutilized if all 3 metrics are below the threshold
          thresholds:
            "cpu" : 50
            "memory": 30
            "pods": 30
          # node is overutilized is any of these 3 metrics is above the target threshold
          targetThresholds:
            "cpu" : 80
            "memory": 70
            "pods": 50
    RemovePodsHavingTooManyRestarts:
      enabled: true
      params:
        podsHavingTooManyRestarts:
          podRestartThreshold: 100
          includingInitContainers: true
    PodLifeTime:
      enabled: false
rbac:
  create: true
schedule: "*/2 * * * *"
```

I am not sure if there is a way in the config to tune to delete the job if it takes more than 30 mins. I dont find that tuning configuration in the values file in this helm chart.
    chart: descheduler/descheduler-helm-chart
    version: "0.19.0"

Any help on how to avoid getting this alert? Is there any tuning that can be done in descheduler config?
