### ISSUE TITLE
Tried to use PodLifeTime but i get "pod_lifetime.go:53] MaxPodLifeTimeSeconds not set·

### ISSUE THREAD

**Issue by IJOL** [kubernetes-sigs/descheduler#447]
using this policy.yaml ( very close to examples ) :+1: 

```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
evictLocalStoragePods: true
strategies:
  "RemoveDuplicates":
     enabled: true
  "RemovePodsViolatingInterPodAntiAffinity":
     enabled: true
  "LowNodeUtilization":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           "cpu" : 20
           "memory": 20
           "pods": 30
         targetThresholds:
           "cpu" : 50
           "memory": 50
           "pods": 45
  "PodLifeTime":
     enabled: true
     params:
        podLifeTime:
          maxPodLifeTimeSeconds: 86400
        namespaces:
          include:
          - "odoo"
-------------

```
Log says below message no matter how put that parameter in the file..

`I1126 08:38:52.583156       1 pod_lifetime.go:53] MaxPodLifeTimeSeconds not set
`-------------

other strategie seem to work ok, at least what we tried...

**Comment by seanmalloy** [comment]
@IJOL what version of descheduler are you using?

**Comment by IJOL** [comment]
The one present in the examples, v0.19.0, my policy file is:


--------------
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
evictLocalStoragePods: true
strategies:
  "RemoveDuplicates":
     enabled: true
  "RemovePodsViolatingInterPodAntiAffinity":
     enabled: true
  "LowNodeUtilization":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           "cpu" : 20
           "memory": 20
           "pods": 30
         targetThresholds:
           "cpu" : 50
           "memory": 50
           "pods": 45
  "PodLifeTime":
     enabled: true
     params:
        podLifeTime:
          maxPodLifeTimeSeconds: 86400
        namespaces:
          include:
          - "odoo"
----

Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by damemi** [comment]
@IJOL it appears you may be using the examples from the master branch (ie, 1.20 in-progress). The pod lifetime params were refactored, please see the docs from the 1.19 branch if you are running the 1.19 image: https://github.com/kubernetes-sigs/descheduler/tree/release-1.19#podlifetime

So your podlifetime section should look like this:
```
  "PodLifeTime":
     enabled: true
     params:
        maxPodLifeTimeSeconds: 86400
```
