### ISSUE TITLE
Allow specifying custom 'podStatusPhases' for 'RemovePodsHavingTooManyRestarts' strategy 

### ISSUE THREAD

**Issue by svaranasi-traderev** [kubernetes-sigs/descheduler#477]
**Is your feature request related to a problem? Please describe.**

We run CI/CD agents on our k8s clusters and these agents are discarded after every use. The main reason for doing that is to get a clean slate for every CI/CD job. The agent's functionality is beyond our control as we use [MS Azure Devops agents and set them to run once](https://developercommunity.visualstudio.com/content/problem/1289864/run-once-self-hosted-linux-agents-on-kubernetes-tr.html). 

However, when the container exits (exit code 0), it triggers Kubernetes' crashloop exponential backoff algorithm. This slows down the restart of these pods and thus slowing down our CI/CD jobs. Ideally, k8s would allow [you to configure/turn-off ](https://github.com/kubernetes/kubernetes/issues/57291) this setting, but it hasn't happened yet.

**Describe the solution you'd like**

Add a 'podStatusPhases' parameter to the 'RemovePodsHavingTooManyRestarts' strategy to allow also including pod status phases aside from [the current 'Succeeded' and 'Failed'](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/pod/pods.go#L75).

I believe this could also prove useful in scenarios such as when you have pods being restarted after being OOM killed, and it would make sense to schedule such pods onto other, more idle, nodes.

**What version of descheduler are you using?**

descheduler version: 0.20.0

**Comment by damemi** [comment]
@svaranasi-traderev I may be misunderstanding, but the TooManyRestarts strategy was designed specifically with crashlooping pods in mind as a use case. The code you linked to is actually *excluding* `Succeeded` and `Failed` pods (there is no use in evicting these, so all strategies ignore them by default).

What is the status phase you would like to include? Perhaps this is already available to you :)

**Comment by svaranasi-traderev** [comment]
My apologies, I _completely_ misread that line. So it does look like descheduler is equipped to look at pods that are in "Pending", "Running" and "Unknown" states. 

The reason I started to dig into code was because descheduler isn't evicting pods that have more than `podRestartThreshold` container restarts. 

This is the config, and the installation is via helm with descheduler running as a CronJob every 2m.

```
deschedulerPolicy:
  strategies:
    RemoveDuplicates:
      enabled: false
    LowNodeUtilization:
      enabled: false
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: false
    RemovePodsViolatingNodeAffinity:
      enabled: false
    RemovePodsViolatingNodeTaints:
      enabled: false
    RemovePodsViolatingTopologySpreadConstraint:
      enabled: false
    PodLifeTime:
      enabled: false
    RemovePodsHavingTooManyRestarts:
      enabled: true
      params:
        podsHavingTooManyRestarts:
          podRestartThreshold: 3
          includingInitContainers: true
          namespaces:
            include: 
            - ado-agent
```


Pods:

```
ado-agent                ado-agent-66495fd549-jwxvc                                1/1     Running             10         12h
ado-agent                ado-agent-66495fd549-wk9pf                                1/1     Running             9          12h
ado-agent                ado-agent-66495fd549-xlzcr                                1/1     Running             9          12h
```

Pods aren't evicted and the logs only show this:
```
E0104 17:02:05.980390       1 server.go:50] "failed to validate server configuration" err="unsupported log format: "
I0104 17:02:05.998530       1 node.go:46] "Node lister returned empty list, now fetch directly" 
I0104 17:02:06.013644       1 toomanyrestarts.go:73] "Processing node" node="ip-10-xxx-28-117.ec2.internal"
I0104 17:02:06.054639       1 toomanyrestarts.go:73] "Processing node" node="ip-10-xxx-28-27.ec2.internal"
I0104 17:02:06.091771       1 toomanyrestarts.go:73] "Processing node" node="ip-10-xxx-29-191.ec2.internal"
I0104 17:02:06.119782       1 toomanyrestarts.go:73] "Processing node" node="ip-10-xxx-30-116.ec2.internal"
I0104 17:02:06.148073       1 toomanyrestarts.go:73] "Processing node" node="ip-10-xxx-30-18.ec2.internal"
I0104 17:02:06.182583       1 toomanyrestarts.go:73] "Processing node" node="ip-10-xxx-30-50.ec2.internal"
I0104 17:02:06.217687       1 toomanyrestarts.go:73] "Processing node" node="ip-10-xxx-30-62.ec2.internal"
I0104 17:02:06.252218       1 toomanyrestarts.go:73] "Processing node" node="ip-10-xxx-31-214.ec2.internal"
stream closed
```

Let me know if I should open another issue for this. Thank you!
