### ISSUE TITLE
Deployment pods can't evicted

### ISSUE THREAD

**Issue by zhangshangbj** [kubernetes-sigs/descheduler#485]
This is my configmap file.

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
         enabled: true
```

**Comment by zhangshangbj** [comment]
The cronjob file:

```
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: descheduler-cronjob
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: descheduler-pod
        spec:
          imagePullSecrets:
          - name: pppharbor
          priorityClassName: system-cluster-critical
          containers:
          - name: descheduler
            image: 10.111.9.72/k8s/descheduler:v0.20.0
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:
              - "/bin/descheduler"
            args:
              - "--policy-config-file"
              - "/policy-dir/policy.yaml"
              - "--v"
              - "3"
            resources:
              requests:
                cpu: "500m"
                memory: "256Mi"
          restartPolicy: "Never"
          serviceAccountName: descheduler-sa
          volumes:
          - name: policy-volume
            configMap:
              name: descheduler-policy-configmap
```

**Comment by zhangshangbj** [comment]
**I've found the problem. -- *Pods associated with DaemonSets are never evicted*
My pods are loaded with local storage,but I need to evict pods with local storage.
What should I do?**

**Comment by lixiang233** [comment]
@zhangshangbj  setting `evictLocalStoragePods` to true will evict pods with local storage.
eg:
```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
evictLocalStoragePods: true
strategies:
   "RemoveDuplicates":
      enabled: true
```
