### ISSUE TITLE
Multiple descheduler strategies of the same type

### ISSUE THREAD

**Issue by irmiller22** [kubernetes-sigs/descheduler#486]
**Is your feature request related to a problem? Please describe.**

k8s version: 1.18
descheduler version: 1.18

Currently, we have `CronJob` resources that are getting stuck due to this k8s issue: https://github.com/kubernetes/kubernetes/issues/52172. We are using managed k8s (EKS), and 1.19 is not available yet. The issue is apparently fixed in 1.19, but we're unable to upgrade.

Long story short, a `CronJob` pod will spin up, and will immediately get stuck due to the bug described in the linked issue above, and the pod will ultimately end up in `Waiting` state with the reason being `CreateContainerError`.

```
State:          Waiting
  Reason:       CreateContainerError
 ```
 
 The only way to address this currently is to manually delete the problematic pods and have k8s re-schedule the CronJob objects during the next scheduled run. Currently, these problematic pods are blocking the CronJob resource from scheduling new pods.

**Describe the solution you'd like**
We'd like to leverage descheduler to handle this case by allowing for multiple `PodLifeTime` strategies. As I understand it from the documentation, we're only allowed to implement one definition per strategy. We'd like to have a policy that applies only to our `CronJob` objects (which have a priority class called `service-cron`), and another policy that applies to all other pods.

For example, the below configuration would be desired:

```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "PodLifeTime":
     enabled: true
     params:
       podLifeTime:
         maxPodLifeTimeSeconds: 86400
         podStatusPhases:
         - "Pending"
  "PodLifeTime":
     enabled: true
     params:
       podLifeTime:
        maxPodLifeTimeSeconds: 86400
        podStatusPhases:
         - "Running"
        thresholdPriorityClassName: "service-cron" # this is a custom priority class
```

If there are other ways to accomplish this, please let me know! I'm open to suggestions.

**Describe alternatives you've considered**

We've considered upgrading our self-managed clusters to 1.19, but our managed clusters are unable to upgrade since 1.19 isn't available yet. We'd prefer not to run into version drift across our clusters.

**What version of descheduler are you using?**

descheduler version: 1.18

**Additional context**

**Comment by damemi** [comment]
Hi @irmiller22, thanks for opening this issue. We have discussed similar requests before (I thought there was an open issue, but I couldn't find it), so there is definitely some validity to what you describe.

One option we discussed was something similar to scheduler profiles (https://kubernetes.io/docs/reference/scheduling/config/#multiple-profiles). This would take some minor refactoring but is certainly doable.

Since I couldn't find another issue for this, maybe we can officially open discussion on this here. @ingvagabund @seanmalloy wdyt?

**Comment by ingvagabund** [comment]
> We'd like to have a policy that applies only to our CronJob objects (which have a priority class called service-cron)

There's currently no way to separate pods into two distinct groups and have multiple instances of the same strategy to target different group. Specifying `thresholdPriorityClassName` in the strategy will still evict any pod that has the priority of the class of lower.

It's more better to allow a strategy to target specific group of pods based on a [label selector](https://github.com/kubernetes-sigs/descheduler/issues/195). `thresholdPriorityClassName` is used for deciding if a pod gets evicted or not.

Nevertheless, +1 for allowing running multiple instances of the same strategy wherever it's applicable. We might start with `PodLifeTime` though it will require to re-design the policy file. E.g.

```yaml
apiVersion: "descheduler/v1alpha2" <-- notice the version bump
kind: "DeschedulerPolicy"
strategies:
  - name: PodLifeTime
  - enabled: true
  ...
  - name: PodLifeTime
  - enabled: true
  ...
```
