### ISSUE TITLE
No `--logging-format` default set

### ISSUE THREAD

**Issue by irmiller22** [kubernetes-sigs/descheduler#487]
**What version of descheduler are you using?**

descheduler version: v0.20.0

**Does this issue reproduce with the latest release?**
Yes.

**Which descheduler CLI options are you using?**
`--policy-config-file`, `--v`, and `--evict-local-storage-pods`.

**Please provide a copy of your descheduler policy config file**

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemovePodsHavingTooManyRestarts":
        enabled: true
        params:
          podsHavingTooManyRestarts:
            podRestartThreshold: 5
            includingInitContainers: true
      "PodLifeTime":
        enabled: true
        params:
          podLifeTime:
            maxPodLifeTimeSeconds: 600
            podStatusPhases:
            - "Pending"
```

**What k8s version are you using (`kubectl version`)?**
1.19.

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**
Upgrade descheduler from v0.18.0 to v0.20.0.

**What did you expect to see?**
No errors regarding log output.

**What did you see instead?**

```
ianmiller@ianmiller ../seismic/infra irmiller22/upgrade-descheduler-1.20 ❯ kubectl logs -f -n kube-system descheduler-cronjob-1611593520-sbrlk
E0125 16:52:18.007331       1 server.go:50] "failed to validate server configuration" err="unsupported log format: "
```

If `--logging-format` is not specified, you'll see this error output. I would expect descheduler to set a default format (either `text` or `json`). I could be wrong and this might actually be an explicit design decision that was made when [the `--logging-format` flag](https://github.com/kubernetes-sigs/descheduler/commit/3ac0c408de3ac963d0054289e7ac61b9a64f5178) was added.
