### ISSUE TITLE
 Exclude namespace is invalid

### ISSUE THREAD

**Issue by 1032231418** [kubernetes-sigs/descheduler#511]
Hi：
          kubernetes version:  v1.16.9
         descheduler version:  v0.20.0
         Exclude namespace is invalid
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "PodLifeTime":
         enabled: true
         params:
            podLifeTime:
              maxPodLifeTimeSeconds: 86400
            namespaces:
              include:
              - "dev"
              exclude:
              - "kube-system"
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 50
               "memory": 20
               "pods": 20
             targetThresholds:
               "cpu" : 70
               "memory": 30
               "pods": 20
```
![248A9953-357A-41d1-B559-34C04A04465B](https://user-images.githubusercontent.com/5716348/109467276-eaa7f380-7aa5-11eb-9686-fc2feedbce42.png)
