### ISSUE TITLE
Descheduler not evicting pods with node selectors

### ISSUE THREAD

**Issue by gaurav1086** [kubernetes-sigs/descheduler#524]
**What version of descheduler are you using?**

descheduler version: v0.20.0

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
N/A

**Please provide a copy of your descheduler policy config file**

```
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      RemovePodsViolatingInterPodAntiAffinity:
         enabled: true
      RemovePodsViolatingTopologySpreadConstraint:
         enabled: true
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

We tried to rebalance pods on a group of nodes with the same (and only 1) Node-Selector.

In our case, we have 3 eligible nodes with the node selector say x=y where we are running a total of 15 pods. The current pod distribution is 7,5,3 .

**What did you expect to see?**

The pods should be balanced. Expected pod distribution should be: 5,5,5 .

**What did you see instead?**

Descheduler refuses to evict pods from nodes with the following error in the logs: 
`{"level":"INFO","message":"\"Ignoring pod for eviction due to node selector/affinity\" pod=\"mypod\""}`
