### ISSUE TITLE
RemoveDuplicates: does not take cordoned nodes into account

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/descheduler#531]
Hi I've just came up against this exact issue and I can confirm 0.20 fixes the issue when I have a higher replica count than nodes BUT it does not take into account nodes that are cordoned. If I have a replica set of 3, 2 active nodes and 1 cordoned node I still get the issue with a continuous loop destroying my pod.

_Originally posted by @Evilweebl in https://github.com/kubernetes-sigs/descheduler/issues/463#issuecomment-749550117_

**Comment by seanmalloy** [comment]
See #42 for some historical context. Looks like a similar issues was fixed for the LowNodeUtilization strategy.

**Comment by a7i** [comment]
Cordoned nodes get tainted as shown below:
```
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    timeAdded: "2021-01-17T15:25:45Z"
```

Meaning that this PR #563 should address this.

PR #567 fixed this for strategy `RemovePodsViolatingTopologySpreadConstraint`
