### ISSUE TITLE
useless code?

### ISSUE THREAD

**Issue by zhangguanzhang** [kubernetes-sigs/descheduler#540]
https://github.com/kubernetes-sigs/descheduler/blob/ce6ce5a0581481316b57368b0ebc50f4a3bbc25a/pkg/descheduler/strategies/lownodeutilization.go#L81-L99

L88-L99 let the empty map to set value, but the function `validateThresholds` , this `len(thresholds) == 0` will conflict it
https://github.com/kubernetes-sigs/descheduler/blob/ce6ce5a0581481316b57368b0ebc50f4a3bbc25a/pkg/descheduler/strategies/lownodeutilization.go#L171-L174

**Comment by lixiang233** [comment]
`validateThresholds` returns error only when none of these three thresholds are set, so this is a valid case:
```yaml
thresholds:
           "cpu" : 20
           "pods": 20
targetThresholds:
           "cpu" : 50
           "pods": 50
```
but we must set the missing threshold(in this case `memory`) to `MaxResourcePercentage ` so that this strategy can run normally.
