### ISSUE TITLE
Question about prometheus metrics from descheduler

### ISSUE THREAD

**Issue by audip** [kubernetes-sigs/descheduler#571]
The suggested deployments of descheduler are as a Job or CronJob, but as neither of them are long-lived, how are folks in the community capturing the prometheus metrics emitted by descheduler?

Job status can be found from [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cronjob-metrics.md). But I'm curious about the way in which others are pushing prometheus metrics to https://github.com/prometheus/pushgateway or using another way to capture them?

**Comment by damemi** [comment]
@audip the descheduler can also be run as a regular Deployment with `--descheduling-interval` or the `DeschedulingInterval` setting set. This will have it run on a regular loop and be long-lived.

This isn't very well documented (which we could improve) but it's fairly similar to deploying it as a Job or running any other app as a Deployment

**Comment by audip** [comment]
Ah, I see. That totally makes sense. I will set it up as a deployment. 

Are y'all open to adding a Run as Deployment to the README and the k8s YAML (and helm files) for it? I can contribute it in a day or two

**Comment by damemi** [comment]
Sure! We discussed adding some examples for that. If you have the time, feel free to open a PR

**Comment by audip** [comment]
A follow-up question, is the metrics endpoint served by default? I'm having trouble trying to scrape the metrics endpoint (maybe a bug in metrics registration?)

Here's the configuration I'm deploying (for reference):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: descheduler
  namespace: prod
  labels:
    app: descheduler
spec:
    replicas: 1
    selector:
      matchLabels:
        app: descheduler
    template:
      metadata:
        name: descheduler
        labels:
          app: descheduler
      spec:
        priorityClassName: system-cluster-critical
        serviceAccountName: descheduler
        containers:
          - name: descheduler
            image: k8s.gcr.io/descheduler/descheduler:v0.20.0
            imagePullPolicy: IfNotPresent
            command:
              - "/bin/descheduler"
            args:
              - "--policy-config-file"
              - "/policy-dir/policy.yaml"
              - "--descheduling-interval"
              - "60m"
              - "--v"
              - "3"
            ports:
            - containerPort: 10258
              name: metrics
              protocol: TCP
            resources:
              requests:
                cpu: 500m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 256Mi
            volumeMounts:
              - mountPath: /policy-dir
                name: policy-volume
        volumes:
        - name: policy-volume
          configMap:
            name: descheduler
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler
  namespace: prod
  labels:
    app: descheduler
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    nodeSelector: kubernetes.io/role=node
    maxNoOfPodsToEvictPerNode: 2
    strategies:
      RemovePodsViolatingTopologySpreadConstraint:
        enabled: true
      LowNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            targetThresholds:
              memory: 85
            thresholds:
              memory: 40
```
