### ISSUE TITLE
Don't start when there are unknown keys in the config

### ISSUE THREAD

**Issue by der-eismann** [kubernetes-sigs/descheduler#586]
**Is your feature request related to a problem? Please describe.**
Today we decided to try out the descheduler and created a simple config to delete pods from two deployments after 24h. But we put the `labelSelector` in the wrong section so instead it was terminating **everything** that was older than 24h. Luckily we had enough PDBs defined and could stop it in time. Of course one should test everything in a staging environment first, but such a simple mistake shouldn't be enough to delete almost all of your pods.

**Describe the solution you'd like**
Let the program fail if there are unrecognized config keys in a part where they don't belong / use strict unmarshaling.

**Describe alternatives you've considered**
none

**What version of descheduler are you using?**
descheduler version: v0.21.0

**Additional context**
This is/was our config:
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
nodeSelector: node.kubernetes.io/role=worker
evictLocalStoragePods: true
evictSystemCriticalPods: false
ignorePvcPods: false
strategies:
  "PodLifeTime":
    enabled: true
    params:
      podLifeTime:
        maxPodLifeTimeSeconds: 86400
        labelSelector:
          matchExpressions:
            - {key: app, operator: In, values: [app1, app2]}
```
In this case I put the `labelSelector` under the `podLifeTime` key because it seemed logical to me. Instead it needs to be on the same level as `podLifeTime`. In this case the descheduler should fail to start because `podLifeTime` has no `labelSelector` field.
