### ISSUE TITLE
Filter fargate node from checking.

### ISSUE THREAD

**Issue by GodSpeedXI** [kubernetes-sigs/descheduler#605]
I have an EKS cluster which has fargate nodes and ec2 nodes. Descheduler try to evict pods from fargate nodes due to overutilized node.

So, these need to filter out from checking on fargate node because this will make an incorrect result to evict pod from ec2 node.

**Comment by a7i** [comment]
@GodSpeedXI Can you use the [label filtering](https://github.com/kubernetes-sigs/descheduler#label-filtering) on each strategy? Something like below..?
```yaml
      labelSelector:
        matchExpressions:
          - {key: eks.amazonaws.com/fargate-profile, operator: DoesNotExist}
```

There's also `nodeSelector` that can apply to all strategies:
```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
nodeSelector: eks.amazonaws.com/compute-type=ec2
```
