### ISSUE TITLE
TopologySpreadConstraint should not take terminating pods into account when balancing domains

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/descheduler#618]
**What version of descheduler are you using?**

descheduler version: 0.21.0

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
`--logging-format text --policy-config-file /policy-dir/policy.yaml --v 4`

**Please provide a copy of your descheduler policy config file**
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
evictLocalStoragePods: true
strategies:
  RemovePodsViolatingTopologySpreadConstraint:
    enabled: true
    params:
      includeSoftConstraints: true
      labelSelector:
        matchExpressions:
        - {key: descheduler.k8s.io/opt-in, operator: In, values: ["true"]}
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
We have a deployment that has a high termination grace period.  During rollouts, the old pods stick around for some time and depending on when Descheduler runs, this can lead to Descheduler not having an accurate view of topology spread across domains.

This is mainly due to the fact that terminating is not a pod phase and the actual pod phase is running. The only distintion is the `metadata.deletionTimestamp`

**What did you expect to see?**
Descheduler to filter out terminating pods when running the strategy.

**What did you see instead?**
Descheduler takes terminating pods into account (i.e. filter by pods missing `metadata.deletionTimestamp`) when running the strategy.
