### ISSUE TITLE
Support labelSelector in RemoveDuplicates

### ISSUE THREAD

**Issue by palmerabollo** [kubernetes-sigs/descheduler#654]
**Is your feature request related to a problem? Please describe.**

Some strategies such as RemovePodsViolatingInterPodAntiAffinity support a `labelSelector` parameter. However, RemoveDuplicates does not support it and comes in handy in some scenarios.

**Describe the solution you'd like**

I'd like to support `labelSelector` to define a RemoveDuplicates strategy such as:

```yaml
    strategies:
      RemoveDuplicates:
        enabled: true
        params:
          labelSelector:
            matchExpressions:
              - key: foo
                operator: NotIn
                values:
                  - bar
```
     
**What version of descheduler are you using?**

descheduler version: 0.20 but the same applies to 0.22 afaik

**Additional context**

Thank you!
