### ISSUE TITLE
MostRequestedPriority is still mentioned in documentation, but seems to be gone many releases ago 

### ISSUE THREAD

**Issue by omichels** [kubernetes-sigs/descheduler#668]
The documentation of strategy HighNodeUtilization states that it must be used in conjunction with MostRequestedPriority.

But MostRequestedPriority is gone and nowhere documented. It would suggest to remove it from the docs

**Comment by damemi** [comment]
Thanks @omichels, it does look like that plugin was removed and we didn't update it. The `NodeResourcesMostAllocated` plugin has also been deprecated, so it looks like the replacement is now to use `NodeResourcesFit` with the [`MostAllocated` scoring strategy](https://github.com/kubernetes/kubernetes/blob/ec8e6e877899442da9eb0c87a9612cb4dc20373a/pkg/scheduler/apis/config/types_pluginargs.go#L73) based on these docs https://kubernetes.io/docs/reference/scheduling/config/#scheduling-plugins

The idea still stands, that with HighNodeUtilization you should have some sort of bin-packing plugin enabled in the scheduler otherwise you'll get an eviction loop due to the conflict of what the scheduler wants vs what the descheduler wants.

/kind documentation

**Comment by omichels** [comment]
So, in order to avoid a conflict (pods get evicted by the descheduler and then scheduled on that same node by the scheduler), i need a non-default scheduler configuration? 

Do you happen to have a configuration example?

**Comment by damemi** [comment]
@omichels yes, by default the scheduler will try to place pods evenly spread according to their resource consumption on the nodes to achieve the lowest resource consumption on all nodes. With HighNodeUtilization, the descheduler is assuming that you want the pods packed as tightly as possible to target high resource consumption on the fewest nodes.

I don't have an exact example, so you might need to tweak this, but your scheduler config would look something like this (in k8s 1.23 we have `multiPoint`, in earlier versions you'll use `v1beta2` and disable BalancedAllocation in `preScore` and `Score` individually, see kind of an example in https://kubernetes.io/docs/reference/scheduling/config/#multiple-profiles):
```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: default-scheduler
    plugins:
      multiPoint:
        disabled:
        - name: "NodeResourcesBalancedAllocation"
    pluginConfig:
    - name: "NodeResourcesFit"
      args:
        scoringStrategy: 
          type: "MostAllocated"
```

There's an example for using NodeResourcesFit in the k8s docs on scheduler config as well https://kubernetes.io/docs/reference/scheduling/config/#scheduler-configuration-migrations
