### ISSUE TITLE
TopologySpreadConstraint not respected 

### ISSUE THREAD

**Issue by simonpie** [kubernetes-sigs/descheduler#672]
**What version of descheduler are you using?**

descheduler version: v0.22.0

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
none

**Please provide a copy of your descheduler policy config file**
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingTopologySpreadConstraint":
         enabled: true
         params:
           includeSoftConstraints: false
```

**What k8s version are you using (`kubectl version`)?**
1.21

<details><summary><code>kubectl version</code> Output</summary><br><pre>
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

and
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</pre></details>

**What did you do?**

I deployed the descheduler as a deployment as described here : https://github.com/kubernetes-sigs/descheduler#run-as-a-deployment

I deployed both in a vanilla regional cluster over GCP and on our internal regional on-prem lab cluster.

In both cases, scaling to a large number of pods works fine.  Spreading happens as expected according to parameters.  But descaling seems to favor emptying full nodes and does not care for spreading at all.  As ca be seen in the snippet below, scalling to over 3 times more pods (13) as the number of available nodes scales fine.  But scaling down to 7 pods, one nodes is fully emptied. 

```
[Ananke:: 15:05:18] [---] > kc scale deployment httpbin  --replicas=13                      
deployment.apps/httpbin scaled
[Ananke:: 15:05:29] [---] > kc get pods -o wide | awk '/httpbin/{print $7}' | sort | uniq -c
   3 lablkbw11a
   3 lablkbw11b
   4 lablkbw12a
   3 lablkbw12b
[Ananke:: 15:05:33] [---] >
[Ananke:: 15:05:36] [---] > kc scale deployment httpbin  --replicas=7 
deployment.apps/httpbin scaled
[Ananke:: 15:05:50] [---] > sleep 40                                 
[Ananke:: 15:06:36] [---] > kc get pods -o wide | awk '/httpbin/{print $7}' | sort | uniq -c
   2 lablkbw11a
   2 lablkbw11b
   3 lablkbw12b
[Ananke:: 15:06:42] [---] >  
```

This is on a lab with 4 workers and the following topology : 

```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
leaderElection:
  leaseDuration: 15s
  renewDeadline: 10s
profiles:
- pluginConfig:
  - args:
      defaultConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      defaultingType: List
    name: PodTopologySpread
```

The same was done one GCP ( google cloud platform ) with a vanilla cluster, but the topology was put in the pod section of the deployment.

**What did you expect to see?**

I would expect to see somthing like this : 

```
[Ananke:: 15:05:36] [---] > kc scale deployment httpbin  --replicas=7 
deployment.apps/httpbin scaled
[Ananke:: 15:05:29] [---] > kc get pods -o wide | awk '/httpbin/{print $7}' | sort | uniq -c
   2 lablkbw11a
   2 lablkbw11b
   2 lablkbw12a
   1 lablkbw12b
[Ananke:: 15:05:33] [---] >
```

**What did you see instead?**

See above
