### ISSUE TITLE
Extend descheduler to support out-of-tree strategies

### ISSUE THREAD

**Issue by Garrybest** [kubernetes-sigs/descheduler#679]
**Is your feature request related to a problem? Please describe.**

Now `descheduler` only supports the [built-in strategies](https://github.com/kubernetes-sigs/descheduler/blob/0b2c10d6cee917bc553f743c44c51e730f9b1205/pkg/descheduler/descheduler.go#L83-L95). If someone has their own strategies, they must fork this repo and modify the source code. It is not really elegant because when `descheduler` has been upgraded, they must rebase their codes and maybe fix some conflicts.

**Describe the solution you'd like**

I wanna add a registry factory in `descheduler`. Users only need to:

1. Depend this repo in their own project.
2. Implement the strategy interface of their own strategy as a plugin factory to tell `descheduler` to add the strategies.
3. Register the plugins as a parameter by calling `NewDeschedulerCommand`.

The inspiration is from `kube-scheduler` out-of-tree plugin registry. The project [scheduler-plugin](https://github.com/kubernetes-sigs/scheduler-plugins) is based on this cool function. It adds new scheduler plugins without modifying any source codes in `kube-scheduler`.

**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version:

**Additional context**

**Comment by Garrybest** [comment]
cc @damemi @ingvagabund

**Comment by damemi** [comment]
I think we've mentioned this idea before, but haven't formalized it. I like the idea of a descheduler framework modeled after the scheduler framework. And, most of the concepts are already established. I think along with a couple other ideas like https://github.com/kubernetes-sigs/descheduler/issues/646 https://github.com/kubernetes-sigs/descheduler/issues/586 and https://github.com/kubernetes-sigs/descheduler/issues/486 this could be a good time to start reviving the [v1alpha2 proposal](https://docs.google.com/document/d/1S1JCh-0F-QCJvBBG-kbmXiHAJFF8doArhDIAKbOj93I/edit#)

**Comment by Dentrax** [comment]
Hey @damemi, just read the `v1alpha2` proposal. Just wanted to propose a custom resource for the `Strategy` to implement custom strategies as mentioned in #686.


What I'm looking for is something like `DeschedulerStrategy`:

```
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerStrategy"
name: "MyCustomStrategy"
...

# just for an example, roughly written
podFilter:
 filter: "FilterType"
 with_namespaces:
  - foo
 without_namespaces:
  - bar
 label_selector: "baz"

strategy:
 for_each: "node"
 pods: "ListPodsOnANode"
 when:
  ...
 action:
  ...
```

So we can use the strategy in the DeschedulerPolicy:

```
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
- name: "my-custom-policy"
  strategies:
    "MyCustomStrategy"
     ...
...
```

Thoughts? 🤔
