### ISSUE TITLE
Issues with constant descheduling

### ISSUE THREAD

**Issue by mnorrsken** [kubernetes-sigs/descheduler#707]
**What version of descheduler are you using?**

descheduler version: v0.22.1

**Does this issue reproduce with the latest release?**

**Which descheduler CLI options are you using?**

`--policy-config-file /policy-dir/policy.yaml --descheduling-interval 5m --v 3`

**Please provide a copy of your descheduler policy config file**

```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  LowNodeUtilization:
    enabled: true
    params:
      nodeResourceUtilizationThresholds:
        targetThresholds:
          cpu: 50
          memory: 50
          pods: 50
        thresholds:
          cpu: 20
          memory: 20
          pods: 20
      thresholdPriorityClassName: non-preemptible
  RemoveDuplicates:
    enabled: true
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: true
  RemovePodsViolatingNodeAffinity:
    enabled: true
    params:
      nodeAffinityType:
      - requiredDuringSchedulingIgnoredDuringExecution
  RemovePodsViolatingNodeTaints:
    enabled: true
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6+k3s1", GitCommit:"df033fa248bc2c9f636e4c0ff2b782cb8edbbf10", GitTreeState:"clean", BuildDate:"2021-11-04T00:25:07Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6+k3s1", GitCommit:"df033fa248bc2c9f636e4c0ff2b782cb8edbbf10", GitTreeState:"clean", BuildDate:"2021-11-04T00:25:07Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
```

**What did you do?**

Run scheduler as a deployment or cron job

**What did you expect to see?**

Sensible descheduling of pods, maybe using a rate-limit or random order, or not invoking LowNodeUtilization when ALL nodes have a low utilizaiton.

**What did you see instead?**

Constant descheduling of the same pod over and over again even though all nodes are pretty equal in utilization:

![image](https://user-images.githubusercontent.com/46407660/151663280-6e131bbb-6a0e-4011-8417-2ef5bc380c17.png)
