### ISSUE TITLE
How to scrape metrics

### ISSUE THREAD

**Issue by mateuszdrab** [kubernetes-sigs/descheduler#718]
Hi

I can see that recently, a PR was merged to enable metrics support - however no documentation has been created to provide instructions how to use it.
I tried to create a podmonitor like this:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  creationTimestamp: "2022-02-07T17:45:56Z"
  generation: 2
  labels:
    app: descheduler
  name: descheduler
  namespace: kube-system
spec:
  jobLabel: descheduler
  namespaceSelector:
    matchNames:
    - kube-system
  podMetricsEndpoints:
  - honorLabels: true
    interval: 5s
    path: /metrics
    scheme: http
    targetPort: 10258
  selector:
    matchLabels:
      app: descheduler
```

Unfortunately, no metrics are collected. I'm running descheduler as a CronJob. Could it be that I need to run it as a deployment and create a service monitor instead?

Perhaps a sample could be provided for the monitor or better, included in the helm chart?

Thanks
