### ISSUE TITLE
HighNodeUtilization does nothing when all nodes are underutilized

### ISSUE THREAD

**Issue by slobo** [kubernetes-sigs/descheduler#725]
**What version of descheduler are you using?**

descheduler version: 0.23

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
Using helm chart 0.23.1 with these overrides:
```yaml
deschedulerPolicy:
  strategies:
    HighNodeUtilization:
      enabled: true
      params:
        nodeResourceUtilizationThresholds:
          thresholds:
            memory: 20
        numberOfNodes: 0
    LowNodeUtilization:
      enabled: false
schedule: 5 10 * * *
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

Installed descheduler. Ran the cron job manually.

**What did you expect to see?**

Descheduler evict pods from some of the underutilized instances.

**What did you see instead?**

Descheduler didn't evict any pods. Saw this in the log:

```
I0214 21:57:50.046412       1 highnodeutilization.go:90] "Criteria for a node below target utilization" CPU=100 Mem=20 Pods=100
I0214 21:57:50.046417       1 highnodeutilization.go:91] "Number of underutilized nodes" totalNumber=4
I0214 21:57:50.046421       1 highnodeutilization.go:102] "All nodes are underutilized, nothing to do here"
```

These lines of code https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/strategies/nodeutilization/highnodeutilization.go#L101-L103 seem to be very similar to code in LowNodeUtilization https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/strategies/nodeutilization/lownodeutilization.go#L128-L130, perhaps a stray copy-paste?
