### ISSUE TITLE
Add a "Do Not Deschedule" label

### ISSUE THREAD

**Issue by BryanDollery** [kubernetes-sigs/descheduler#802]
**Is your feature request related to a problem? Please describe.**

I have a k8s cluster of small nodes and I'm trying to deploy Sonatype Nexus (OSS version) to it. My own pods are quite small -- all using <500Mi/250m memory and CPU limits. Nexus however is huge by comparison with a 4Gi memory limit and wanting 500m CPU. When I schedule nexus, descheduler notices the memory pressure on its node, notes that other nodes have lots of free memory, and deschedules it. As soon as it is running on this other node for a couple of minutes, descheduler does it again. And again. 

The result is that I can't keep nexus alive for more than a couple of minutes.

**Describe the solution you'd like**
The easiest thing for me would be to put a 'do not reschedule' label on the nexus pod, to instruct descheduled to leave this one alone. 

**Describe alternatives you've considered**
I know that I can set a priority class to achieve the same thing, but that would be to misuse the priorities available to me (node or cluster critical)
**What version of descheduler are you using?**

descheduler version:
Image label: 0.23.1

**Additional context**
I'm using the default yaml
```yaml
strategies:
  LowNodeUtilization:
    enabled: true
    params:
      nodeResourceUtilizationThresholds:
        targetThresholds:
          cpu: 50
          memory: 50
          pods: 50
        thresholds:
          cpu: 20
          memory: 20
          pods: 20
  RemoveDuplicates:
    enabled: true
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: true
  RemovePodsViolatingNodeAffinity:
    enabled: true
    params:
      nodeAffinityType:
      - requiredDuringSchedulingIgnoredDuringExecution
  RemovePodsViolatingNodeTaints:
    enabled: true
```
