### ISSUE TITLE
no matches for kind "DeschedulerPolicy" in version "descheduler/v1alpha1"

### ISSUE THREAD

**Issue by st0ner** [kubernetes-sigs/descheduler#807]
**What version of descheduler are you using?**

descheduler version: v0.23.1

**Does this issue reproduce with the latest release?**
I see the problem in all versions

**Which descheduler CLI options are you using?**
--policy-config-file /policy-dir/policy.yaml --descheduling-interval 5m --v 3

**Please provide a copy of your descheduler policy config file**
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  LowNodeUtilization:
    enabled: true
    params:
      nodeResourceUtilizationThresholds:
        targetThresholds:
          cpu: 50
          memory: 50
          pods: 50
        thresholds:
          cpu: 20
          memory: 20
          pods: 20
  RemoveDuplicates:
    enabled: true
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: true
  RemovePodsViolatingNodeAffinity:
    enabled: true
    params:
      nodeAffinityType:
      - requiredDuringSchedulingIgnoredDuringExecution
  RemovePodsViolatingNodeTaints:
    enabled: true
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
I setup clear baremetal k8s cluster with kubespray.
Install descheduler with [helm](https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/README.md)
`helm install descheduler --namespace kube-system descheduler/descheduler --set kind=Deployment`
And trying add yaml
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "PodLifeTime":
    enabled: true
    params:
      podLifeTime:
        maxPodLifeTimeSeconds: 300
        namespaces: "somenamespace"
        labelSelector: 
          matchLabels:
            app.kubernetes.io/instance: somelabel
            app.kubernetes.io/name: somelabel
```

**What did you expect to see?**
resource in kubectl api-versions

**What did you see instead?**
error: unable to recognize "test.yaml": no matches for kind "DeschedulerPolicy" in version "descheduler/v1alpha1"
