### ISSUE TITLE
Descheduler should sort pods by age for PodLifeTime

### ISSUE THREAD

**Issue by bwmetcalf** [kubernetes-sigs/descheduler#816]
**What version of descheduler are you using?**

descheduler version: 0.23.1

**Does this issue reproduce with the latest release?**

Unknown

**Please provide a copy of your descheduler policy config file**

```
deschedulerPolicy:
  evictLocalStoragePods: true
  ignorePvcPods: true
  nodeSelector: ""
  strategies:
    HighNodeUtilization:
      enabled: false
      params:
        nodeFit: true
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 40
            memory: 70
            pods: 80
    LowNodeUtilization:
      enabled: false
    PodLifeTime:
      enabled: true
      params:
        labelSelector:
          matchLabels:
            app.umbra.space/deschedule-pod-lifetime: "true"
        podLifeTime:
          maxPodLifeTimeSeconds: 120
    RemoveDuplicates:
      enabled: false
    RemoveFailedPods:
      enabled: false
    RemovePodsHavingTooManyRestarts:
      enabled: false
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: false
    RemovePodsViolatingNodeAffinity:
      enabled: false
    RemovePodsViolatingNodeTaints:
      enabled: false
    RemovePodsViolatingTopologySpreadConstraint:
      enabled: false
kind: Deployment
nodeSelector:
  node.umbra.space/basenode: "true"
```

**What k8s version are you using (`kubectl version`)?**

1.22

**What did you do?**

Set `maxPodLifeTimeSeconds` to 120 and `deschedulingInterval` to 5m.  Using an example of a two replica deployment with a pod disruption budget  `minAvailable` set to 1.  This will result in descheduler trying to evict both pods because both will always be older than 120s.  One eviction will fail due to the pdb.

The descheduler should sort by the pods by age and evict the oldest one first.  The descheduler seems to always evict the "first" pod as listed in `kubectl get pods` which sorts alphanumerically.

**What did you expect to see?**

The descheduler should evict the older pod first.

**What did you see instead?**

The descheduler always evicts the first pod listed and therefore the second continues to grow in age.
