### ISSUE TITLE
allow namespace filter to use a namespace selector

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/descheduler#901]
**Problem description**

in a cluster where namespaces are frequently created and destroyed (for example because tenants are onboarded and removed) listing the included/excluded namespaces as an array makes it necessary to frequently patch the Policy object

**Describe the solution you'd like**
a namespace selector (based on label) can be specified in alternative to the include/exclude list. This is the standard that is followed by many other operators.

**Describe alternatives you've considered**
none

**What version of descheduler are you using?**
latest

**Additional context**

**Comment by JaneLiuL** [comment]
yet, good idea~~ 
would you like to have a try on this feature ? @raffaelespazzoli

**Comment by a7i** [comment]
I also like the flexibility it brings but should we do this work as part of `descheduler/v1alpha2` initiative? Given the breaking changes.

cc: @ingvagabund  @damemi

**Comment by damemi** [comment]
Would it be a breaking change to make the namespace include/exclude fields a regex? Current settings with alphanumeric namespace strings would still only match the exact name, so the functionality is the same. As long as no regex special characters are allowed in k8s namespace names.

I am not sure about taking a labelling approach as it decouples descheduler config from the descheduler itself, which I could see causing headaches

**Comment by a7i** [comment]
In my organization, we're discussing use-cases around skipping a namespace via a label. Currently, we have to re-deploy Descheduler to exclude a namespace. [Alternatively, we can label each Deployment as well]

It would be ideal for us to label a namespace and have it be ignored by Descheduler.
example:
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: example
  labels:
    descheduler.k8s.io/opt-out: "true"
```

Where my Descheduler configuration would define a `namespaceSelector` at a plugin definition:
```yaml
 namespaceSelector:
   matchExpressions:
   - key: descheduler.k8s.io/opt-out
     operator: In
     values: ["true"]
```

cc: @jklaw90
