### ISSUE TITLE
Incorrect work with HPA (when replicas more than number of nodes)

### ISSUE THREAD

**Issue by OuFinx** [kubernetes-sigs/descheduler#921]
**What version of descheduler are you using?**

descheduler version: 0.24.1

**Does this issue reproduce with the latest release?**

Yes

**Please provide a copy of your descheduler policy config file**

I've deployed with default variables

```
helm repo add descheduler https://kubernetes-sigs.github.io/descheduler/
helm install my-release --namespace kube-system descheduler/descheduler
```

```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
evictLocalStoragePods: true
strategies:
  LowNodeUtilization:
    enabled: false
  RemoveDuplicates:
    enabled: true
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: true
  RemovePodsViolatingNodeAffinity:
    enabled: false
  RemovePodsViolatingNodeTaints:
    enabled: false
```

**What k8s version are you using (`kubectl version`)?**

```
$ kubectl version
v1.21.9
```

**What did you do?**

In my cluster I've deployed deployment with [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/). 

Cluster has 5 nodes and HPA config has minimum 2 and maximum 10 pods

My application was scaled up by HPA up to 10 replicas.

After an hour, I noticed that HPA can't scale down my application back to 2 replicas. I checked my pods and saw that descheduler every 2 minutes trying to remove duplicates from the nodes, so it restarts 3 pods every 2 minutes. 

After each restart, HPA recalculates CPU/RAM metrics and keeps 10/10 replicas. 

Shortly speaking, in this situation, HPA never scaled my replicas back to 2/10 due to Descheduler behaviour.

Also, I think, without HPA will be the same situation (_with the same number of replicas and worker nodes_)

**What did you expect to see?**

I expect that descheduler won't infinitive restart pods if the number of replicas is more than twice the worker nodes.

**What did you see instead?**

Descheduler kill 3 of 10 pods each 2 minutes when I have 5 worker nodes and 10 replicas.

```
"Processing node" node="ip-172-11-33-36.ec2.internal"
"Duplicate found" pod="sandbox/worker-dc454495d-b2c49"
"Duplicate found" pod="sandbox/worker-dc454495d-8x62z"
"Processing node" node="ip-172-11-39-138.ec2.internal"
"Processing node" node="ip-172-11-39-67.ec2.internal"
"Processing node" node="ip-172-11-52-28.ec2.internal"
"Duplicate found" pod="sandbox/worker-dc454495d-w9vpj"
"Duplicate found" pod="sandbox/worker-dc454495d-9b8hn"
"Duplicate found" pod="sandbox/worker-dc454495d-rhxkk"
"Processing node" node="ip-172-11-11-27.ec2.internal"
"Evicted pod" pod="sandbox/worker-dc454495d-9b8hn" reason="RemoveDuplicatePods" strategy="RemoveDuplicatePods" node="ip-172-11-52-28.ec2.internal"
"Evicted pod" pod="sandbox/worker-dc454495d-rhxkk" reason="RemoveDuplicatePods" strategy="RemoveDuplicatePods" node="ip-172-11-52-28.ec2.internal"
"Evicted pod" pod="sandbox/worker-dc454495d-8x62z" reason="RemoveDuplicatePods" strategy="RemoveDuplicatePods" node="ip-172-11-33-36.ec2.internal"
```

**Comment by damemi** [comment]
We've actually tried fixing this issue before, as reported in https://github.com/kubernetes-sigs/descheduler/issues/263 and addressed in https://github.com/kubernetes-sigs/descheduler/pull/463, which takes more of an approach to remove duplicate pods based on the average number per node. In this case that's 10/5=2, so any node with more than 2 replicas is going to evict at least one. RemoveDuplicates is a pretty strict strategy that doesn't allow for any skew. 

This can be difficult to enforce as there are other scheduling criteria that could cause duplicates to be re-scheduled onto the same node.

If you are looking to tolerate some skew, and not strictly try to enforce each node to have as few duplicates as mathematically possible, I recommend using [topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/). This is a much better way to distribute workloads with some wiggle room, and we have a descheduler strategy to rebalance topologies on scale changes

**Comment by OuFinx** [comment]
Ok, let me test with [topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/).
It will take me around 1h

**Comment by OuFinx** [comment]
**Descheduler config:**

```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
evictLocalStoragePods: true
strategies:
  LowNodeUtilization:
    enabled: false
  RemoveDuplicates:
    enabled: false
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: true
  RemovePodsViolatingNodeAffinity:
    enabled: false
  RemovePodsViolatingNodeTaints:
    enabled: false
  RemovePodsViolatingTopologySpreadConstraint:
    enabled: true
    params:
      includeSoftConstraints: true
```

**Descheduler logs:**

```
"Evicted pod" pod="sandbox/worker-dc454495d-t66mn" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-38-28.ec2.internal"

"Event occurred" object="sandbox/worker-dc454495d-t66mn" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerPodTopologySpread"

"Evicted pod" pod="sandbox/worker-dc454495d-fzmx6" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-38-28.ec2.internal"

"Event occurred" object="sandbox/worker-dc454495d-fzmx6" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerPodTopologySpread"

"Evicted pod" pod="sandbox/worker-dc454495d-8rkwd" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-38-28.ec2.internal"

"Event occurred" object="sandbox/worker-dc454495d-8rkwd" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerPodTopologySpread"

"Evicted pod" pod="sandbox/worker-dc454495d-8bmmp" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-38-28.ec2.internal"

I0824 14:30:04.484400       1 descheduler.go:304] "Number of evicted pods" totalEvicted=4
```

**Deployment topologySpreadConstraints config**:

```
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: lifecycle
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            "app": {{ .Release.Name | quote }}
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            "app": {{ .Release.Name | quote }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 4
            preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - spot
          - weight: 5
            preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - on-demand
```

**Result**:

Descheduler evict 4 pods every 2 minutes

**Comment by OuFinx** [comment]
After all tests with `topologySpreadConstraints` I can say that the problem with

```
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            "app": {{ .Release.Name | quote }}
```

It's trying to evict pods all the time

If I don't set this second topology and have only this one:

```
      - maxSkew: 1
        topologyKey: lifecycle
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            "app": {{ .Release.Name | quote }}
```

It works, but, until 20 replicas. I noticed that after 20+ replicas, descheduler starts evictin ~4-5 pods every time.

**Comment by damemi** [comment]
@OuFinx could you share the output for `kubectl get pods -o wide` in that namespace? Might be easier to see what pods are on what nodes to get a better idea of the spread.

**Comment by OuFinx** [comment]
@damemi sure

Conditions:

```
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: lifecycle
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            "app": {{ .Release.Name | quote }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 4
            preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - spot
          - weight: 5
            preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - on-demand
```

and 

```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
evictLocalStoragePods: true
strategies:
  LowNodeUtilization:
    enabled: false
  RemoveDuplicates:
    enabled: false
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: true
  RemovePodsViolatingNodeAffinity:
    enabled: false
  RemovePodsViolatingNodeTaints:
    enabled: false
  RemovePodsViolatingTopologySpreadConstraint:
    enabled: true
    params:
      includeSoftConstraints: true
```

**Test #1:** 5 replicas 
```
NAME                                         READY   STATUS    RESTARTS   AGE     IP              NODE                            NOMINATED NODE   READINESS GATES
worker-8fc5bcbcc-2crw8   2/2     Running   0          43m     172.11.28.19    ip-172-11-19-221.ec2.internal   <none>           <none>
worker-8fc5bcbcc-5zxkg   2/2     Running   0          89s     172.11.33.44    ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-gqth6   2/2     Running   0          75s     172.11.34.73    ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-mc8jx   2/2     Running   0          90s     172.11.34.186   ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-x6qbj   2/2     Running   0          2m16s   172.11.38.26    ip-172-11-38-28.ec2.internal    <none>           <none>
```

Descheduler output 

```
"Number of evicted pods" totalEvicted=0
```

**Test #2** (_the same conditions_): 30 replicas

```
NAME                                         READY   STATUS    RESTARTS   AGE     IP              NODE                            NOMINATED NODE   READINESS GATES
worker-8fc5bcbcc-24hjq   2/2     Running   0          3m37s   172.11.32.47    ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-2crw8   2/2     Running   0          51m     172.11.28.19    ip-172-11-19-221.ec2.internal   <none>           <none>
worker-8fc5bcbcc-2fntc   2/2     Running   0          3m35s   172.11.37.44    ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-45dgk   2/2     Running   0          3m38s   172.11.47.83    ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-59fmj   2/2     Running   0          47s     172.11.30.162   ip-172-11-19-221.ec2.internal   <none>           <none>
worker-8fc5bcbcc-5n6sg   2/2     Running   0          3m35s   172.11.19.184   ip-172-11-19-41.ec2.internal    <none>           <none>
worker-8fc5bcbcc-5zxkg   2/2     Running   0          9m10s   172.11.33.44    ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-62z9w   2/2     Running   0          83s     172.11.25.211   ip-172-11-19-221.ec2.internal   <none>           <none>
worker-8fc5bcbcc-75vkx   2/2     Running   0          84s     172.11.45.24    ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-8kt2h   2/2     Running   0          47s     172.11.30.190   ip-172-11-19-221.ec2.internal   <none>           <none>
worker-8fc5bcbcc-8n69r   2/2     Running   0          83s     172.11.28.44    ip-172-11-19-41.ec2.internal    <none>           <none>
worker-8fc5bcbcc-98lkk   2/2     Running   0          3m11s   172.11.46.130   ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-b77k9   2/2     Running   0          3m38s   172.11.38.5     ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-bhjcw   2/2     Running   0          3m39s   172.11.42.28    ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-cdd8m   2/2     Running   0          3m38s   172.11.41.50    ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-cps66   2/2     Running   0          3m33s   172.11.32.134   ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-drpst   2/2     Running   0          83s     172.11.43.142   ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-fbtng   2/2     Running   0          3m33s   172.11.18.1     ip-172-11-19-41.ec2.internal    <none>           <none>
worker-8fc5bcbcc-ghsbb   2/2     Running   0          3m37s   172.11.44.94    ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-gqth6   2/2     Running   0          8m56s   172.11.34.73    ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-grmq6   2/2     Running   0          3m33s   172.11.40.110   ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-hj99r   2/2     Running   0          3m39s   172.11.35.122   ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-jmq4b   2/2     Running   0          3m33s   172.11.43.120   ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-mc8jx   2/2     Running   0          9m11s   172.11.34.186   ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-mq49g   2/2     Running   0          3m37s   172.11.11.133   ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-p4fz2   2/2     Running   0          3m37s   172.11.32.71    ip-172-11-42-11.ec2.internal    <none>           <none>
worker-8fc5bcbcc-rrrdc   2/2     Running   0          83s     172.11.28.149   ip-172-11-19-221.ec2.internal   <none>           <none>
worker-8fc5bcbcc-x5wpj   2/2     Running   0          3m35s   172.11.44.30    ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-x6qbj   2/2     Running   0          9m57s   172.11.38.26    ip-172-11-38-28.ec2.internal    <none>           <none>
worker-8fc5bcbcc-zcrjh   2/2     Running   0          46s     172.11.40.0     ip-172-11-42-11.ec2.internal    <none>           <none>
```

Descheduler output 

```
"Evicted pod" pod="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-p4fz2" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-42-11.ec2.internal"
"Event occurred" object="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-p4fz2" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerPodTopologySpread"
"Evicted pod" pod="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-rrrdc" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-19-221.ec2.internal"
"Event occurred" object="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-rrrdc" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerPodTopologySpread"
"Evicted pod" pod="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-zcrjh" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-42-11.ec2.internal"
"Event occurred" object="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-zcrjh" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerPodTopologySpread"

"Number of evicted pods" totalEvicted=3
```

Run descheduler one more time

```
"Evicted pod" pod="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-j2d86" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-19-41.ec2.internal"
"Event occurred" object="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-j2d86" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerPodTopologySpread"
"Evicted pod" pod="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-mjx82" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-42-11.ec2.internal"
"Event occurred" object="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-mjx82" fieldPath="" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerPodTopologySpread"
"Evicted pod" pod="kudo-kcp-sandbox/kudo-kcp-stagingnxt-worker-8fc5bcbcc-x5pmc" reason="PodTopologySpread" strategy="PodTopologySpread" node="ip-172-11-42-11.ec2.internal"
I0824 17:38:37.152048       1 descheduler.go:304] "Number of evicted pods" totalEvicted=3
```

**Comment by damemi** [comment]
Your pods don't seem to be properly distributed when they're scheduled.

In the first test, you should have more than 0 evictions because the nodes are out of skew (3 pods/1 pod/1pod, skew is 2 but your maxSkew is only 1, so you should have 1 eviction from `ip-172-11-38-28.ec2.internal`)

Then in your larger test, I only see pods scheduled onto 4 nodes (not 5):
* `ip-172-11-42-11.ec2.internal` - 10 pods
* `ip-172-11-19-221.ec2.internal` - 5 pods
* `ip-172-11-38-28.ec2.internal` - 12 pods
* `ip-172-11-19-41.ec2.internal` - 3 pods

Could you do `kubectl get nodes` and share the yaml for whichever node isn't listed above? It must be unavailable or something

these are all out of skew, which is fine from the scheduler's point of view because the constraints are only `ScheduleAnyway`. The descheduler is still going to try evicting in order to balance them though. What happens if you make the constraints `DoNotSchedule`?

I think ultimately the descheduler is working as it's supposed to but there is a problem in how your pods are getting scheduled

**Comment by OuFinx** [comment]
In the test with 5 replicas, node `ip-172-11-38-28.ec2.internal` has label `on-demand`.
And other nodes have label `spot`.

So, 1 on-demand and 4 spot. 

Based on `topologySpreadConstraints` and `nodeAffinity `,  score for on-demand is 20 points greater than for spot (_weights are normalized: 4->80, 5->100_)

For this reasons, I believe all pods were distributed in this way.

There is `yaml` file from the node that isn't listed above

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    csi.volume.kubernetes.io/nodeid: '{"efs.csi.aws.com":"i-009139f35126af400"}'
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: t3.xlarge
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1d
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: i-009139f35126af400
    kubernetes.io/os: linux
    lifecycle: spot
    node.kubernetes.io/instance-type: t3.xlarge
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1d
  name: ip-172-11-42-11.ec2.internal
spec:
  providerID: aws:///us-east-1d/i-009139f35126af400
status:
  addresses:
  - address: 172.11.42.11
    type: InternalIP
  - address: ip-172-11-42-11.ec2.internal
    type: Hostname
  - address: ip-172-11-42-11.ec2.internal
    type: InternalDNS
  allocatable:
    attachable-volumes-aws-ebs: "25"
    cpu: 3920m
    ephemeral-storage: "95551679124"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 15189028Ki
    pods: "58"
  capacity:
    attachable-volumes-aws-ebs: "25"
    cpu: "4"
    ephemeral-storage: 104845292Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16205860Ki
    pods: "58"
  conditions:
  - lastHeartbeatTime: "2022-08-24T18:04:44Z"
    lastTransitionTime: "2022-08-24T04:02:54Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2022-08-24T18:04:44Z"
    lastTransitionTime: "2022-08-24T04:02:54Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2022-08-24T18:04:44Z"
    lastTransitionTime: "2022-08-24T04:02:54Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2022-08-24T18:04:44Z"
    lastTransitionTime: "2022-08-24T04:04:05Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  nodeInfo:
    architecture: amd64
    bootID: 6008f34c-791c-4c0b-a2b9-28be6d5ea543
    containerRuntimeVersion: docker://20.10.13
    kernelVersion: 5.4.204-113.362.amzn2.x86_64
    kubeProxyVersion: v1.21.12-eks-5308cf7
    kubeletVersion: v1.21.12-eks-5308cf7
    machineID: ec2be60aefd251a26bf5521ca96dc67a
    operatingSystem: linux
    osImage: Amazon Linux 2
    systemUUID: ec2be60a-efd2-51a2-6bf5-521ca96dc67a
```
