### ISSUE TITLE
Balanced pods are being continuously evicted by PodTopologySpread

### ISSUE THREAD

**Issue by dry4ng** [kubernetes-sigs/descheduler#948]
**What version of descheduler are you using?**

descheduler version: 1.24

**Does this issue reproduce with the latest release?**

yes

**Which descheduler CLI options are you using?**

none

**Please provide a copy of your descheduler policy config file**

```
deschedulerPolicy:
  strategies:
    RemoveDuplicates:
      enabled: false
    RemovePodsViolatingNodeTaints:
      enabled: false
    RemovePodsViolatingNodeAffinity:
      enabled: false      
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: false
    LowNodeUtilization:
      enabled: false
    RemovePodsViolatingTopologySpreadConstraint:
      enabled: true
      params:
        includeSoftConstraints: true
```

**What k8s version are you using (`kubectl version`)?**

1.21

**What did you do?**

I have the following config:

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - myapp-node-pool

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: myapp
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: myapp
```

**What did you expect to see?**

My goal is to meet the following conditions:
- pods are placed on `myapp-node-pool`
- pods are evenly distributed across GKE zones
- pods are evenly distributed across nodes in a zone

This is working as expected. I have 8 nodes in 2 zones (4 in each zone): n1a, n2a, n3a, n4a, n1b, n2b, n3b, n4b.
I have 4 replica deployment, and pods are correctly placed on nodes: n1a, n2a, n1b, n2b.

**What did you see instead?**

However every time descheduler runs, it evicts 2 out of 4 pods. Only for them to placed to the same nodes again with message:

```
"Evicted pod" pod="myapp" reason="PodTopologySpread" strategy="PodTopologySpread" node="mynode"
```
