### ISSUE TITLE
 cannot create resource "events" in API group "events.k8s.io" in the namespace "utils"'

### ISSUE THREAD

**Issue by dmitry-mightydevops** [kubernetes-sigs/descheduler#959]
**What version of descheduler are you using?**

descheduler version: `k8s.gcr.io/descheduler/descheduler:v0.25.0`

**Does this issue reproduce with the latest release?**

Yes

**Which descheduler CLI options are you using?**

Not using CLI

**Please provide a copy of your descheduler policy config file**

I'm running it as HELM ([descheduler/descheduler](https://github.com/kubernetes-sigs/descheduler/tree/master/charts/descheduler), 0.25.0) chart with the following values:

```yaml
kind: CronJob
schedule: "*/15 * * * *"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

tolerations:
  {}

affinity:
  {}

nodeSelector:
  {}

deschedulerPolicy:
  evictFailedBarePods: true
  evictLocalStoragePods: true
  ignorePvcPods: false
  maxNoOfPodsToEvictPerNamespace: 10
  maxNoOfPodsToEvictPerNode: 10
  strategies:
    LowNodeUtilization:
      enabled: true
      nodeFit: true
      params:
        nodeResourceUtilizationThresholds:
          targetThresholds:
            cpu: 70
            memory: 70
          thresholds:
            cpu: 40
            memory: 40
    PodLifeTime:
      enabled: true
      params:
        namespaces:
          include:
          - mysql57
          - influxdb
          - mongodb
          - etcd
          - utils
        podLifeTime:
          maxPodLifeTimeSeconds: 86400
    RemoveDuplicates:
      enabled: false
      nodeFit: true
    RemovePodsHavingTooManyRestarts:
      enabled: true
      params:
        podsHavingTooManyRestarts:
          includingInitContainers: true
          podRestartThreshold: 20
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
      nodeFit: true
    RemovePodsViolatingNodeAffinity:
      enabled: true
      nodeFit: true
      params:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
    RemovePodsViolatingNodeTaints:
      enabled: true
      nodeFit: true
    RemovePodsViolatingTopologySpreadConstraint:
      enabled: true
      nodeFit: true
      params:
        includeSoftConstraints: false

successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1

priorityClassName: system-cluster-critical

cmdOptions:
  v: 3
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:32:14Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.7-eks-4721010", GitCommit:"b77d9473a02fbfa834afa67d677fd12d690b195f", GitTreeState:"clean", BuildDate:"2022-06-27T22:19:07Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

I'm getting the following error in the logs
```sh
'events.events.k8s.io is forbidden: User "system:serviceaccount:ops:descheduler" cannot create resource "events" in API group "events.k8s.io" in the namespace "utils"' (will not retry!)
```

**full output:**

```sh
klon ops -l app.kubernetes.io/instance=descheduler

node="ip-10-110-7-206.us-west-2.compute.internal"
ops/descheduler-27732750-hs7xg[descheduler]: E0923 20:30:30.551327       1 event_broadcaster.go:253] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"xxx-xxx-psql-6c86c4c489-dnkq8.1717976114452b5c", GenerateName:"", Namespace:"utils", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, EventTime:time.Date(2022, time.September, 23, 20, 30, 30, 544378065, time.Local), Series:(*v1.EventSeries)(nil), ReportingController:"sigs.k8s.io.descheduler", ReportingInstance:"sigs.k8s.io.descheduler-descheduler-27732750-hs7xg", Action:"Descheduled", Reason:"PodLifeTime", Regarding:v1.ObjectReference{Kind:"Pod", Namespace:"utils", Name:"xxx-xxx-psql-6c86c4c489-dnkq8", UID:"b7a7fcde-5eb0-4e5e-af50-29e695f11e8f", APIVersion:"v1", ResourceVersion:"753022310", FieldPath:""}, Related:(*v1.ObjectReference)(nil), Note:"pod evicted by sigs.k8s.io/descheduler", Type:"Normal", DeprecatedSource:v1.EventSource{Component:"", Host:""}, DeprecatedFirstTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeprecatedLastTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeprecatedCount:0}': 'events.events.k8s.io is forbidden: User "system:serviceaccount:ops:descheduler" cannot create resource "events" in API group "events.k8s.io" in the namespace "utils"' (will not retry!)
ops/descheduler-27732750-hs7xg[descheduler]: I0923 20:30:30.579421       1 evictions.go:160] "Evicted pod" pod="utils/xxx-xxx-mongodb-7d97495d7b-rltfv" reason="" strategy="PodLifeTime" 
```

**What did you expect to see?**

Event to be written in the namespace where the eviction happened.

**What did you see instead?**

```sh
'events.events.k8s.io is forbidden: User "system:serviceaccount:ops:descheduler" cannot create resource "events" in API group "events.k8s.io" in the namespace "utils"' (will not retry!)
```
