### ISSUE TITLE
The pods evicted by LowNodeUtilization are now placed in the same previous Node.

### ISSUE THREAD

**Issue by kahirokunn** [kubernetes-sigs/descheduler#994]
The pods evicted by LowNodeUtilization are now placed in the same previous Node.
A pod evicted by LowNodeUtilization is now placed in the same Node, evicted again by LowNodeUtilization, and placed in the same Node again.
Is there any option not to place them on the same Node?

**Comment by damemi** [comment]
Hi @kahirokunn, the descheduler doesn't have any control over which nodes the newly-recreated pods will be placed on. It can only evict based on what it knows at the time, then it is up to the kube-scheduler to determine where new pods will go.

So when the descheduler evicts a pod from an overutilized node, it's assumed that the kube-scheduler will try to spread that pod onto an underutilized node (this is the kube-scheduler's default behavior). The scheduler could end up choosing the same node for a range of reasons such as affinity, taints, or even image locality in cases where nodes have similar utilization. You can try to adjust for this by tweaking the scheduler config and descheduler thresholds for utilization.

Can you share some more information about what you're seeing, such as your descheduler config, descheduler version, or a sample yaml from one of the evicted pods. We might be able to help out with that

**Comment by kahirokunn** [comment]
Thank you.
I am installing via ArgoCD.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  destination:
    namespace: descheduler
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/descheduler'
    targetRevision: 0.25.2
    chart: descheduler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

I have not set anything in values, so it is the default.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: descheduler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: descheduler
    app.kubernetes.io/version: 0.25.1
    argocd.argoproj.io/instance: descheduler
    helm.sh/chart: descheduler-0.25.2
  name: descheduler
  namespace: descheduler
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      LowNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            targetThresholds:
              cpu: 50
              memory: 50
              pods: 50
            thresholds:
              cpu: 20
              memory: 20
              pods: 20
      RemoveDuplicates:
        enabled: true
      RemovePodsHavingTooManyRestarts:
        enabled: true
        params:
          podsHavingTooManyRestarts:
            includingInitContainers: true
            podRestartThreshold: 100
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true
      RemovePodsViolatingNodeAffinity:
        enabled: true
        params:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
      RemovePodsViolatingNodeTaints:
        enabled: true
      RemovePodsViolatingTopologySpreadConstraint:
        enabled: true
        params:
          includeSoftConstraints: false
```

I basically try to set resources on all pods.
So I want to bias the Nodes with high usage and leave the Nodes with low usage as empty as possible, and let Karpenter scale-in the Nodes so that I don't have to pay for EC2 that I don't need.
I don't know much about what can be done with descheduler and to what extent, so I'm very glad to get your advice.
Thx.
